Bee ERP: newtonERP.common.Authentication Class Reference
newtonERP.common.Authentication Class Reference
Cette classe sert à authentifier un user de manière hardcodée OU par session HTTP Le but de cette classe est d'être gérée par le code qui manipulera les sessions HTTP.
Static Public Member Functions
static String getCurrentUserName ()
static User getCurrentUser ()
static void setCurrentUserName (String currentUserName)
Detailed Description
Cette classe sert à authentifier un user de manière hardcodée OU par session HTTP Le but de cette classe est d'être gérée par le code qui manipulera les sessions HTTP.
Author:
Guillaume Lacasse
Definition at line 12 of file Authentication.java.
Member Function Documentation
static User newtonERP.common.Authentication.getCurrentUser () [static]
Returns:
Entité représentant l'utilisateur courant
Definition at line 27 of file Authentication.java.
References newtonERP.module.AbstractOrmEntity.get(), newtonERP.common.Authentication.getCurrentUserName(), and newtonERP.module.AbstractEntity.setData().
static String newtonERP.common.Authentication.getCurrentUserName () [static]
Returns:
Utilisateur présentement loggé par session HTTP
Definition at line 19 of file Authentication.java.
Referenced by newtonERP.common.Authentication.getCurrentUser().
static void newtonERP.common.Authentication.setCurrentUserName (String currentUserName) [static]
Parameters:
currentUserName Utilisateur présentement loggé par session HTTP
Definition at line 38 of file Authentication.java.
The documentation for this class was generated from the following file:
src/newtonERP/common/Authentication.java