Bee ERP: modules.common.entityDefinitions.Address Class Reference
modules.common.entityDefinitions.Address Class Reference
A warehouse address.
Inherits newtonERP::module::AbstractOrmEntity.
Public Member Functions
Address ()
Default constructor.
Fields initFields ()
initialise les champ de l'entity, doit etre overider si l'entity contient des champs, sinon initialise une liste de champ vide
Detailed Description
A warehouse address.
Author:
r3hallejo
Definition at line 17 of file Address.java.
Constructor & Destructor Documentation
modules.common.entityDefinitions.Address.Address ()
Default constructor.
Definition at line 24 of file Address.java.
References newtonERP.module.AbstractOrmEntity.setVisibleName().
Member Function Documentation
Fields modules.common.entityDefinitions.Address.initFields () [virtual]
initialise les champ de l'entity, doit etre overider si l'entity contient des champs, sinon initialise une liste de champ vide
Returns:
le Fields initialiser
Implements newtonERP.module.AbstractOrmEntity.
Definition at line 33 of file Address.java.
References newtonERP.module.AbstractOrmEntity.getForeignKeyName(), and newtonERP.module.AbstractOrmEntity.getPrimaryKeyName().
The documentation for this class was generated from the following file:
src/modules/common/entityDefinitions/Address.java