Bee ERP: newtonERP.orm.associations.FlagPoolManager Class Reference
newtonERP.orm.associations.FlagPoolManager Class Reference
Cette classe gère les comportement d'association d'entités faites par le FlagPool.
Static Public Member Functions
static void applyFlagPoolChanges (AbstractOrmEntity sourceEntity, Iterable< FlagPool > flagPoolList, Hashtable< String, String > parameters)
static final void addFlagPool (AbstractOrmEntity sourceEntity, AbstractOrmEntity foreignEntityDefinition)
Detailed Description
Cette classe gère les comportement d'association d'entités faites par le FlagPool.
Author:
Guillaume
Definition at line 17 of file FlagPoolManager.java.
Member Function Documentation
static final void newtonERP.orm.associations.FlagPoolManager.addFlagPool (AbstractOrmEntity sourceEntity, AbstractOrmEntity foreignEntityDefinition) [static]
Parameters:
sourceEntity the source entity
foreignEntityDefinition entity of the foreign entity
Definition at line 101 of file FlagPoolManager.java.
References newtonERP.module.AbstractOrmEntity.getForeignKeyName(), newtonERP.module.AbstractOrmEntity.getNaturalKeyName(), and newtonERP.module.AbstractOrmEntity.getPrimaryKeyName().
static void newtonERP.orm.associations.FlagPoolManager.applyFlagPoolChanges (AbstractOrmEntity sourceEntity, Iterable< FlagPool > flagPoolList, Hashtable< String, String > parameters) [static]
Parameters:
sourceEntity the source entity
flagPoolList liste de FlagPool
parameters paramêtres (mêmes type que dans doAction
Definition at line 24 of file FlagPoolManager.java.
The documentation for this class was generated from the following file:
src/newtonERP/orm/associations/FlagPoolManager.java