Bee ERP: newtonERP.viewers.firstStep.FloorViewer Class Reference
newtonERP.viewers.firstStep.FloorViewer Class Reference
Représente un viewer de plancher.
Static Public Member Functions
static String getHtmlCode (FloorViewable entity)
Detailed Description
Représente un viewer de plancher.
Author:
Guillaume Lacasse
Definition at line 14 of file FloorViewer.java.
Member Function Documentation
static String newtonERP.viewers.firstStep.FloorViewer.getHtmlCode (FloorViewable entity) [static]
Parameters:
entity entité de plancher
Returns:
code HTML
Definition at line 28 of file FloorViewer.java.
References newtonERP.viewers.viewables.FloorViewable.getColumnCount(), newtonERP.viewers.viewables.FloorViewable.getRowCount(), newtonERP.viewers.viewables.FloorViewable.isCorridorAt(), and newtonERP.viewers.viewables.FloorViewable.tryGetZoneNameAt().
The documentation for this class was generated from the following file:
src/newtonERP/viewers/firstStep/FloorViewer.java