Bee ERP: newtonERP.viewers.viewerData.ListViewerData Class Reference
newtonERP.viewers.viewerData.ListViewerData Class Reference
Inherits newtonERP::viewers::viewerData::GridViewerData.
Public Member Functions
ListViewerData (AbstractOrmEntity dataType)
constructeur par defaut
Vector< AbstractOrmEntity > getEntity ()
GridCaseData[] getHeader ()
GridCaseData[][] getCases ()
void addEntity (AbstractOrmEntity entity)
AbstractOrmEntity getDataType ()
Iterator< AbstractOrmEntity > iterator ()
PageSelector getPageSelector ()
void setPageSelector (PageSelector pageSelector)
SearchBar getSearchBar ()
void setSearchBar (SearchBar searchBar)
Static Public Member Functions
static final int BuildOffset (Hashtable< String, String > parameters, int limit)
static final int BuildLimit (Hashtable< String, String > parameters, int defaultValue)
Detailed Description
Author:
Guillaume Lacasse, CloutierJo
Definition at line 18 of file ListViewerData.java.
Constructor & Destructor Documentation
newtonERP.viewers.viewerData.ListViewerData.ListViewerData (AbstractOrmEntity dataType)
constructeur par defaut
Parameters:
dataType type d'entity a etre liste
Definition at line 30 of file ListViewerData.java.
Member Function Documentation
void newtonERP.viewers.viewerData.ListViewerData.addEntity (AbstractOrmEntity entity)
Parameters:
entity the entity to add
Definition at line 156 of file ListViewerData.java.
Referenced by newtonERP.module.AbstractOrmEntity.getList().
static final int newtonERP.viewers.viewerData.ListViewerData.BuildLimit (Hashtable< String, String > parameters, int defaultValue) [static]
Parameters:
parameters parametres d'action GetList
defaultValue nombre d'item par page par default
Returns:
limite de selection de liste d'entité, -1 si aucun
Definition at line 198 of file ListViewerData.java.
static final int newtonERP.viewers.viewerData.ListViewerData.BuildOffset (Hashtable< String, String > parameters, int limit) [static]
Parameters:
parameters parametres d'action GetList
limit limite par page
Returns:
offset de selection de liste d'entité, -1 si aucun
Definition at line 180 of file ListViewerData.java.
GridCaseData [][] newtonERP.viewers.viewerData.ListViewerData.getCases ()
Returns:
the cases
Reimplemented from newtonERP.viewers.viewerData.GridViewerData.
Definition at line 79 of file ListViewerData.java.
References newtonERP.module.generalEntity.ListOfValue.getForeignEntityDefinition(), newtonERP.module.generalEntity.ListOfValue.getForeignValue(), newtonERP.module.AbstractOrmEntity.getNaturalKeyDescription(), newtonERP.module.AbstractOrmEntity.getPrimaryKeyName(), newtonERP.module.AbstractOrmEntity.getPrimaryKeyValue(), and newtonERP.viewers.viewerData.GridCaseData.setColored().
AbstractOrmEntity newtonERP.viewers.viewerData.ListViewerData.getDataType ()
Returns:
the dataType
Definition at line 164 of file ListViewerData.java.
Vector<AbstractOrmEntity> newtonERP.viewers.viewerData.ListViewerData.getEntity ()
Returns:
les entity
Definition at line 39 of file ListViewerData.java.
GridCaseData [] newtonERP.viewers.viewerData.ListViewerData.getHeader ()
Returns:
the header
Reimplemented from newtonERP.viewers.viewerData.GridViewerData.
Definition at line 44 of file ListViewerData.java.
References newtonERP.module.AbstractEntity.getFields(), newtonERP.module.AbstractOrmEntity.getGateWayList(), newtonERP.module.generalEntity.ListOfValue.getLabelName(), and newtonERP.module.AbstractEntity.tryMatchListOfValue().
PageSelector newtonERP.viewers.viewerData.ListViewerData.getPageSelector ()
Returns:
page selector
Definition at line 209 of file ListViewerData.java.
SearchBar newtonERP.viewers.viewerData.ListViewerData.getSearchBar ()
Returns:
modèle de barre de recherche
Definition at line 225 of file ListViewerData.java.
void newtonERP.viewers.viewerData.ListViewerData.setPageSelector (PageSelector pageSelector)
Parameters:
pageSelector page selector
Definition at line 217 of file ListViewerData.java.
Referenced by newtonERP.module.AbstractOrmEntity.getList().
void newtonERP.viewers.viewerData.ListViewerData.setSearchBar (SearchBar searchBar)
Parameters:
searchBar modèle de barre de recherche
Definition at line 233 of file ListViewerData.java.
Referenced by newtonERP.module.AbstractOrmEntity.getList().
The documentation for this class was generated from the following file:
src/newtonERP/viewers/viewerData/ListViewerData.java