Bee ERP: modules.userRightModule.actions.RightCheck Class Reference
modules.userRightModule.actions.RightCheck Class Reference
Action class that checks the right on an entity.
Inherits newtonERP::module::AbstractAction.
Public Member Functions
AbstractEntity doAction (AbstractEntity entity, Hashtable< String, String > parameters)
Abstract method that will be reused by all the actions.
Detailed Description
Action class that checks the right on an entity.
Author:
cloutierJo
Definition at line 18 of file RightCheck.java.
Member Function Documentation
AbstractEntity modules.userRightModule.actions.RightCheck.doAction (AbstractEntity entity, Hashtable< String, String > parameters) [virtual]
Abstract method that will be reused by all the actions.
Parameters:
entity entite a utiliser a l'intérieur du doAction
parameters list de parametre autre que l'entite
Returns:
l'entite resultante
Implements newtonERP.module.AbstractAction.
Definition at line 21 of file RightCheck.java.
References newtonERP.orm.associations.PluralAccessor.get(), modules.userRightModule.entityDefinitions.User.getGroupsEntity(), newtonERP.module.AbstractOrmEntity.getPluralAccessor(), and newtonERP.module.AbstractEntity.setData().
The documentation for this class was generated from the following file:
src/modules/userRightModule/actions/RightCheck.java