Bee ERP: newtonERP.viewers.firstStep.BaseViewer Class Reference
newtonERP.viewers.firstStep.BaseViewer Class Reference
permet l'affichage des BaseViewerData
Static Public Member Functions
static String getTopHtmlCode (BaseViewerData entity)
donne le code html des element de base du haut
static String getBottomHtmlCode (BaseViewerData entity)
donne le code html des element de base du bas
Detailed Description
permet l'affichage des BaseViewerData
Author:
CloutierJo
Definition at line 13 of file BaseViewer.java.
Member Function Documentation
static String newtonERP.viewers.firstStep.BaseViewer.getBottomHtmlCode (BaseViewerData entity) [static]
donne le code html des element de base du bas
Parameters:
entity l'entity cntenant ces information
Returns:
le code html
Definition at line 61 of file BaseViewer.java.
References newtonERP.viewers.viewerData.BaseViewerData.getGlobalActions().
static String newtonERP.viewers.firstStep.BaseViewer.getTopHtmlCode (BaseViewerData entity) [static]
donne le code html des element de base du haut
Parameters:
entity l'entity cntenant ces information
Returns:
le code html
Definition at line 21 of file BaseViewer.java.
References newtonERP.viewers.viewerData.BaseViewerData.getBackLink(), and newtonERP.viewers.viewerData.BaseViewerData.getTitle().
The documentation for this class was generated from the following file:
src/newtonERP/viewers/firstStep/BaseViewer.java