Bee ERP: newtonERP.orm.associations.GateWay Class Reference
newtonERP.orm.associations.GateWay Class Reference
Accesseur passant par un autre accesseur.
Public Member Functions
GateWay (AbstractOrmEntity gateWayEntity, AbstractOrmEntity externalEntity)
AbstractOrmEntity getGateWayEntity ()
AbstractOrmEntity getExternalEntity ()
boolean isColored ()
Detailed Description
Accesseur passant par un autre accesseur.
Author:
Guillaume Lacasse
Definition at line 9 of file GateWay.java.
Constructor & Destructor Documentation
newtonERP.orm.associations.GateWay.GateWay (AbstractOrmEntity gateWayEntity, AbstractOrmEntity externalEntity)
Parameters:
gateWayEntity entité de passerelle
externalEntity entité externe
Definition at line 18 of file GateWay.java.
Member Function Documentation
AbstractOrmEntity newtonERP.orm.associations.GateWay.getExternalEntity ()
Returns:
entité externe
Definition at line 36 of file GateWay.java.
Referenced by newtonERP.orm.associations.GateWayManager.getExternalEntity().
AbstractOrmEntity newtonERP.orm.associations.GateWay.getGateWayEntity ()
Returns:
entité de passerelle
Definition at line 28 of file GateWay.java.
Referenced by newtonERP.orm.associations.GateWayManager.getExternalEntity().
boolean newtonERP.orm.associations.GateWay.isColored ()
Returns:
whether the external entity's field should be in color
Definition at line 44 of file GateWay.java.
References newtonERP.module.AbstractEntity.getFields(), and newtonERP.module.AbstractOrmEntity.getForeignKeyName().
The documentation for this class was generated from the following file:
src/newtonERP/orm/associations/GateWay.java