Bee ERP: newtonERP.logging.Logger Class Reference
newtonERP.logging.Logger Class Reference
Public Types
enum State { DEBUG, INFO, WARNING, ERROR }
States the logger can have.
Static Public Member Functions
static void init ()
initialize the loging system if not already done
static void close ()
properly close all File writer
static void log (String message, State state)
Used to log a message, passing a message and the desired state.
static void debug (String message)
helper function to log a Debug message
static void info (String message)
helper function to log an Info message
static void warning (String message)
helper function to log a Warning message
static void error (String message)
helper function to log an Error message
Detailed Description
Author:
r3hallejo
Class used to log system messages into an external log for purposes of viewing errors, information messages, warnings and much more that has happen on a later time.
HOWTO : (Static class) Logger.log("MY MESSAGE GOES HERE", Log.State.STATE_OF_MESSAGE)
See the state enumeration for all the actual states available
For better results we might have to think a better way of implementing the logging in all the project so we wont have dozens of logger objects accessing the log file causing multiple write lines at the same time
Definition at line 26 of file Logger.java.
Member Enumeration Documentation
enum newtonERP::logging::Logger::State
States the logger can have.
Enumerator:
DEBUG
An debug message.
INFO
An information message.
WARNING
A warning message.
ERROR
An error message.
Definition at line 37 of file Logger.java.
Member Function Documentation
static void newtonERP.logging.Logger.debug (String message) [static]
helper function to log a Debug message
Parameters:
message the message
Definition at line 154 of file Logger.java.
References newtonERP.logging.Logger.log().
static void newtonERP.logging.Logger.error (String message) [static]
helper function to log an Error message
Parameters:
message the message
Definition at line 181 of file Logger.java.
References newtonERP.logging.Logger.log().
static void newtonERP.logging.Logger.info (String message) [static]
helper function to log an Info message
Parameters:
message the message
Definition at line 163 of file Logger.java.
References newtonERP.logging.Logger.log().
static void newtonERP.logging.Logger.log (String message, State state) [static]
Used to log a message, passing a message and the desired state.
Parameters:
message the message
state the state
Definition at line 105 of file Logger.java.
References newtonERP.logging.Logger.init().
Referenced by newtonERP.logging.Logger.debug(), newtonERP.logging.Logger.error(), newtonERP.logging.Logger.info(), and newtonERP.logging.Logger.warning().
static void newtonERP.logging.Logger.warning (String message) [static]
helper function to log a Warning message
Parameters:
message the message
Definition at line 172 of file Logger.java.
References newtonERP.logging.Logger.log().
The documentation for this class was generated from the following file:
src/newtonERP/logging/Logger.java