Bee ERP: modules.taskModule.entityDefinitions.SearchCriteriaOperator Class Reference
modules.taskModule.entityDefinitions.SearchCriteriaOperator Class Reference
Opérateur de critère de recherche.
Inherits newtonERP::module::AbstractOrmEntity.
Public Member Functions
Fields initFields ()
initialise les champ de l'entity, doit etre overider si l'entity contient des champs, sinon initialise une liste de champ vide
AbstractEntity deleteUI (Hashtable< String, String > parameters)
BaseAction Delete.
BaseViewerData editUI (Hashtable< String, String > parameters)
BaseAction Edit.
final ListViewerData getList (Hashtable< String, String > parameters)
String getOperator ()
Detailed Description
Opérateur de critère de recherche.
Author:
Guillaume Lacasse
Definition at line 19 of file SearchCriteriaOperator.java.
Member Function Documentation
AbstractEntity modules.taskModule.entityDefinitions.SearchCriteriaOperator.deleteUI (Hashtable< String, String > parameters)
BaseAction Delete.
Parameters:
parameters parametre suplementaire
Returns:
todo: qu'Est-ce que l'on devrai retourné en general?
Reimplemented from newtonERP.module.AbstractOrmEntity.
Definition at line 39 of file SearchCriteriaOperator.java.
BaseViewerData modules.taskModule.entityDefinitions.SearchCriteriaOperator.editUI (Hashtable< String, String > parameters)
BaseAction Edit.
Parameters:
parameters parametre suplementaire
Returns:
todo: qu'Est-ce que l'on devrai retourné en general?
Reimplemented from newtonERP.module.AbstractOrmEntity.
Definition at line 51 of file SearchCriteriaOperator.java.
final ListViewerData modules.taskModule.entityDefinitions.SearchCriteriaOperator.getList (Hashtable< String, String > parameters)
Parameters:
parameters parametres de sélection (à venir)
Returns:
une liste d'entité de ce type
Reimplemented from newtonERP.module.AbstractOrmEntity.
Definition at line 63 of file SearchCriteriaOperator.java.
String modules.taskModule.entityDefinitions.SearchCriteriaOperator.getOperator ()
Returns:
opérateur en string
Definition at line 73 of file SearchCriteriaOperator.java.
References newtonERP.module.AbstractEntity.getDataString().
Referenced by modules.taskModule.entityDefinitions.SearchCriteria.getOperator().
Fields modules.taskModule.entityDefinitions.SearchCriteriaOperator.initFields () [virtual]
initialise les champ de l'entity, doit etre overider si l'entity contient des champs, sinon initialise une liste de champ vide
Returns:
le Fields initialiser
Implements newtonERP.module.AbstractOrmEntity.
Definition at line 30 of file SearchCriteriaOperator.java.
References newtonERP.module.AbstractOrmEntity.getPrimaryKeyName().
The documentation for this class was generated from the following file:
src/modules/taskModule/entityDefinitions/SearchCriteriaOperator.java