Bee ERP: modules.taskModule.actions.AddFieldToOrm Class Reference
modules.taskModule.actions.AddFieldToOrm Class Reference
Ajoute un field à l'Orm.
Inherits newtonERP::module::AbstractAction.
Public Member Functions
BaseViewerData doAction (AbstractEntity sourceFieldEntity, Hashtable< String, String > parameters)
Abstract method that will be reused by all the actions.
Detailed Description
Ajoute un field à l'Orm.
Author:
Guillaume
Definition at line 20 of file AddFieldToOrm.java.
Member Function Documentation
BaseViewerData modules.taskModule.actions.AddFieldToOrm.doAction (AbstractEntity entity, Hashtable< String, String > parameters) [virtual]
Abstract method that will be reused by all the actions.
Parameters:
entity entite a utiliser a l'intérieur du doAction
parameters list de parametre autre que l'entite
Returns:
l'entite resultante
Implements newtonERP.module.AbstractAction.
Definition at line 30 of file AddFieldToOrm.java.
References newtonERP.viewers.viewerData.BaseViewerData.addNormalMessage(), newtonERP.module.AbstractOrmEntity.editUI(), modules.taskModule.entityDefinitions.EntityEntity.getEntityDefinition(), modules.taskModule.entityDefinitions.FieldEntity.getFieldInstance(), and newtonERP.module.AbstractEntity.getSystemName().
The documentation for this class was generated from the following file:
src/modules/taskModule/actions/AddFieldToOrm.java