Bee ERP: newtonERP.viewers.viewerData.BaseViewerData Class Reference
newtonERP.viewers.viewerData.BaseViewerData Class Reference
viewer servant a standardisé nos viewer
Inherits newtonERP::module::AbstractEntity.
Inherited by newtonERP.viewers.viewerData.GridViewerData, newtonERP.viewers.viewerData.ImgViewerData, and newtonERP.viewers.viewerData.PromptViewerData.
Public Member Functions
BaseViewerData ()
constructeur vide
void setTitle (String title)
String getTitle ()
void setGlobalActions (Vector< ActionLink > globalActions)
Vector< ActionLink > getGlobalActions ()
void addGlobalActions (ActionLink globalAction)
void removeGlobalActions (String globalActionName)
Vector< String > getAlertMessageList ()
void setAlertMessageList (Vector< String > alertMessageList)
final void addAlertMessage (String message)
Vector< String > getNormalMessageList ()
void setNormalMessageList (Vector< String > normalMessageList)
void addNormalMessage (String message)
ActionLink getBackLink ()
void setBackLink (ActionLink backLink)
void addComplementaryInfoLine (String complementaryInfoLine)
Vector< String > getComplementaryInfoLineList ()
Detailed Description
viewer servant a standardisé nos viewer
Author:
CloutierJo
Definition at line 14 of file BaseViewerData.java.
Member Function Documentation
final void newtonERP.viewers.viewerData.BaseViewerData.addAlertMessage (String message)
Parameters:
message message à ajouter
Definition at line 104 of file BaseViewerData.java.
Referenced by modules.taskModule.entityDefinitions.FieldEntity.deleteUI(), modules.userRightModule.actions.Login.doAction(), modules.taskModule.actions.GenerateSourceCode.doAction(), modules.taskModule.actions.GenerateEntityCode.doAction(), modules.taskModule.actions.GenerateActionCode.doAction(), and newtonERP.module.AbstractOrmEntity.editUI().
void newtonERP.viewers.viewerData.BaseViewerData.addComplementaryInfoLine (String complementaryInfoLine)
Parameters:
complementaryInfoLine ligne d'information complémentaire à ajouter
Definition at line 153 of file BaseViewerData.java.
References newtonERP.viewers.viewerData.BaseViewerData.getComplementaryInfoLineList().
void newtonERP.viewers.viewerData.BaseViewerData.addGlobalActions (ActionLink globalAction)
Parameters:
globalAction the globalActions to add
Definition at line 66 of file BaseViewerData.java.
Referenced by newtonERP.module.AbstractOrmEntity.getList().
void newtonERP.viewers.viewerData.BaseViewerData.addNormalMessage (String message)
Parameters:
message nouveau message normal
Definition at line 129 of file BaseViewerData.java.
Referenced by modules.taskModule.actions.GenerateSourceCode.doAction(), modules.taskModule.actions.GenerateEntityCode.doAction(), modules.taskModule.actions.AddFieldToOrm.doAction(), and newtonERP.module.AbstractOrmEntity.editUI().
Vector<String> newtonERP.viewers.viewerData.BaseViewerData.getAlertMessageList ()
Returns:
the alertMessageList
Definition at line 88 of file BaseViewerData.java.
ActionLink newtonERP.viewers.viewerData.BaseViewerData.getBackLink ()
Returns:
the backLink
Definition at line 137 of file BaseViewerData.java.
Referenced by newtonERP.viewers.firstStep.BaseViewer.getTopHtmlCode().
Vector<String> newtonERP.viewers.viewerData.BaseViewerData.getComplementaryInfoLineList ()
Returns:
liste des lignes d'information complémentaire
Definition at line 162 of file BaseViewerData.java.
Referenced by newtonERP.viewers.viewerData.BaseViewerData.addComplementaryInfoLine(), and newtonERP.viewers.firstStep.PromptViewer.getHtmlCode().
Vector<ActionLink> newtonERP.viewers.viewerData.BaseViewerData.getGlobalActions ()
Returns:
the globalActions
Definition at line 58 of file BaseViewerData.java.
Referenced by newtonERP.viewers.firstStep.BaseViewer.getBottomHtmlCode().
Vector<String> newtonERP.viewers.viewerData.BaseViewerData.getNormalMessageList ()
Returns:
the normalMessageList
Definition at line 113 of file BaseViewerData.java.
String newtonERP.viewers.viewerData.BaseViewerData.getTitle ()
Returns:
the title
Definition at line 42 of file BaseViewerData.java.
Referenced by newtonERP.viewers.firstStep.BaseViewer.getTopHtmlCode(), and newtonERP.viewers.viewerData.PromptViewerData.setData().
void newtonERP.viewers.viewerData.BaseViewerData.removeGlobalActions (String globalActionName)
Parameters:
globalActionName the globalActionName to remove
Definition at line 74 of file BaseViewerData.java.
References newtonERP.common.ActionLink.getName().
Referenced by modules.taskModule.entityDefinitions.FieldEntity.getList(), modules.taskModule.entityDefinitions.EntityEntity.getList(), and modules.taskModule.entityDefinitions.ActionEntity.getList().
void newtonERP.viewers.viewerData.BaseViewerData.setAlertMessageList (Vector< String > alertMessageList)
Parameters:
alertMessageList the alertMessageList to set
Definition at line 96 of file BaseViewerData.java.
void newtonERP.viewers.viewerData.BaseViewerData.setBackLink (ActionLink backLink)
Parameters:
backLink the backLink to set
Definition at line 145 of file BaseViewerData.java.
Referenced by newtonERP.module.AbstractOrmEntity.editUI().
void newtonERP.viewers.viewerData.BaseViewerData.setGlobalActions (Vector< ActionLink > globalActions)
Parameters:
globalActions the globalActions to set
Definition at line 50 of file BaseViewerData.java.
void newtonERP.viewers.viewerData.BaseViewerData.setNormalMessageList (Vector< String > normalMessageList)
Parameters:
normalMessageList the normalMessageList to set
Definition at line 121 of file BaseViewerData.java.
void newtonERP.viewers.viewerData.BaseViewerData.setTitle (String title)
Parameters:
title the title to set
Definition at line 34 of file BaseViewerData.java.
Referenced by modules.userRightModule.actions.Login.doAction(), modules.taskModule.actions.DbGraph.doAction(), newtonERP.module.AbstractOrmEntity.editUI(), newtonERP.module.AbstractOrmEntity.getList(), and newtonERP.viewers.viewerData.PromptViewerData.setData().
The documentation for this class was generated from the following file:
src/newtonERP/viewers/viewerData/BaseViewerData.java