Bee ERP: newtonERP.viewers.secondStep.ScrollListViewer Class Reference
newtonERP.viewers.secondStep.ScrollListViewer Class Reference
Sert à afficher des listes de lien et de texte en HTML avec une scrollbar.
Static Public Member Functions
static String getHtmlContent (ScrollListViewable entity)
Detailed Description
Sert à afficher des listes de lien et de texte en HTML avec une scrollbar.
Author:
Guillaume
Definition at line 12 of file ScrollListViewer.java.
Member Function Documentation
static String newtonERP.viewers.secondStep.ScrollListViewer.getHtmlContent (ScrollListViewable entity) [static]
Parameters:
entity liste à afficher
Returns:
code HTML
Definition at line 18 of file ScrollListViewer.java.
References newtonERP.viewers.viewables.ScrollListViewable.getActionLinkList(), newtonERP.viewers.viewables.ScrollListViewable.getLinkGroupList(), newtonERP.viewers.viewables.ScrollListViewable.getLinkList(), newtonERP.viewers.viewables.ScrollListViewable.getTitle(), and newtonERP.viewers.viewables.ScrollListViewable.getTitleUrl().
The documentation for this class was generated from the following file:
src/newtonERP/viewers/secondStep/ScrollListViewer.java