Bee ERP: newtonERP.orm.associations.AccessorManager Class Reference
newtonERP.orm.associations.AccessorManager Class Reference
Facade vers FlagPoolManager et ListOfValueManager.
Static Public Member Functions
static void addAccessor (AbstractOrmEntity sourceEntity, AbstractOrmEntity foreignEntityDefinition)
Essaie d'ajouter un accessor quelconque (1 à plusieur, plusiseurs à plusieurs selon la disponibilité des tables).
static final void addFlagPool (AbstractOrmEntity sourceEntity, AbstractOrmEntity foreignEntityDefinition)
static final void addListOfValue (AbstractOrmEntity entity, AbstractOrmEntity foreignEntity)
static final TreeMap< String,
PluralAccessor > getPluralAccessorList (AbstractOrmEntity abstractOrmEntity)
static final TreeMap< String,
AbstractOrmEntity > getSingleAccessorList (AbstractOrmEntity abstractOrmEntity)
static AbstractOrmEntity getSingleAccessor (AbstractOrmEntity abstractOrmEntity, String accessorName)
static void addGateWay (AbstractOrmEntity sourceEntity, AbstractOrmEntity gateWayEntity, AbstractOrmEntity externalEntity)
Detailed Description
Facade vers FlagPoolManager et ListOfValueManager.
Author:
Guillaume Lacasse
Definition at line 12 of file AccessorManager.java.
Member Function Documentation
static void newtonERP.orm.associations.AccessorManager.addAccessor (AbstractOrmEntity sourceEntity, AbstractOrmEntity foreignEntityDefinition) [static]
Essaie d'ajouter un accessor quelconque (1 à plusieur, plusiseurs à plusieurs selon la disponibilité des tables).
Parameters:
sourceEntity the source entity
foreignEntityDefinition entity of the foreign entity
Definition at line 21 of file AccessorManager.java.
References newtonERP.module.AbstractOrmEntity.getAccessorNameList(), and newtonERP.module.AbstractEntity.getSystemName().
static final void newtonERP.orm.associations.AccessorManager.addFlagPool (AbstractOrmEntity sourceEntity, AbstractOrmEntity foreignEntityDefinition) [static]
Parameters:
sourceEntity the source entity
foreignEntityDefinition entity of the foreign entity
Definition at line 52 of file AccessorManager.java.
static void newtonERP.orm.associations.AccessorManager.addGateWay (AbstractOrmEntity sourceEntity, AbstractOrmEntity gateWayEntity, AbstractOrmEntity externalEntity) [static]
Parameters:
sourceEntity entié de source
gateWayEntity entité de passerelle
externalEntity entié externe
Definition at line 106 of file AccessorManager.java.
static final void newtonERP.orm.associations.AccessorManager.addListOfValue (AbstractOrmEntity entity, AbstractOrmEntity foreignEntity) [static]
Parameters:
entity Entité source
foreignEntity Entité cible
Definition at line 62 of file AccessorManager.java.
static final TreeMap<String, PluralAccessor> newtonERP.orm.associations.AccessorManager.getPluralAccessorList (AbstractOrmEntity abstractOrmEntity) [static]
Parameters:
abstractOrmEntity entité source
Returns:
liste des accessors plusieurs à plusieurs pour l'entité source
Definition at line 72 of file AccessorManager.java.
static AbstractOrmEntity newtonERP.orm.associations.AccessorManager.getSingleAccessor (AbstractOrmEntity abstractOrmEntity, String accessorName) [static]
Parameters:
abstractOrmEntity entité
accessorName nom de l'accessor
Returns:
accessor
Definition at line 93 of file AccessorManager.java.
References newtonERP.module.AbstractOrmEntity.getSingleAccessor().
static final TreeMap<String, AbstractOrmEntity> newtonERP.orm.associations.AccessorManager.getSingleAccessorList (AbstractOrmEntity abstractOrmEntity) [static]
Parameters:
abstractOrmEntity entité source
Returns:
liste des accessors 1 à 1 et plusieurs à 1 pour l'entité source
Definition at line 82 of file AccessorManager.java.
The documentation for this class was generated from the following file:
src/newtonERP/orm/associations/AccessorManager.java