Bee ERP: newtonERP.orm.sgbd.sqlite.SgbdSqlite Class Reference
newtonERP.orm.sgbd.sqlite.SgbdSqlite Class Reference
Class who's role is only for executing the statements that has been sent from the orm.
Inherits newtonERP::orm::sgbd::AbstractSgbd.
Public Member Functions
ResultSet execute (String request, OrmActions action)
Method that executes the sql query passed in paramter plus de action from the OrmAction.
void disconnect ()
Method used to disconnect from the database.
void connect ()
Method used to initialize the connection to the databse.
ResultSet addColumnToTable (AbstractOrmEntity entity, Field<?> field)
Alter table.
ResultSet select (AbstractOrmEntity searchEntity, Vector< String > searchCriteriasParam)
Use only for complex queries.
ResultSet select (Vector< AbstractOrmEntity > searchEntities)
Uses the new where builder.
int insert (AbstractOrmEntity newEntity)
Method used to insert an entity in the database based into the entity passed in parameter.
void delete (AbstractOrmEntity searchEntity, Vector< String > searchCriterias)
Method used to delete an entity from the database.
void delete (Vector< AbstractOrmEntity > searchEntities)
Uses the new where builder.
void update (AbstractOrmEntity entityContainingChanges, Vector< String > searchCriterias)
Method used to update / change an entity.
void update (Vector< AbstractOrmEntity > searchEntities, AbstractOrmEntity entityContainingChanges)
Uses the new where builder.
boolean isEntityExists (String entitySystemName)
void createIndex (String entityName, String fieldName)
Sert à ajouter un index dans la table SQL de l'entité pour un field en particulier.
void createTableForEntity (AbstractOrmEntity entity)
Créer une table pour un type d'entité.
void updateUnique (AbstractOrmEntity searchEntity, AbstractOrmEntity entityContainingChanges)
Uses the new where builder.
ResultSet select (AbstractOrmEntity searchEntity, Vector< String > searchCriteriasParam, int limit, int offset, String orderBy)
Use only for complex queries.
int count (AbstractOrmEntity searchEntity, Vector< String > searchParameterList)
void doBackup ()
Fait un backup de la DB.
long getLatestBackupTime ()
Detailed Description
Class who's role is only for executing the statements that has been sent from the orm.
Author:
r3lacasgu, r3hallejo
Definition at line 33 of file SgbdSqlite.java.
Member Function Documentation
ResultSet newtonERP.orm.sgbd.sqlite.SgbdSqlite.addColumnToTable (AbstractOrmEntity entity, Field<?> field) [virtual]
Alter table.
Parameters:
entity the entity containing the new field
field the field to add
Returns:
?
Implements newtonERP.orm.sgbd.AbstractSgbd.
Definition at line 98 of file SgbdSqlite.java.
References newtonERP.orm.sgbd.sqlite.SgbdSqlite.execute(), and newtonERP.module.AbstractEntity.getSystemName().
void newtonERP.orm.sgbd.sqlite.SgbdSqlite.connect () [virtual]
Method used to initialize the connection to the databse.
Implements newtonERP.orm.sgbd.AbstractSgbd.
Definition at line 83 of file SgbdSqlite.java.
int newtonERP.orm.sgbd.sqlite.SgbdSqlite.count (AbstractOrmEntity searchEntity, Vector< String > searchParameterList) [virtual]
Parameters:
searchEntity entité de recherche
searchParameterList paramêtres de recherche
Returns:
nombre d'occurence du type de l'entité de recherche
Implements newtonERP.orm.sgbd.AbstractSgbd.
Definition at line 554 of file SgbdSqlite.java.
References newtonERP.orm.sgbd.sqlite.SgbdSqlite.execute(), newtonERP.module.AbstractOrmEntity.getPrimaryKeyName(), and newtonERP.module.AbstractEntity.getSystemName().
void newtonERP.orm.sgbd.sqlite.SgbdSqlite.createIndex (String entityName, String fieldName) [virtual]
Sert à ajouter un index dans la table SQL de l'entité pour un field en particulier.
Parameters:
entityName nom de l'entité
fieldName nom du field
Implements newtonERP.orm.sgbd.AbstractSgbd.
Definition at line 434 of file SgbdSqlite.java.
References newtonERP.orm.sgbd.sqlite.SgbdSqlite.execute().
void newtonERP.orm.sgbd.sqlite.SgbdSqlite.createTableForEntity (AbstractOrmEntity entity) [virtual]
Créer une table pour un type d'entité.
Parameters:
entity entité
Implements newtonERP.orm.sgbd.AbstractSgbd.
Definition at line 448 of file SgbdSqlite.java.
References newtonERP.orm.sgbd.sqlite.SgbdSqlite.execute(), and newtonERP.module.AbstractEntity.getSystemName().
void newtonERP.orm.sgbd.sqlite.SgbdSqlite.delete (AbstractOrmEntity searchEntity, Vector< String > searchCriterias) [virtual]
Method used to delete an entity from the database.
Parameters:
searchEntity the entity to be researched
searchCriterias the search criterias for the where clause
Implements newtonERP.orm.sgbd.AbstractSgbd.
Definition at line 354 of file SgbdSqlite.java.
References newtonERP.orm.sgbd.sqlite.SgbdSqlite.execute().
void newtonERP.orm.sgbd.sqlite.SgbdSqlite.delete (Vector< AbstractOrmEntity > searchEntities) [virtual]
Uses the new where builder.
Method used to delete an entity from the database
Parameters:
searchEntities the entities from which we will build our where clause
Implements newtonERP.orm.sgbd.AbstractSgbd.
Definition at line 368 of file SgbdSqlite.java.
References newtonERP.orm.sgbd.sqlite.SgbdSqlite.execute().
void newtonERP.orm.sgbd.sqlite.SgbdSqlite.disconnect () [virtual]
Method used to disconnect from the database.
Implements newtonERP.orm.sgbd.AbstractSgbd.
Definition at line 69 of file SgbdSqlite.java.
ResultSet newtonERP.orm.sgbd.sqlite.SgbdSqlite.execute (String request, OrmActions action) [virtual]
Method that executes the sql query passed in paramter plus de action from the OrmAction.
Parameters:
request l'action a effectue
action the OrmActions that will be done
Returns:
le resultat sous forme d'un result set
Implements newtonERP.orm.sgbd.AbstractSgbd.
Definition at line 44 of file SgbdSqlite.java.
Referenced by newtonERP.orm.sgbd.sqlite.SgbdSqlite.addColumnToTable(), newtonERP.orm.sgbd.sqlite.SgbdSqlite.count(), newtonERP.orm.sgbd.sqlite.SgbdSqlite.createIndex(), newtonERP.orm.sgbd.sqlite.SgbdSqlite.createTableForEntity(), newtonERP.orm.sgbd.sqlite.SgbdSqlite.delete(), newtonERP.orm.sgbd.sqlite.SgbdSqlite.insert(), newtonERP.orm.sgbd.sqlite.SgbdSqlite.isEntityExists(), newtonERP.orm.sgbd.sqlite.SgbdSqlite.select(), newtonERP.orm.sgbd.sqlite.SgbdSqlite.update(), and newtonERP.orm.sgbd.sqlite.SgbdSqlite.updateUnique().
long newtonERP.orm.sgbd.sqlite.SgbdSqlite.getLatestBackupTime () [virtual]
Returns:
timestamp en ms où le dernier backup à été fait
Implements newtonERP.orm.sgbd.AbstractSgbd.
Definition at line 595 of file SgbdSqlite.java.
References newtonERP.orm.sgbd.sqlite.SgbdSqliteBackupManager.getLatestBackupTime().
int newtonERP.orm.sgbd.sqlite.SgbdSqlite.insert (AbstractOrmEntity newEntity) [virtual]
Method used to insert an entity in the database based into the entity passed in parameter.
Parameters:
newEntity the entity to add
Returns:
le id de clé primaire ajoutée
Implements newtonERP.orm.sgbd.AbstractSgbd.
Definition at line 291 of file SgbdSqlite.java.
References newtonERP.orm.sgbd.sqlite.SgbdSqlite.execute(), newtonERP.module.AbstractEntity.getFields(), newtonERP.module.AbstractEntity.getSystemName(), and newtonERP.orm.field.Fields.iterator().
boolean newtonERP.orm.sgbd.sqlite.SgbdSqlite.isEntityExists (String entitySystemName) [virtual]
Parameters:
entitySystemName nom système d'une entité
Returns:
true si l'entité a une table dans la base de donnée, sinon false
Implements newtonERP.orm.sgbd.AbstractSgbd.
Definition at line 415 of file SgbdSqlite.java.
References newtonERP.orm.sgbd.sqlite.SgbdSqlite.execute().
ResultSet newtonERP.orm.sgbd.sqlite.SgbdSqlite.select (Vector< AbstractOrmEntity > searchEntities) [virtual]
Uses the new where builder.
Method used to do search queries done from the views to the databse. The search criterias that has been passed in parameter are a list of string that has been generated by the view modules todo: correct doc
Parameters:
searchEntities the entities from which we will perform the search
Returns:
the entities
Implements newtonERP.orm.sgbd.AbstractSgbd.
Definition at line 274 of file SgbdSqlite.java.
References newtonERP.orm.sgbd.sqlite.SgbdSqlite.execute().
ResultSet newtonERP.orm.sgbd.sqlite.SgbdSqlite.select (AbstractOrmEntity searchEntity, Vector< String > searchCriteriasParam) [virtual]
Use only for complex queries.
Use the select that takes only a vector of entities instead
Method used to do search queries done from the views to the databse. The search criterias that has been passed in parameter are a list of string that has been generated by the view modules
Parameters:
searchEntity the entity that has to be researched
searchCriteriasParam the search criterias formatted into strings
Returns:
a vector of ormizable entities
Implements newtonERP.orm.sgbd.AbstractSgbd.
Definition at line 126 of file SgbdSqlite.java.
References newtonERP.orm.sgbd.sqlite.SgbdSqlite.execute(), and newtonERP.module.AbstractEntity.getSystemName().
ResultSet newtonERP.orm.sgbd.sqlite.SgbdSqlite.select (AbstractOrmEntity searchEntity, Vector< String > searchCriteriasParam, int limit, int offset, String orderBy) [virtual]
Use only for complex queries.
Use the select that takes only a vector of entities instead
Method used to do search queries done from the views to the databse. The search criterias that has been passed in parameter are a list of string that has been generated by the view modules
Parameters:
searchEntity the entity that has to be researched
searchCriteriasParam the search criterias formatted into strings
limit limite de résultat
offset offset du début des résultats
orderBy ordre facultatif
Returns:
a vector of ormizable entities
Implements newtonERP.orm.sgbd.AbstractSgbd.
Definition at line 519 of file SgbdSqlite.java.
References newtonERP.orm.sgbd.sqlite.SgbdSqlite.execute(), and newtonERP.module.AbstractEntity.getSystemName().
void newtonERP.orm.sgbd.sqlite.SgbdSqlite.update (Vector< AbstractOrmEntity > searchEntities, AbstractOrmEntity entityContainingChanges) [virtual]
Uses the new where builder.
Method used to update / change an entity
Parameters:
searchEntities the entities from which we will build our where clause
entityContainingChanges the changes to apply
Implements newtonERP.orm.sgbd.AbstractSgbd.
Definition at line 399 of file SgbdSqlite.java.
References newtonERP.orm.sgbd.sqlite.SgbdSqlite.execute(), newtonERP.module.AbstractEntity.getFields(), and newtonERP.module.AbstractEntity.getSystemName().
void newtonERP.orm.sgbd.sqlite.SgbdSqlite.update (AbstractOrmEntity entityContainingChanges, Vector< String > searchCriterias) [virtual]
Method used to update / change an entity.
Parameters:
entityContainingChanges the entity that has been changed and will be in the orm
searchCriterias the criterias used by the update
Implements newtonERP.orm.sgbd.AbstractSgbd.
Definition at line 383 of file SgbdSqlite.java.
References newtonERP.orm.sgbd.sqlite.SgbdSqlite.execute(), newtonERP.module.AbstractEntity.getFields(), and newtonERP.module.AbstractEntity.getSystemName().
void newtonERP.orm.sgbd.sqlite.SgbdSqlite.updateUnique (AbstractOrmEntity searchEntity, AbstractOrmEntity entityContainingChanges) [virtual]
Uses the new where builder.
Method used to update / change an entity
Parameters:
searchEntity the entities from which we will build our where clause
entityContainingChanges the changes to apply
Implements newtonERP.orm.sgbd.AbstractSgbd.
Definition at line 502 of file SgbdSqlite.java.
References newtonERP.orm.sgbd.sqlite.SgbdSqlite.execute(), newtonERP.module.AbstractEntity.getFields(), and newtonERP.module.AbstractEntity.getSystemName().
The documentation for this class was generated from the following file:
src/newtonERP/orm/sgbd/sqlite/SgbdSqlite.java