Bee ERP: modules.taskModule.entityDefinitions.Specification Class Reference
modules.taskModule.entityDefinitions.Specification Class Reference
Spécification d'une tâche.
Inherits newtonERP::module::AbstractOrmEntity.
Public Member Functions
Fields initFields ()
initialise les champ de l'entity, doit etre overider si l'entity contient des champs, sinon initialise une liste de champ vide
boolean isSatisfied (Hashtable< String, String > entityParameters, boolean isStraightSearch)
Detailed Description
Spécification d'une tâche.
Author:
Guillaume Lacasse
Definition at line 19 of file Specification.java.
Member Function Documentation
Fields modules.taskModule.entityDefinitions.Specification.initFields () [virtual]
initialise les champ de l'entity, doit etre overider si l'entity contient des champs, sinon initialise une liste de champ vide
Returns:
le Fields initialiser
Implements newtonERP.module.AbstractOrmEntity.
Definition at line 31 of file Specification.java.
References newtonERP.module.AbstractOrmEntity.getForeignKeyName(), and newtonERP.module.AbstractOrmEntity.getPrimaryKeyName().
boolean modules.taskModule.entityDefinitions.Specification.isSatisfied (Hashtable< String, String > entityParameters, boolean isStraightSearch)
Parameters:
entityParameters paramètres de l'entité
isStraightSearch si c'est une recherche directe
Returns:
true si la spécification est satisfaite
Definition at line 47 of file Specification.java.
References newtonERP.module.AbstractOrmEntity.getPrimaryKeyName(), and newtonERP.module.AbstractEntity.setData().
Referenced by modules.taskModule.entityDefinitions.TaskEntity.isSatisfied().
The documentation for this class was generated from the following file:
src/modules/taskModule/entityDefinitions/Specification.java