Bee ERP: newtonERP.module.Module Class Reference
newtonERP.module.Module Class Reference
Abstract class representing an abstract module.
Inherited by modules.common.Common, modules.taskModule.TaskModule, and modules.userRightModule.UserRightModule.
Public Member Functions
Module ()
constructeur par default
String getDefaultAction ()
void initAction (String path)
initialise la liste d'action du module
void initEntityDefinition (String path)
initialise la liste de definition d'entite du module
final Hashtable< String,
AbstractOrmEntity > getEntityDefinitionList ()
final Hashtable< String,
AbstractAction > getActionList ()
final AbstractOrmEntity getEntityDefinition (String entityDefinitionName)
final AbstractAction getAction (String actionName)
void initDB ()
permet d'initialiser la base de donne lors de l'installation du module, ne doit pas prendre en compte la creation des table
final AbstractEntity doAction (String actionName, Hashtable< String, String > parameters)
permet de faire une action
final AbstractEntity doAction (String actionName, String entityName, Hashtable< String, String > parameters)
permet de faire un action standart sur une entité
final NaturalMap< String,
AbstractAction > getGlobalActionMenu ()
final void addGlobalActionMenuItem (String name, AbstractAction action)
void addGlobalActionButton (ActionLink actionLink)
Vector< ActionLink > getGlobalActionButtonList ()
String getDefaultEntity ()
final String getVisibleName ()
final void setVisibleName (String visibleName)
boolean equals (Object obj)
String getSystemName ()
NaturalMap< String,
AbstractAction > getGlobalActionMenuOrReturnDefaultBehavior ()
boolean isVisible ()
void setVisible (boolean visible)
Static Public Member Functions
static void resetCache ()
reset les cache de module
Protected Member Functions
final void setDefaultAction (AbstractAction action)
Protected Attributes
Hashtable< String,
AbstractOrmEntity > entityDefinitionList
Hashtable< String, AbstractAction > actionList
Detailed Description
Abstract class representing an abstract module.
Author:
Pascal Lemay
Definition at line 23 of file Module.java.
Constructor & Destructor Documentation
newtonERP.module.Module.Module ()
constructeur par default
Definition at line 50 of file Module.java.
Member Function Documentation
void newtonERP.module.Module.addGlobalActionButton (ActionLink actionLink)
Parameters:
actionLink bouton à ajouter
Definition at line 373 of file Module.java.
References newtonERP.module.Module.getGlobalActionButtonList().
final void newtonERP.module.Module.addGlobalActionMenuItem (String name, AbstractAction action)
Parameters:
name the action name
action the action
Definition at line 365 of file Module.java.
References newtonERP.module.Module.getGlobalActionMenu().
Referenced by modules.common.Common.Common(), and modules.userRightModule.UserRightModule.UserRightModule().
final AbstractEntity newtonERP.module.Module.doAction (String actionName, String entityName, Hashtable< String, String > parameters)
permet de faire un action standart sur une entité
Parameters:
actionName Nom de l'action que l'utilisateur veut faire
entityName Nom de l'entity contenant l'action
moduleGetterName Nom du module getter permetant d'obtenir l'entité produite par le module (cette entité servira de paramêtre à l'action
parameters Paramètres de l'action devant être accomplie, exemple, contenu d'un email
Returns:
Entité viewable pour l'output du résultat
Definition at line 320 of file Module.java.
References newtonERP.module.AbstractOrmEntity.deleteUI(), newtonERP.module.AbstractOrmEntity.editUI(), newtonERP.module.Module.getEntityDefinition(), newtonERP.module.AbstractEntity.getFields(), newtonERP.module.AbstractOrmEntity.getList(), newtonERP.module.AbstractOrmEntity.newUI(), and newtonERP.orm.field.Fields.setFromHashTable().
final AbstractEntity newtonERP.module.Module.doAction (String actionName, Hashtable< String, String > parameters)
permet de faire une action
Parameters:
actionName Nom de l'action que l'utilisateur veut faire
moduleGetterName Nom du module getter permetant d'obtenir l'entité produite par le module (cette entité servira de paramêtre à l'action
parameters Paramètres de l'action devant être accomplie, exemple, contenu d'un email
Returns:
Entité viewable pour l'output du résultat
Definition at line 301 of file Module.java.
References newtonERP.module.Module.getAction(), and newtonERP.module.AbstractAction.perform().
Referenced by newtonERP.serveur.CommandRouteur.routeCommand().
final AbstractAction newtonERP.module.Module.getAction (String actionName)
Parameters:
actionName nom de l action
Returns:
action de ce nom contenue dans le HashTable
Definition at line 238 of file Module.java.
References newtonERP.module.Module.getDefaultAction().
Referenced by newtonERP.module.Module.doAction(), and modules.taskModule.entityDefinitions.ActionEntity.getAction().
final Hashtable<String, AbstractAction> newtonERP.module.Module.getActionList ()
Returns:
the actions HashTable
Definition at line 205 of file Module.java.
Referenced by modules.userRightModule.actions.CreateAllRight.doAction().
String newtonERP.module.Module.getDefaultAction ()
Returns:
the defaultAction
Definition at line 73 of file Module.java.
References newtonERP.module.Module.getEntityDefinitionList().
Referenced by newtonERP.module.Module.getAction(), and newtonERP.serveur.CommandRouteur.routeCommand().
String newtonERP.module.Module.getDefaultEntity ()
Returns:
Entité par default (dans le cas d'action par default qui est une baseAction)
Definition at line 392 of file Module.java.
Referenced by newtonERP.serveur.CommandRouteur.routeCommand().
final AbstractOrmEntity newtonERP.module.Module.getEntityDefinition (String entityDefinitionName)
Parameters:
entityDefinitionName nom de l action
Returns:
action de ce nom contenue dans le HashTable
Definition at line 214 of file Module.java.
Referenced by newtonERP.module.Module.doAction(), and modules.taskModule.entityDefinitions.EntityEntity.getEntityDefinition().
final Hashtable<String, AbstractOrmEntity> newtonERP.module.Module.getEntityDefinitionList ()
Returns:
the Vector entities
Definition at line 197 of file Module.java.
Referenced by modules.userRightModule.actions.CreateAllRight.doAction(), and newtonERP.module.Module.getDefaultAction().
Vector<ActionLink> newtonERP.module.Module.getGlobalActionButtonList ()
Returns:
liste des boutons du module
Definition at line 381 of file Module.java.
Referenced by newtonERP.module.Module.addGlobalActionButton(), and newtonERP.viewers.Viewer.getLeftMenu().
final NaturalMap<String, AbstractAction> newtonERP.module.Module.getGlobalActionMenu ()
Returns:
the global action list
Definition at line 353 of file Module.java.
Referenced by newtonERP.module.Module.addGlobalActionMenuItem(), and newtonERP.module.Module.getGlobalActionMenuOrReturnDefaultBehavior().
NaturalMap<String, AbstractAction> newtonERP.module.Module.getGlobalActionMenuOrReturnDefaultBehavior ()
Returns:
retourne les élément du menu du module peu importe qu'ils aient été spécifiés ou pas (cas pour lequel les éléments par défault seront des GetList sur chaque entité du module)
Definition at line 490 of file Module.java.
References newtonERP.module.Module.getGlobalActionMenu().
Referenced by newtonERP.viewers.Viewer.getLeftMenu().
String newtonERP.module.Module.getSystemName ()
Returns:
nom du module dans le système (normalement nom de la classe mais peut être overridé si c'est un module dynamique)
Definition at line 480 of file Module.java.
Referenced by newtonERP.module.Module.getVisibleName(), newtonERP.module.Module.initAction(), newtonERP.module.Module.initDB(), modules.userRightModule.UserRightModule.initDB(), newtonERP.module.Module.initEntityDefinition(), and newtonERP.serveur.Servlet.makeLink().
final String newtonERP.module.Module.getVisibleName ()
Returns:
Nom visible d'un module
Definition at line 400 of file Module.java.
References newtonERP.module.Module.getSystemName().
Referenced by newtonERP.viewers.Viewer.getLeftMenu().
void newtonERP.module.Module.initAction (String path)
initialise la liste d'action du module
Parameters:
path path to the module contening the action
Definition at line 96 of file Module.java.
References newtonERP.module.Module.getSystemName().
Referenced by newtonERP.common.ListModule.getModule().
void newtonERP.module.Module.initEntityDefinition (String path)
initialise la liste de definition d'entite du module
Parameters:
path path to the module contening the action
Definition at line 139 of file Module.java.
References newtonERP.module.Module.getSystemName().
Referenced by newtonERP.common.ListModule.getModule().
boolean newtonERP.module.Module.isVisible ()
Returns:
the visible
Definition at line 536 of file Module.java.
Referenced by newtonERP.viewers.Viewer.getLeftMenu().
void newtonERP.module.Module.setVisible (boolean visible)
Parameters:
visible the visible to set
Definition at line 544 of file Module.java.
final void newtonERP.module.Module.setVisibleName (String visibleName)
Parameters:
visibleName nom visible d'un module
Definition at line 411 of file Module.java.
Referenced by modules.common.Common.Common(), and modules.userRightModule.UserRightModule.UserRightModule().
The documentation for this class was generated from the following file:
src/newtonERP/module/Module.java