Bee ERP: modules.taskModule.actions.GenerateEntityCode Class Reference
modules.taskModule.actions.GenerateEntityCode Class Reference
Génère code source d'entité.
Inherits newtonERP::module::AbstractAction.
Public Member Functions
AbstractEntity doAction (AbstractEntity entity, Hashtable< String, String > parameters)
Abstract method that will be reused by all the actions.
Static Public Member Functions
static void createRightIfNotExist (String moduleName, String entityName, String actionName)
Detailed Description
Génère code source d'entité.
Author:
Guillaume Lacasse
Definition at line 24 of file GenerateEntityCode.java.
Member Function Documentation
static void modules.taskModule.actions.GenerateEntityCode.createRightIfNotExist (String moduleName, String entityName, String actionName) [static]
Parameters:
moduleName module name
entityName entity name
actionName action name
Definition at line 114 of file GenerateEntityCode.java.
References newtonERP.module.AbstractEntity.setData().
AbstractEntity modules.taskModule.actions.GenerateEntityCode.doAction (AbstractEntity entity, Hashtable< String, String > parameters) [virtual]
Abstract method that will be reused by all the actions.
Parameters:
entity entite a utiliser a l'intérieur du doAction
parameters list de parametre autre que l'entite
Returns:
l'entite resultante
Implements newtonERP.module.AbstractAction.
Definition at line 34 of file GenerateEntityCode.java.
References newtonERP.viewers.viewerData.BaseViewerData.addAlertMessage(), newtonERP.viewers.viewerData.BaseViewerData.addNormalMessage(), and newtonERP.module.AbstractOrmEntity.editUI().
The documentation for this class was generated from the following file:
src/modules/taskModule/actions/GenerateEntityCode.java