Bee ERP: modules.taskModule.entityDefinitions.SearchEntity Class Reference
modules.taskModule.entityDefinitions.SearchEntity Class Reference
Entité de recherche pour spécification.
Inherits newtonERP::module::AbstractOrmEntity.
Public Member Functions
Fields initFields ()
initialise les champ de l'entity, doit etre overider si l'entity contient des champs, sinon initialise une liste de champ vide
AbstractOrmEntity getEntity ()
Detailed Description
Entité de recherche pour spécification.
Author:
Guillaume Lacasse
Definition at line 17 of file SearchEntity.java.
Member Function Documentation
AbstractOrmEntity modules.taskModule.entityDefinitions.SearchEntity.getEntity ()
Returns:
vraie entité de recherche
Definition at line 42 of file SearchEntity.java.
References modules.taskModule.entityDefinitions.EntityEntity.getEntityDefinition(), and newtonERP.module.AbstractOrmEntity.getSingleAccessor().
Fields modules.taskModule.entityDefinitions.SearchEntity.initFields () [virtual]
initialise les champ de l'entity, doit etre overider si l'entity contient des champs, sinon initialise une liste de champ vide
Returns:
le Fields initialiser
Implements newtonERP.module.AbstractOrmEntity.
Definition at line 29 of file SearchEntity.java.
References newtonERP.module.AbstractOrmEntity.getForeignKeyName(), and newtonERP.module.AbstractOrmEntity.getPrimaryKeyName().
The documentation for this class was generated from the following file:
src/modules/taskModule/entityDefinitions/SearchEntity.java