Bee ERP: modules.userRightModule.entityDefinitions.User Class Reference
modules.userRightModule.entityDefinitions.User Class Reference
Entity defenition class representing a user.
Inherits newtonERP::module::AbstractOrmEntity.
Public Member Functions
Fields initFields ()
initialise les champ de l'entity, doit etre overider si l'entity contient des champs, sinon initialise une liste de champ vide
Groups getGroupsEntity ()
permet d'obtenir directement l'entity groups lie a cet user
Detailed Description
Entity defenition class representing a user.
Author:
r3hallejo cloutierJo
Definition at line 16 of file User.java.
Member Function Documentation
Groups modules.userRightModule.entityDefinitions.User.getGroupsEntity ()
permet d'obtenir directement l'entity groups lie a cet user
Returns:
le group lie
Definition at line 47 of file User.java.
References newtonERP.module.AbstractOrmEntity.getSingleAccessor().
Referenced by modules.userRightModule.actions.RightCheck.doAction().
Fields modules.userRightModule.entityDefinitions.User.initFields () [virtual]
initialise les champ de l'entity, doit etre overider si l'entity contient des champs, sinon initialise une liste de champ vide
Returns:
le Fields initialiser
Implements newtonERP.module.AbstractOrmEntity.
Definition at line 30 of file User.java.
References newtonERP.module.AbstractOrmEntity.getPrimaryKeyName().
The documentation for this class was generated from the following file:
src/modules/userRightModule/entityDefinitions/User.java