Bee ERP: newtonERP.viewers.secondStep.LinkViewer Class Reference
newtonERP.viewers.secondStep.LinkViewer Class Reference
Sert à formatter de l'argent.
Static Public Member Functions
static String getHtmlCode (ActionLink actionLink)
static int getNextBalloonDivId ()
Detailed Description
Sert à formatter de l'argent.
Author:
Guillaume
Definition at line 12 of file LinkViewer.java.
Member Function Documentation
static String newtonERP.viewers.secondStep.LinkViewer.getHtmlCode (ActionLink actionLink) [static]
Parameters:
actionLink representation du lien a effectuer
Returns:
bouton de lien
Definition at line 20 of file LinkViewer.java.
References newtonERP.common.ActionLink.getName(), newtonERP.viewers.secondStep.LinkViewer.getNextBalloonDivId(), and newtonERP.common.ActionLink.getUrlParam().
static int newtonERP.viewers.secondStep.LinkViewer.getNextBalloonDivId () [static]
Returns:
prochain ID de bulle d'aide
Definition at line 56 of file LinkViewer.java.
Referenced by newtonERP.viewers.secondStep.LinkViewer.getHtmlCode().
The documentation for this class was generated from the following file:
src/newtonERP/viewers/secondStep/LinkViewer.java