Bee ERP: newtonERP.serveur.CommandRouteur Class Reference
newtonERP.serveur.CommandRouteur Class Reference
Public Member Functions
AbstractEntity routeCommand (String moduleName, String actionName, String entityName, Hashtable< String, String > parameter)
dirige une demande client vers une action d'un module
Detailed Description
Author:
Gabriel Therrien JoCloutier
Definition at line 18 of file CommandRouteur.java.
Member Function Documentation
AbstractEntity newtonERP.serveur.CommandRouteur.routeCommand (String moduleName, String actionName, String entityName, Hashtable< String, String > parameter)
dirige une demande client vers une action d'un module
Parameters:
moduleName nom du module
actionName BaseAction a executer
entityName nom de l'entite contenant la baseAction
moduleGetter la nom du modulGetter a utiliser
parameter parametre a passer a l'action
Returns:
une entity viewable
Definition at line 30 of file CommandRouteur.java.
References newtonERP.module.Module.doAction(), newtonERP.module.Module.getDefaultAction(), and newtonERP.module.Module.getDefaultEntity().
Referenced by newtonERP.serveur.Servlet.urlToAction().
The documentation for this class was generated from the following file:
src/newtonERP/serveur/CommandRouteur.java