Bee ERP: newtonERP.viewers.Viewer Class Reference
newtonERP.viewers.Viewer Class Reference
Represents the main viewer for our ERP.
Static Public Member Functions
static String getHtmlCode (AbstractEntity entity, String moduleName, String actionName)
Gets the html code by calling the same method in the right viewer.
static String getHeader (String moduleName, String actionName)
Gets the html code for the header ***(id="header" -> dans css pour mise en page).
static String getLeftMenu (String moduleName)
Gets the html code for left menu (css pour mise en page).
static String getFooter ()
Gets the html code for the footer ***(id="footer" -> dans css pour mise en page).
static String getEncoding ()
Detailed Description
Represents the main viewer for our ERP.
Author:
Guillaume Lacasse, Pascal Lemay
Definition at line 42 of file Viewer.java.
Member Function Documentation
static String newtonERP.viewers.Viewer.getEncoding () [static]
Returns:
encodage de charset
Definition at line 261 of file Viewer.java.
static String newtonERP.viewers.Viewer.getFooter () [static]
Gets the html code for the footer ***(id="footer" -> dans css pour mise en page).
Returns:
html
Definition at line 252 of file Viewer.java.
Referenced by newtonERP.viewers.Viewer.getHtmlCode().
static String newtonERP.viewers.Viewer.getHeader (String moduleName, String actionName) [static]
Gets the html code for the header ***(id="header" -> dans css pour mise en page).
Parameters:
moduleName the module name
actionName the action name
Returns:
html
Definition at line 102 of file Viewer.java.
Referenced by newtonERP.viewers.Viewer.getHtmlCode().
static String newtonERP.viewers.Viewer.getHtmlCode (AbstractEntity entity, String moduleName, String actionName) [static]
Gets the html code by calling the same method in the right viewer.
Parameters:
entity the entity to view
moduleName the module of entity
actionName the action to perform
Returns:
the viewer
Definition at line 54 of file Viewer.java.
References newtonERP.viewers.Viewer.getFooter(), newtonERP.viewers.Viewer.getHeader(), and newtonERP.viewers.Viewer.getLeftMenu().
static String newtonERP.viewers.Viewer.getLeftMenu (String moduleName) [static]
Gets the html code for left menu (css pour mise en page).
Parameters:
moduleName the module name
Returns:
html
Definition at line 177 of file Viewer.java.
References newtonERP.module.Module.getGlobalActionButtonList(), newtonERP.module.Module.getGlobalActionMenuOrReturnDefaultBehavior(), newtonERP.module.Module.getVisibleName(), and newtonERP.module.Module.isVisible().
Referenced by newtonERP.viewers.Viewer.getHtmlCode().
The documentation for this class was generated from the following file:
src/newtonERP/viewers/Viewer.java