Bee ERP: newtonERP.module.generalEntity.ListOfValue Class Reference
newtonERP.module.generalEntity.ListOfValue Class Reference
Inherits newtonERP::viewers::viewables::SelectBoxViewable.
Public Member Functions
ListOfValue (AbstractOrmEntity sourceEntity, String labelName, AbstractOrmEntity foreignEntity)
NaturalMap< String, String > getElements ()
String getLabelName ()
String getForeignValue (String currentForeignPrimaryKey)
AbstractOrmEntity getForeignEntityDefinition ()
AbstractOrmEntity getSourceEntityDefinition ()
boolean equals (ListOfValue other)
Detailed Description
Author:
Guillaume Lacasse
List of value for the viewers
Definition at line 15 of file ListOfValue.java.
Constructor & Destructor Documentation
newtonERP.module.generalEntity.ListOfValue.ListOfValue (AbstractOrmEntity sourceEntity, String labelName, AbstractOrmEntity foreignEntity)
Parameters:
sourceEntity source entity
labelName the label name
foreignPrimaryKey the foreign primary key naturelle de l'entité étrangere
foreignEntity the foreign entity
Definition at line 28 of file ListOfValue.java.
Member Function Documentation
boolean newtonERP.module.generalEntity.ListOfValue.equals (ListOfValue other)
Parameters:
other autre list of value
Returns:
si les list of value sont pareilles
Definition at line 100 of file ListOfValue.java.
References newtonERP.module.generalEntity.ListOfValue.getForeignEntityDefinition(), newtonERP.module.generalEntity.ListOfValue.getLabelName(), newtonERP.module.generalEntity.ListOfValue.getSourceEntityDefinition(), and newtonERP.module.AbstractEntity.getSystemName().
NaturalMap<String, String> newtonERP.module.generalEntity.ListOfValue.getElements ()
Returns:
the elements of the select box
Implements newtonERP.viewers.viewables.SelectBoxViewable.
Definition at line 36 of file ListOfValue.java.
Referenced by newtonERP.viewers.secondStep.SelectBoxViewer.getHtmlCode().
AbstractOrmEntity newtonERP.module.generalEntity.ListOfValue.getForeignEntityDefinition ()
Returns:
définition pour entité étrangère
Definition at line 83 of file ListOfValue.java.
Referenced by newtonERP.module.generalEntity.ListOfValue.equals(), newtonERP.viewers.viewerData.ListViewerData.getCases(), newtonERP.orm.associations.SingleAccessorManager.getSingleAccessor(), and newtonERP.orm.associations.SingleAccessorManager.getSingleAccessorList().
String newtonERP.module.generalEntity.ListOfValue.getForeignValue (String currentForeignPrimaryKey)
Parameters:
currentForeignPrimaryKey the primary key
Returns:
the foreign value of the primary key
Definition at line 61 of file ListOfValue.java.
References newtonERP.module.AbstractOrmEntity.getNaturalKeyDescription(), newtonERP.module.AbstractOrmEntity.getPrimaryKeyName(), and newtonERP.module.AbstractOrmEntity.getVisibleName().
Referenced by newtonERP.viewers.viewerData.ListViewerData.getCases(), and newtonERP.module.AbstractOrmEntity.getNaturalKeyDescription().
String newtonERP.module.generalEntity.ListOfValue.getLabelName ()
Returns:
the label name
Implements newtonERP.viewers.viewables.SelectBoxViewable.
Definition at line 52 of file ListOfValue.java.
Referenced by newtonERP.module.generalEntity.ListOfValue.equals(), newtonERP.viewers.viewerData.ListViewerData.getHeader(), and newtonERP.viewers.secondStep.SelectBoxViewer.getHtmlCode().
AbstractOrmEntity newtonERP.module.generalEntity.ListOfValue.getSourceEntityDefinition ()
Returns:
entité qui a une listOfValue
Definition at line 91 of file ListOfValue.java.
Referenced by newtonERP.module.generalEntity.ListOfValue.equals().
The documentation for this class was generated from the following file:
src/newtonERP/module/generalEntity/ListOfValue.java