Bee ERP: modules.taskModule.entityDefinitions.FieldEntity Class Reference
modules.taskModule.entityDefinitions.FieldEntity Class Reference
Représente un champ.
Inherits newtonERP::module::AbstractOrmEntity.
Public Member Functions
Fields initFields ()
initialise les champ de l'entity, doit etre overider si l'entity contient des champs, sinon initialise une liste de champ vide
AbstractEntity newUI (Hashtable< String, String > parameters)
BaseAction New.
ListViewerData getList (Hashtable< String, String > parameters)
Field<?> getFieldInstance ()
AbstractEntity deleteUI (Hashtable< String, String > parameters)
BaseAction Delete, on ne veut pas deleter de Field.
Protected Member Functions
Fields preInitFields ()
Detailed Description
Représente un champ.
Author:
Guillaume Lacasse
Definition at line 30 of file FieldEntity.java.
Member Function Documentation
AbstractEntity modules.taskModule.entityDefinitions.FieldEntity.deleteUI (Hashtable< String, String > parameters)
BaseAction Delete, on ne veut pas deleter de Field.
Parameters:
parameters parametre suplementaire
Returns:
todo: qu'Est-ce que l'on devrai retourné en general?
Reimplemented from newtonERP.module.AbstractOrmEntity.
Definition at line 198 of file FieldEntity.java.
References newtonERP.viewers.viewerData.BaseViewerData.addAlertMessage(), newtonERP.module.AbstractOrmEntity.editUI(), newtonERP.module.AbstractEntity.getDataString(), and newtonERP.module.AbstractOrmEntity.getSingleAccessor().
Field<?> modules.taskModule.entityDefinitions.FieldEntity.getFieldInstance ()
Returns:
retourne un vrai field
Definition at line 142 of file FieldEntity.java.
References newtonERP.module.AbstractEntity.getData(), and newtonERP.module.AbstractEntity.getDataString().
Referenced by modules.taskModule.actions.AddFieldToOrm.doAction().
ListViewerData modules.taskModule.entityDefinitions.FieldEntity.getList (Hashtable< String, String > parameters)
Parameters:
parameters parametres de sélection (à venir)
Returns:
une liste d'entité de ce type
Reimplemented from newtonERP.module.AbstractOrmEntity.
Definition at line 120 of file FieldEntity.java.
References newtonERP.viewers.viewerData.GridViewerData.addSpecificActionButtonList(), newtonERP.module.AbstractOrmEntity.getPrimaryKeyName(), newtonERP.module.AbstractOrmEntity.getVisibleName(), and newtonERP.viewers.viewerData.BaseViewerData.removeGlobalActions().
Fields modules.taskModule.entityDefinitions.FieldEntity.initFields () [virtual]
initialise les champ de l'entity, doit etre overider si l'entity contient des champs, sinon initialise une liste de champ vide
Returns:
le Fields initialiser
Implements newtonERP.module.AbstractOrmEntity.
Definition at line 51 of file FieldEntity.java.
References newtonERP.module.AbstractOrmEntity.getForeignKeyName(), and newtonERP.module.AbstractOrmEntity.getPrimaryKeyName().
AbstractEntity modules.taskModule.entityDefinitions.FieldEntity.newUI (Hashtable< String, String > parameters)
BaseAction New.
Parameters:
parameters parametre suplementaire
Returns:
l'entity qui a été entré en DB (incluant la primaryKey)
Reimplemented from newtonERP.module.AbstractOrmEntity.
Definition at line 80 of file FieldEntity.java.
References modules.taskModule.entityDefinitions.EntityEntity.buildPrimaryKeyName(), modules.taskModule.entityDefinitions.EntityEntity.ContainsPrimaryKeyField(), newtonERP.module.AbstractOrmEntity.editUI(), newtonERP.module.AbstractEntity.getFields(), and newtonERP.orm.field.Fields.setDefaultValue().
The documentation for this class was generated from the following file:
src/modules/taskModule/entityDefinitions/FieldEntity.java