Bee ERP: newtonERP.module.generalEntity.ScrollList Class Reference
newtonERP.module.generalEntity.ScrollList Class Reference
Entité comportant une scrollbar.
Inherits newtonERP::module::AbstractEntity, and newtonERP::viewers::viewables::ScrollListViewable.
Public Member Functions
ScrollList (String title)
void addLink (String name, String url)
TreeMap< String, String > getLinkList ()
Vector< NaturalMap< String,
String > > getLinkGroupList ()
String getTitle ()
void addLinkGroup (String link1Name, String link1Url, String link2Name, String link2Url)
void setTitleUrl (String titleUrl)
String getTitleUrl ()
void addActionLink (ActionLink actionLink)
Vector< ActionLink > getActionLinkList ()
Detailed Description
Entité comportant une scrollbar.
Cette entité peut être vue comme une liste HTML de lien ou de texte.
Author:
Guillaume Lacasse
Definition at line 16 of file ScrollList.java.
Constructor & Destructor Documentation
newtonERP.module.generalEntity.ScrollList.ScrollList (String title)
Parameters:
title titre
Definition at line 31 of file ScrollList.java.
Member Function Documentation
void newtonERP.module.generalEntity.ScrollList.addActionLink (ActionLink actionLink)
Parameters:
actionLink actionLink à ajouter
Definition at line 104 of file ScrollList.java.
References newtonERP.module.generalEntity.ScrollList.getActionLinkList().
void newtonERP.module.generalEntity.ScrollList.addLink (String name, String url)
Parameters:
name nom visible du lien
url url du lien
Definition at line 41 of file ScrollList.java.
void newtonERP.module.generalEntity.ScrollList.addLinkGroup (String link1Name, String link1Url, String link2Name, String link2Url)
Parameters:
link1Name Premier nom de lien
link1Url Premier url
link2Name 2e nom de lien
link2Url 2e url
Definition at line 77 of file ScrollList.java.
References newtonERP.module.generalEntity.ScrollList.getLinkGroupList().
Vector<ActionLink> newtonERP.module.generalEntity.ScrollList.getActionLinkList ()
Returns:
liste des actionLink
Implements newtonERP.viewers.viewables.ScrollListViewable.
Definition at line 112 of file ScrollList.java.
Referenced by newtonERP.module.generalEntity.ScrollList.addActionLink().
Vector<NaturalMap<String, String> > newtonERP.module.generalEntity.ScrollList.getLinkGroupList ()
Returns:
liste de groupe de liens
Implements newtonERP.viewers.viewables.ScrollListViewable.
Definition at line 57 of file ScrollList.java.
Referenced by newtonERP.module.generalEntity.ScrollList.addLinkGroup().
TreeMap<String, String> newtonERP.module.generalEntity.ScrollList.getLinkList ()
Returns:
liste des liens dans la liste (clef: nom visible, valeur: url)
Implements newtonERP.viewers.viewables.ScrollListViewable.
Definition at line 50 of file ScrollList.java.
String newtonERP.module.generalEntity.ScrollList.getTitle ()
Returns:
le titre de la liste
Implements newtonERP.viewers.viewables.ScrollListViewable.
Definition at line 66 of file ScrollList.java.
String newtonERP.module.generalEntity.ScrollList.getTitleUrl ()
Returns:
url du titre si c'est un lien
Implements newtonERP.viewers.viewables.ScrollListViewable.
Definition at line 96 of file ScrollList.java.
void newtonERP.module.generalEntity.ScrollList.setTitleUrl (String titleUrl)
Parameters:
titleUrl url du titre (facultatif)
Definition at line 90 of file ScrollList.java.
The documentation for this class was generated from the following file:
src/newtonERP/module/generalEntity/ScrollList.java