Bee ERP: newtonERP.taskManager.TaskManager Class Reference
newtonERP.taskManager.TaskManager Class Reference
Gestionnaire de tâches (effectue les tâches automatisées).
Static Public Member Functions
static AbstractEntity executeTasks (AbstractOrmEntity entity, int primaryKeyValue)
static AbstractEntity executeTasks (AbstractOrmEntity entity)
static AbstractEntity executeTasks (AbstractOrmEntity entity, Hashtable< String, String > entityParameters)
static AbstractEntity executeTasks (String entityName, Hashtable< String, String > entityParameters)
static void executeTasks (Vector< AbstractOrmEntity > searchEntities, Hashtable< String, String > entityParameters)
Detailed Description
Gestionnaire de tâches (effectue les tâches automatisées).
Author:
Guillaume Lacasse
Definition at line 22 of file TaskManager.java.
Member Function Documentation
static AbstractEntity newtonERP.taskManager.TaskManager.executeTasks (AbstractOrmEntity entity, int primaryKeyValue) [static]
Parameters:
entity entité pour laquelle on veut exécuter les tâches
primaryKeyValue valeur de clef primaire
Returns:
retour de l'action d'une tâche exécutée (s'il y a lieu)
Definition at line 31 of file TaskManager.java.
References newtonERP.module.AbstractEntity.getFields(), and newtonERP.module.AbstractOrmEntity.getPrimaryKeyName().
Referenced by newtonERP.taskManager.TaskManager.executeTasks().
static void newtonERP.taskManager.TaskManager.executeTasks (Vector< AbstractOrmEntity > searchEntities, Hashtable< String, String > entityParameters) [static]
Parameters:
searchEntities entités pour lesquelles on doit possiblement effectuer des tâches
entityParameters paramètres de l'entité
Definition at line 223 of file TaskManager.java.
References newtonERP.taskManager.TaskManager.executeTasks().
static AbstractEntity newtonERP.taskManager.TaskManager.executeTasks (String entityName, Hashtable< String, String > entityParameters) [static]
Parameters:
entityName nom de l'entité
entityParameters paramètres de l'entité
Returns:
enitité visible de retour
Definition at line 79 of file TaskManager.java.
static AbstractEntity newtonERP.taskManager.TaskManager.executeTasks (AbstractOrmEntity entity, Hashtable< String, String > entityParameters) [static]
Parameters:
entity Entité pour laquelle on doit effecter des tâches s'il y a lieu
entityParameters paramètres de l'entité
Returns:
entité viewable de retour
Definition at line 68 of file TaskManager.java.
References newtonERP.taskManager.TaskManager.executeTasks(), and newtonERP.module.AbstractEntity.getSystemName().
static AbstractEntity newtonERP.taskManager.TaskManager.executeTasks (AbstractOrmEntity entity) [static]
Parameters:
entity entité pour laquelle on veut exécuter les tâches
Returns:
retour de l'action d'une tâche exécutée (s'il y a lieu)
Definition at line 48 of file TaskManager.java.
References newtonERP.taskManager.TaskManager.executeTasks(), newtonERP.module.AbstractEntity.getFields(), newtonERP.module.AbstractOrmEntity.getPrimaryKeyName(), and newtonERP.module.AbstractOrmEntity.getPrimaryKeyValue().
The documentation for this class was generated from the following file:
src/newtonERP/taskManager/TaskManager.java