Bee ERP: newtonERP.module.generalEntity.Form Class Reference
newtonERP.module.generalEntity.Form Class Reference
Inherits newtonERP::viewers::viewerData::PromptViewerData.
Public Member Functions
Form (Module currentModule, AbstractAction currentAction)
void addField (String label, String fieldName, String currentValue)
void addField (String label, String fieldName)
void addField (Field<?> field)
Detailed Description
Author:
Guillaume Lacasse
A loging form
Definition at line 13 of file Form.java.
Constructor & Destructor Documentation
newtonERP.module.generalEntity.Form.Form (Module currentModule, AbstractAction currentAction)
Parameters:
currentModule module courant
currentAction action courante
currentSelectedUser the currently selected user
Definition at line 20 of file Form.java.
References newtonERP.module.AbstractEntity.setCurrentAction(), newtonERP.module.AbstractEntity.setCurrentModule(), and newtonERP.viewers.viewerData.PromptViewerData.setData().
Member Function Documentation
void newtonERP.module.generalEntity.Form.addField (String label, String fieldName, String currentValue)
Parameters:
label étiquette du champ
fieldName nom du champ
currentValue valeur courante
Definition at line 34 of file Form.java.
References newtonERP.viewers.viewerData.PromptViewerData.getData().
Referenced by newtonERP.module.generalEntity.Form.addField(), and modules.userRightModule.actions.Login.doAction().
void newtonERP.module.generalEntity.Form.addField (Field<?> field)
Parameters:
field un field a ajouter
Definition at line 52 of file Form.java.
References newtonERP.module.generalEntity.Form.addField(), and newtonERP.viewers.viewerData.PromptViewerData.getData().
void newtonERP.module.generalEntity.Form.addField (String label, String fieldName)
Parameters:
label étiquette du champ
fieldName nom du champ
Definition at line 44 of file Form.java.
References newtonERP.module.generalEntity.Form.addField(), and newtonERP.viewers.viewerData.PromptViewerData.getData().
The documentation for this class was generated from the following file:
src/newtonERP/module/generalEntity/Form.java