Bee ERP: modules.taskModule.entityDefinitions.TaskEntity Class Reference
modules.taskModule.entityDefinitions.TaskEntity Class Reference
entité représentant une task
Inherits newtonERP::module::AbstractOrmEntity.
Public Member Functions
Fields initFields ()
initialise les champ de l'entity, doit etre overider si l'entity contient des champs, sinon initialise une liste de champ vide
boolean isSatisfied (Hashtable< String, String > entityParameters, boolean isStraightSearch)
AbstractEntity execute (Hashtable< String, String > entityParameters, boolean isStraightSearch)
Execute l'effet de la tâche.
boolean isActive ()
boolean isStraightSearch ()
Detailed Description
entité représentant une task
Author:
Guillaume Lacasse
Definition at line 19 of file TaskEntity.java.
Member Function Documentation
AbstractEntity modules.taskModule.entityDefinitions.TaskEntity.execute (Hashtable< String, String > entityParameters, boolean isStraightSearch)
Execute l'effet de la tâche.
Parameters:
entityParameters paramètres de l'entité
isStraightSearch si c'est une recherche directe
Returns:
entité viewable, résultat de la tâche
Definition at line 75 of file TaskEntity.java.
References modules.taskModule.entityDefinitions.EffectEntity.execute().
Fields modules.taskModule.entityDefinitions.TaskEntity.initFields () [virtual]
initialise les champ de l'entity, doit etre overider si l'entity contient des champs, sinon initialise une liste de champ vide
Returns:
le Fields initialiser
Implements newtonERP.module.AbstractOrmEntity.
Definition at line 32 of file TaskEntity.java.
References newtonERP.module.AbstractOrmEntity.getForeignKeyName(), and newtonERP.module.AbstractOrmEntity.getPrimaryKeyName().
boolean modules.taskModule.entityDefinitions.TaskEntity.isActive ()
Returns:
si la tâche est présentement active
Definition at line 90 of file TaskEntity.java.
References newtonERP.module.AbstractEntity.getData().
boolean modules.taskModule.entityDefinitions.TaskEntity.isSatisfied (Hashtable< String, String > entityParameters, boolean isStraightSearch)
Parameters:
entityParameters paramètres de l'entité
isStraightSearch si c'est une recherche directe
Returns:
true si la spécification de la tâche est satisfaite
Definition at line 56 of file TaskEntity.java.
References modules.taskModule.entityDefinitions.Specification.isSatisfied().
boolean modules.taskModule.entityDefinitions.TaskEntity.isStraightSearch ()
Returns:
si c'est une recherche directe
Definition at line 98 of file TaskEntity.java.
References newtonERP.module.AbstractEntity.getData().
The documentation for this class was generated from the following file:
src/modules/taskModule/entityDefinitions/TaskEntity.java