Bee ERP: newtonERP.orm.associations.ListOfValueManager Class Reference
newtonERP.orm.associations.ListOfValueManager Class Reference
List of value manager.
Static Public Member Functions
static final void addListOfValue (AbstractOrmEntity entity, AbstractOrmEntity foreignEntity)
Detailed Description
List of value manager.
Author:
Guillaume Lacasse
Definition at line 12 of file ListOfValueManager.java.
Member Function Documentation
static final void newtonERP.orm.associations.ListOfValueManager.addListOfValue (AbstractOrmEntity entity, AbstractOrmEntity foreignEntity) [static]
Parameters:
entity Entité source
foreignEntity Entité cible
Definition at line 18 of file ListOfValueManager.java.
References newtonERP.module.AbstractEntity.addNegativeListOfValue(), newtonERP.module.AbstractEntity.addPositiveListOfValue(), newtonERP.module.AbstractEntity.getFields(), newtonERP.module.AbstractOrmEntity.getForeignKeyName(), and newtonERP.module.AbstractEntity.getSystemName().
The documentation for this class was generated from the following file:
src/newtonERP/orm/associations/ListOfValueManager.java