Bee ERP: newtonERP.viewers.viewables.ScrollListViewable Interface Reference
newtonERP.viewers.viewables.ScrollListViewable Interface Reference
Element graphique visible en tant que liste scrollable de lien ou de texte avec une scrollbar.
Inherited by newtonERP.module.generalEntity.ScrollList.
Public Member Functions
String getTitle ()
TreeMap< String, String > getLinkList ()
Vector< NaturalMap< String,
String > > getLinkGroupList ()
String getTitleUrl ()
Vector< ActionLink > getActionLinkList ()
Detailed Description
Element graphique visible en tant que liste scrollable de lien ou de texte avec une scrollbar.
Author:
Guillaume
Definition at line 14 of file ScrollListViewable.java.
Member Function Documentation
Vector<ActionLink> newtonERP.viewers.viewables.ScrollListViewable.getActionLinkList ()
Returns:
liste des actionLink
Implemented in newtonERP.module.generalEntity.ScrollList.
Referenced by newtonERP.viewers.secondStep.ScrollListViewer.getHtmlContent().
Vector<NaturalMap<String, String> > newtonERP.viewers.viewables.ScrollListViewable.getLinkGroupList ()
Returns:
liste de groupe de liens
Implemented in newtonERP.module.generalEntity.ScrollList.
Referenced by newtonERP.viewers.secondStep.ScrollListViewer.getHtmlContent().
TreeMap<String, String> newtonERP.viewers.viewables.ScrollListViewable.getLinkList ()
Returns:
liste des liens dans la liste (clef: nom visible, valeur: url)
Implemented in newtonERP.module.generalEntity.ScrollList.
Referenced by newtonERP.viewers.secondStep.ScrollListViewer.getHtmlContent().
String newtonERP.viewers.viewables.ScrollListViewable.getTitle ()
Returns:
le titre de la liste
Implemented in newtonERP.module.generalEntity.ScrollList.
Referenced by newtonERP.viewers.secondStep.ScrollListViewer.getHtmlContent().
String newtonERP.viewers.viewables.ScrollListViewable.getTitleUrl ()
Returns:
url du titre si c'est un lien
Implemented in newtonERP.module.generalEntity.ScrollList.
Referenced by newtonERP.viewers.secondStep.ScrollListViewer.getHtmlContent().
The documentation for this interface was generated from the following file:
src/newtonERP/viewers/viewables/ScrollListViewable.java