package newtonERP.orm;

import java.lang.reflect.Field;
import java.sql.ResultSet;
import java.util.Hashtable;
import java.util.Iterator;
import java.util.Vector;

import newtonERP.orm.exceptions.OrmException;
import newtonERP.orm.sgbd.SgbdSqlite;
import newtonERP.orm.sgbd.Sgbdable;

/**
 * 
 * @author r3hallejo, r3lacasgu
 * 
 *         Basic class for the orm. It is used to put the objects in the databse
 *         using SqLite3 and its java binding. The orm will receive an entity
 *         from which the orm will perform various tasks such as generating the
 *         query. Then it's gonna send the query to the SgbdSqlite classe to
 *         execute it.
 */
public class Orm
{
    private static Sgbdable sgbd = new SgbdSqlite();

    /**
     * Method used to do search queries done from the views to the databse. The
     * search criterias that has been passed in parameter are a list of string
     * that has been generated by the view modules
     * 
     * @param searchEntity, a list of search criterias
     * @return a vector of Ormizable entities
     */
    public static Vector<Ormizable> select(Ormizable searchEntity,
	    Vector<String> searchCriteriasParam) throws OrmException
    {
	Vector<Ormizable> returnedEntities = new Vector<Ormizable>();

	String sqlQuery = "SELECT * FROM " + searchEntity.getTableName()
		+ " WHERE ";

	// Affectation des parametres, le but sera de passer au travers de ces
	// parametres pour les rajouter dans la sql query
	Vector<String> searchCriterias = searchCriteriasParam;

	// Generally a parameter will be under the following form :
	// OPERATOR (or not if it's the first) + FieldName + OPERATOR + value
	// The view will have to take care that the criterias are well built so
	// the orm can work
	for (String parameter : searchCriterias)
	{
	    sqlQuery += parameter;
	}

	ResultSet rs = sgbd.Execute(sqlQuery, OrmActions.SEARCH);
	System.out.println("SQL query produced : " + sqlQuery);

	// Now we will iterate through the result set to create the entities
	try
	{
	    // Fort each row in my result set
	    while (rs.next())
	    {
		Ormizable entity = searchEntity.getClass().newInstance();
		Field[] fields = entity.getClass().getFields();
		Hashtable<String, Object> parameters = new Hashtable<String, Object>();

		// we add each column to the hashtable
		for (int i = 0; i < fields.length; i++)
		{
		    // Will have to find out if this works properly
		    parameters.put(fields[i].getName(), rs.getObject(i));
		}

		entity.setOrmizableData(parameters);
		returnedEntities.add(entity);
	    }
	} catch (Exception e)
	{
	    // TODO Auto-generated catch block
	    e.printStackTrace();
	}

	return returnedEntities;
    }

    /**
     * Method used to add an entity in the databse
     * 
     * @param newEntity
     * @throws OrmException
     */
    public static void insert(Ormizable newEntity) throws OrmException
    {
	Hashtable<String, String> data = newEntity.getOrmizableData();
	String sqlQuery = "";

	// We add the hardcoded statements, in this case INSERT TO
	sqlQuery += "INSERT INTO " + newEntity.getTableName() + " (";

	// We now iterate through the key set so we can add the fields to the
	// query
	Iterator keySetIterator = data.keySet().iterator();
	while (keySetIterator.hasNext())
	{
	    // Retrieve key
	    Object key = keySetIterator.next();

	    if (!keySetIterator.hasNext())
		sqlQuery += "'" + key.toString() + "') ";
	    else
		sqlQuery += "'" + key.toString() + "', ";
	}

	// We add the VALUES keyword for the query
	sqlQuery += "VALUES (";

	// Now we add the values to the query
	Iterator valueIterator = data.values().iterator();
	while (valueIterator.hasNext())
	{
	    Object value = valueIterator.next();

	    if (!valueIterator.hasNext())
		sqlQuery += "'" + value.toString() + "') ";
	    else
		sqlQuery += "'" + value.toString() + "', ";
	}

	// We execute the query and print out the sql query produced to see we
	// have no errors
	sgbd.Execute(sqlQuery, OrmActions.INSERT);
	System.out.println("SQL query produced : " + sqlQuery);
    }

    /**
     * Method used to delete an entity from the database
     * 
     * @param searchEntity
     * @throws OrmException
     */
    public static void delete(Ormizable searchEntity) throws OrmException
    {
    }

    /**
     * Method used to update / change an entity
     * 
     * @param searchEntity
     * @param entityContainingChanges
     * @throws OrmException
     */
    public static void update(Ormizable searchEntity,
	    Ormizable entityContainingChanges) throws OrmException
    {
    }
}
