Bee ERP: newtonERP.orm.sgbd.AbstractSgbd Class Reference
newtonERP.orm.sgbd.AbstractSgbd Class Reference
Inherited by newtonERP.orm.sgbd.sqlite.SgbdSqlite.
Public Member Functions
abstract ResultSet execute (String request, OrmActions action)
Method that executes the sql query passed in paramter plus de action from the OrmAction.
abstract void connect ()
Method used to initialize the connection to the databse.
abstract void disconnect ()
Method used to disconnect from the database.
abstract ResultSet addColumnToTable (AbstractOrmEntity entity, Field<?> field)
Alter table.
abstract ResultSet select (AbstractOrmEntity searchEntity, Vector< String > searchCriteriasParam)
Use only for complex queries.
abstract ResultSet select (Vector< AbstractOrmEntity > searchEntities)
Uses the new where builder.
abstract int insert (AbstractOrmEntity newEntity)
Method used to insert an entity in the database based into the entity passed in parameter.
abstract void delete (AbstractOrmEntity searchEntity, Vector< String > searchCriterias)
Method used to delete an entity from the database.
abstract void delete (Vector< AbstractOrmEntity > searchEntities)
Uses the new where builder.
abstract void update (AbstractOrmEntity entityContainingChanges, Vector< String > searchCriterias)
Method used to update / change an entity.
abstract void update (Vector< AbstractOrmEntity > searchEntities, AbstractOrmEntity entityContainingChanges)
Uses the new where builder.
abstract boolean isEntityExists (String entitySystemName)
abstract void createIndex (String entityName, String fieldName)
Sert à ajouter un index dans la table SQL de l'entité pour un field en particulier.
abstract void createTableForEntity (AbstractOrmEntity entity)
Créer une table pour un type d'entité.
abstract void updateUnique (AbstractOrmEntity searchEntity, AbstractOrmEntity entityContainingChanges)
Uses the new where builder.
abstract ResultSet select (AbstractOrmEntity searchEntity, Vector< String > searchCriteriasParam, int limit, int offset, String orderBy)
Use only for complex queries.
int count (AbstractOrmEntity searchEntity)
abstract int count (AbstractOrmEntity searchEntity, Vector< String > searchParameterList)
abstract void doBackup ()
Fait un backup de la DB.
abstract long getLatestBackupTime ()
Detailed Description
Author:
BeeERP team Représente tous les SGBD et leurs implémentations et déclatations communes
Definition at line 14 of file AbstractSgbd.java.
Member Function Documentation
abstract ResultSet newtonERP.orm.sgbd.AbstractSgbd.addColumnToTable (AbstractOrmEntity entity, Field<?> field) [pure virtual]
Alter table.
Parameters:
entity the entity containing the new field
field the field to add
Returns:
?
Implemented in newtonERP.orm.sgbd.sqlite.SgbdSqlite.
Referenced by newtonERP.orm.Orm.addColumnToTable().
abstract void newtonERP.orm.sgbd.AbstractSgbd.connect () [pure virtual]
Method used to initialize the connection to the databse.
Implemented in newtonERP.orm.sgbd.sqlite.SgbdSqlite.
Referenced by newtonERP.orm.Orm.connect().
int newtonERP.orm.sgbd.AbstractSgbd.count (AbstractOrmEntity searchEntity)
Parameters:
searchEntity entité de recherche
Returns:
nombre d'occurence du type de l'entité de recherche
Definition at line 184 of file AbstractSgbd.java.
Referenced by newtonERP.orm.Orm.count().
abstract int newtonERP.orm.sgbd.AbstractSgbd.count (AbstractOrmEntity searchEntity, Vector< String > searchParameterList) [pure virtual]
Parameters:
searchEntity entité de recherche
searchParameterList paramêtres de recherche
Returns:
nombre d'occurence du type de l'entité de recherche
Implemented in newtonERP.orm.sgbd.sqlite.SgbdSqlite.
abstract void newtonERP.orm.sgbd.AbstractSgbd.createIndex (String entityName, String fieldName) [pure virtual]
Sert à ajouter un index dans la table SQL de l'entité pour un field en particulier.
Parameters:
entityName nom de l'entité
fieldName nom du field
Implemented in newtonERP.orm.sgbd.sqlite.SgbdSqlite.
Referenced by newtonERP.orm.Orm.createIndex().
abstract void newtonERP.orm.sgbd.AbstractSgbd.createTableForEntity (AbstractOrmEntity entity) [pure virtual]
Créer une table pour un type d'entité.
Parameters:
entity entité
Implemented in newtonERP.orm.sgbd.sqlite.SgbdSqlite.
abstract void newtonERP.orm.sgbd.AbstractSgbd.delete (AbstractOrmEntity searchEntity, Vector< String > searchCriterias) [pure virtual]
Method used to delete an entity from the database.
Parameters:
searchEntity the entity to be researched
searchCriterias the search criterias for the where clause
Implemented in newtonERP.orm.sgbd.sqlite.SgbdSqlite.
Referenced by newtonERP.orm.Orm.delete().
abstract void newtonERP.orm.sgbd.AbstractSgbd.delete (Vector< AbstractOrmEntity > searchEntities) [pure virtual]
Uses the new where builder.
Method used to delete an entity from the database
Parameters:
searchEntities the entities from which we will build our where clause
Implemented in newtonERP.orm.sgbd.sqlite.SgbdSqlite.
abstract void newtonERP.orm.sgbd.AbstractSgbd.disconnect () [pure virtual]
Method used to disconnect from the database.
Implemented in newtonERP.orm.sgbd.sqlite.SgbdSqlite.
Referenced by newtonERP.orm.Orm.disconnect().
abstract ResultSet newtonERP.orm.sgbd.AbstractSgbd.execute (String request, OrmActions action) [pure virtual]
Method that executes the sql query passed in paramter plus de action from the OrmAction.
Parameters:
request l'action a effectue
action the OrmActions that will be done
Returns:
le resultat sous forme d'un result set
Implemented in newtonERP.orm.sgbd.sqlite.SgbdSqlite.
Referenced by newtonERP.orm.Orm.executeCustomQuery().
abstract long newtonERP.orm.sgbd.AbstractSgbd.getLatestBackupTime () [pure virtual]
Returns:
timestamp en ms où le dernier backup à été fait
Implemented in newtonERP.orm.sgbd.sqlite.SgbdSqlite.
Referenced by newtonERP.orm.OrmFonction.doBackupIfTimeIntervalAllows().
abstract int newtonERP.orm.sgbd.AbstractSgbd.insert (AbstractOrmEntity newEntity) [pure virtual]
Method used to insert an entity in the database based into the entity passed in parameter.
Parameters:
newEntity the entity to add
Returns:
le id de clé primaire ajoutée
Implemented in newtonERP.orm.sgbd.sqlite.SgbdSqlite.
Referenced by newtonERP.orm.Orm.insert().
abstract boolean newtonERP.orm.sgbd.AbstractSgbd.isEntityExists (String entitySystemName) [pure virtual]
Parameters:
entitySystemName nom système d'une entité
Returns:
true si l'entité a une table dans la base de donnée, sinon false
Implemented in newtonERP.orm.sgbd.sqlite.SgbdSqlite.
Referenced by newtonERP.orm.Orm.isEntityExists().
abstract ResultSet newtonERP.orm.sgbd.AbstractSgbd.select (AbstractOrmEntity searchEntity, Vector< String > searchCriteriasParam) [pure virtual]
Use only for complex queries.
Use the select that takes only a vector of entities instead
Method used to do search queries done from the views to the databse. The search criterias that has been passed in parameter are a list of string that has been generated by the view modules
Parameters:
searchEntity the entity that has to be researched
searchCriteriasParam the search criterias formatted into strings
Returns:
a vector of ormizable entities
Implemented in newtonERP.orm.sgbd.sqlite.SgbdSqlite.
abstract ResultSet newtonERP.orm.sgbd.AbstractSgbd.select (Vector< AbstractOrmEntity > searchEntities) [pure virtual]
Uses the new where builder.
Method used to do search queries done from the views to the databse. The search criterias that has been passed in parameter are a list of string that has been generated by the view modules todo: correct doc
Parameters:
searchEntities the entities from which we will perform the search
Returns:
the entities
Implemented in newtonERP.orm.sgbd.sqlite.SgbdSqlite.
abstract ResultSet newtonERP.orm.sgbd.AbstractSgbd.select (AbstractOrmEntity searchEntity, Vector< String > searchCriteriasParam, int limit, int offset, String orderBy) [pure virtual]
Use only for complex queries.
Use the select that takes only a vector of entities instead
Method used to do search queries done from the views to the databse. The search criterias that has been passed in parameter are a list of string that has been generated by the view modules
Parameters:
searchEntity the entity that has to be researched
searchCriteriasParam the search criterias formatted into strings
limit limite de résultat
offset offset du début des résultats
orderBy ordre facultatif
Returns:
a vector of ormizable entities
Implemented in newtonERP.orm.sgbd.sqlite.SgbdSqlite.
abstract void newtonERP.orm.sgbd.AbstractSgbd.update (AbstractOrmEntity entityContainingChanges, Vector< String > searchCriterias) [pure virtual]
Method used to update / change an entity.
Parameters:
entityContainingChanges the entity that has been changed and will be in the orm
searchCriterias the criterias used by the update
Implemented in newtonERP.orm.sgbd.sqlite.SgbdSqlite.
Referenced by newtonERP.orm.Orm.update().
abstract void newtonERP.orm.sgbd.AbstractSgbd.update (Vector< AbstractOrmEntity > searchEntities, AbstractOrmEntity entityContainingChanges) [pure virtual]
Uses the new where builder.
Method used to update / change an entity
Parameters:
searchEntities the entities from which we will build our where clause
entityContainingChanges the changes to apply
Implemented in newtonERP.orm.sgbd.sqlite.SgbdSqlite.
abstract void newtonERP.orm.sgbd.AbstractSgbd.updateUnique (AbstractOrmEntity searchEntity, AbstractOrmEntity entityContainingChanges) [pure virtual]
Uses the new where builder.
Method used to update / change an entity
Parameters:
searchEntity the entities from which we will build our where clause
entityContainingChanges the changes to apply
Implemented in newtonERP.orm.sgbd.sqlite.SgbdSqlite.
Referenced by newtonERP.orm.Orm.updateUnique().
The documentation for this class was generated from the following file:
src/newtonERP/orm/sgbd/AbstractSgbd.java