Bee ERP: newtonERP.viewers.secondStep.PageSelectorViewer Class Reference
newtonERP.viewers.secondStep.PageSelectorViewer Class Reference
Sert à voir les liste de pages.
Static Public Member Functions
static String getHtmlCode (PageSelector pageSelector)
Detailed Description
Sert à voir les liste de pages.
Author:
Guillaume Lacasse
Definition at line 13 of file PageSelectorViewer.java.
Member Function Documentation
static String newtonERP.viewers.secondStep.PageSelectorViewer.getHtmlCode (PageSelector pageSelector) [static]
Parameters:
pageSelector selecteur de page
Returns:
code html
Definition at line 20 of file PageSelectorViewer.java.
References newtonERP.viewers.viewerData.PageSelector.getCurrentLimit(), newtonERP.viewers.viewerData.PageSelector.getCurrentOffset(), newtonERP.viewers.viewerData.PageSelector.getCurrentSearchEntry(), newtonERP.viewers.viewerData.PageSelector.getCurrentUrl(), newtonERP.viewers.viewerData.PageSelector.getOrderBy(), newtonERP.viewers.viewerData.PageSelector.getPageCount(), and newtonERP.viewers.viewerData.PageSelector.getTotalRowCount().
The documentation for this class was generated from the following file:
src/newtonERP/viewers/secondStep/PageSelectorViewer.java