Bee ERP: newtonERP.viewers.viewerData.PageSelector Class Reference
newtonERP.viewers.viewerData.PageSelector Class Reference
Modèle d'un selecteur de page.
Inherits newtonERP::module::AbstractEntity.
Public Member Functions
PageSelector (int limit, int offset, int totalRowCount, String currentUrl, String currentSearchEntry, String orderBy)
int getPageCount ()
int getCurrentLimit ()
String getCurrentUrl ()
int getCurrentOffset ()
int getTotalRowCount ()
String getCurrentSearchEntry ()
String getOrderBy ()
Detailed Description
Modèle d'un selecteur de page.
Author:
Guillaume
Definition at line 9 of file PageSelector.java.
Constructor & Destructor Documentation
newtonERP.viewers.viewerData.PageSelector.PageSelector (int limit, int offset, int totalRowCount, String currentUrl, String currentSearchEntry, String orderBy)
Parameters:
limit limite
offset offset
totalRowCount nonbre total de rangée
currentUrl url courant
currentSearchEntry texte de recherche
orderBy ordre de tri
rowPerPage row per page
pageCount page count
Definition at line 39 of file PageSelector.java.
Member Function Documentation
int newtonERP.viewers.viewerData.PageSelector.getCurrentLimit ()
Returns:
nombre maximum de rangée par page
Definition at line 70 of file PageSelector.java.
Referenced by newtonERP.viewers.secondStep.PageSelectorViewer.getHtmlCode().
int newtonERP.viewers.viewerData.PageSelector.getCurrentOffset ()
Returns:
offset
Definition at line 86 of file PageSelector.java.
Referenced by newtonERP.viewers.secondStep.PageSelectorViewer.getHtmlCode().
String newtonERP.viewers.viewerData.PageSelector.getCurrentSearchEntry ()
Returns:
recherche courante
Definition at line 102 of file PageSelector.java.
Referenced by newtonERP.viewers.secondStep.PageSelectorViewer.getHtmlCode().
String newtonERP.viewers.viewerData.PageSelector.getCurrentUrl ()
Returns:
url
Definition at line 78 of file PageSelector.java.
Referenced by newtonERP.viewers.secondStep.PageSelectorViewer.getHtmlCode().
String newtonERP.viewers.viewerData.PageSelector.getOrderBy ()
Returns:
ordre de tri
Definition at line 110 of file PageSelector.java.
Referenced by newtonERP.viewers.secondStep.PageSelectorViewer.getHtmlCode().
int newtonERP.viewers.viewerData.PageSelector.getPageCount ()
Returns:
nombre de pages
Definition at line 62 of file PageSelector.java.
Referenced by newtonERP.viewers.secondStep.PageSelectorViewer.getHtmlCode().
int newtonERP.viewers.viewerData.PageSelector.getTotalRowCount ()
Returns:
nombre total de rangée
Definition at line 94 of file PageSelector.java.
Referenced by newtonERP.viewers.secondStep.PageSelectorViewer.getHtmlCode().
The documentation for this class was generated from the following file:
src/newtonERP/viewers/viewerData/PageSelector.java