Bee ERP: newtonERP.common.ActionLink Class Reference
newtonERP.common.ActionLink Class Reference
class englobant une action et tout les composants néscéssaire pour l'executer
Inherited by newtonERP.viewers.viewerData.GridCaseData.
Public Member Functions
ActionLink ()
constructeur vide
ActionLink (AbstractAction action)
ActionLink (String name, AbstractAction action)
ActionLink (String name, AbstractAction action, Hashtable< String, String > parameters)
String getName ()
void setName (String name)
AbstractAction getAction ()
void setAction (AbstractAction action)
Hashtable< String, String > getParameters ()
Hashtable< String, String > getParameters (AbstractEntity entity)
void setParameters (Hashtable< String, String > parameters)
void addParameters (String field, String value)
String getUrl ()
String getParam (AbstractEntity entity)
String getUrlParam (AbstractEntity entity)
String getUrlParam ()
boolean isConfirm ()
void setConfirm (boolean confirm)
boolean equals (Object obj)
String toString ()
Detailed Description
class englobant une action et tout les composants néscéssaire pour l'executer
Author:
CloutierJo
Definition at line 13 of file ActionLink.java.
Constructor & Destructor Documentation
newtonERP.common.ActionLink.ActionLink (AbstractAction action)
Parameters:
action action a effectuer
Definition at line 31 of file ActionLink.java.
newtonERP.common.ActionLink.ActionLink (String name, AbstractAction action)
Parameters:
name nom a afficher
action action a effectuer
Definition at line 40 of file ActionLink.java.
newtonERP.common.ActionLink.ActionLink (String name, AbstractAction action, Hashtable< String, String > parameters)
Parameters:
name nom a afficher
action action a effectuer
parameters parametre de lien
Definition at line 51 of file ActionLink.java.
Member Function Documentation
void newtonERP.common.ActionLink.addParameters (String field, String value)
Parameters:
field nom du champ a ajouter
value valeur du champ a ajouter
parameters ajoute le parametre a la liste de parametre
Definition at line 132 of file ActionLink.java.
Referenced by newtonERP.module.AbstractOrmEntity.getList().
AbstractAction newtonERP.common.ActionLink.getAction ()
Returns:
the action
Definition at line 81 of file ActionLink.java.
Referenced by newtonERP.viewers.viewerData.GridCaseData.getActionLink(), and modules.userRightModule.UserRightModule.isPermissionAllowed().
String newtonERP.common.ActionLink.getName ()
Returns:
the name
Definition at line 65 of file ActionLink.java.
Referenced by newtonERP.viewers.secondStep.LinkViewer.getHtmlCode(), newtonERP.viewers.secondStep.ButtonLinkViewer.getHtmlCode(), newtonERP.viewers.firstStep.PromptViewer.getHtmlCode(), newtonERP.viewers.viewerData.BaseViewerData.removeGlobalActions(), and newtonERP.viewers.viewerData.GridViewerData.removeSpecificActions().
String newtonERP.common.ActionLink.getParam (AbstractEntity entity)
Parameters:
entity entity servant a definir les parametre dynamique
Returns:
les parametre sous la forme key=value&key2=value2... (ne contien pas le '?')
Definition at line 150 of file ActionLink.java.
References newtonERP.common.ActionLink.getParameters().
Referenced by newtonERP.common.ActionLink.getUrlParam().
Hashtable<String, String> newtonERP.common.ActionLink.getParameters ()
Returns:
the parameters
Definition at line 97 of file ActionLink.java.
Referenced by newtonERP.viewers.secondStep.ButtonLinkViewer.getHtmlCode(), and newtonERP.common.ActionLink.getParam().
Hashtable<String, String> newtonERP.common.ActionLink.getParameters (AbstractEntity entity)
Parameters:
entity entity servant a compile les parametre
Returns:
les parametre compile
Definition at line 106 of file ActionLink.java.
References newtonERP.module.AbstractEntity.getDataString().
String newtonERP.common.ActionLink.getUrl ()
Returns:
l'url relatif
Definition at line 140 of file ActionLink.java.
Referenced by newtonERP.viewers.secondStep.ButtonLinkViewer.getHtmlCode(), and newtonERP.common.ActionLink.getUrlParam().
String newtonERP.common.ActionLink.getUrlParam (AbstractEntity entity)
Parameters:
entity entity servant a definir les parametre dynamique
Returns:
l'url relatif et suivie des parametre, utilisabe directement dans un lien web
Definition at line 170 of file ActionLink.java.
References newtonERP.common.ActionLink.getParam(), and newtonERP.common.ActionLink.getUrl().
Referenced by newtonERP.viewers.secondStep.LinkViewer.getHtmlCode(), and newtonERP.viewers.firstStep.PromptViewer.getHtmlCode().
String newtonERP.common.ActionLink.getUrlParam ()
Returns:
l'url relatif et suivie des parametre, utilisabe directement dans un lien web
Definition at line 179 of file ActionLink.java.
boolean newtonERP.common.ActionLink.isConfirm ()
Returns:
the confirm
Definition at line 187 of file ActionLink.java.
Referenced by newtonERP.viewers.secondStep.ButtonLinkViewer.getHtmlCode().
void newtonERP.common.ActionLink.setAction (AbstractAction action)
Parameters:
action the action to set
Definition at line 89 of file ActionLink.java.
void newtonERP.common.ActionLink.setConfirm (boolean confirm)
Parameters:
confirm the confirm to set
Definition at line 195 of file ActionLink.java.
Referenced by newtonERP.module.AbstractOrmEntity.getList().
void newtonERP.common.ActionLink.setName (String name)
Parameters:
name the name to set
Definition at line 73 of file ActionLink.java.
void newtonERP.common.ActionLink.setParameters (Hashtable< String, String > parameters)
Parameters:
parameters the parameters to set
Definition at line 122 of file ActionLink.java.
The documentation for this class was generated from the following file:
src/newtonERP/common/ActionLink.java