Bee ERP: newtonERP.viewers.secondStep.SearchBarViewer Class Reference
newtonERP.viewers.secondStep.SearchBarViewer Class Reference
Ser à voir les barres de recherche.
Static Public Member Functions
static String getHtmlCode (SearchBar searchBar)
Detailed Description
Ser à voir les barres de recherche.
Author:
Guillaume Lacasse
Definition at line 9 of file SearchBarViewer.java.
Member Function Documentation
static String newtonERP.viewers.secondStep.SearchBarViewer.getHtmlCode (SearchBar searchBar) [static]
Parameters:
searchBar barre de recherche
Returns:
code html
Definition at line 15 of file SearchBarViewer.java.
References newtonERP.viewers.viewerData.SearchBar.getCurrentOrder(), newtonERP.viewers.viewerData.SearchBar.getCurrentSearchEntry(), newtonERP.viewers.viewerData.SearchBar.getLimit(), newtonERP.viewers.viewerData.SearchBar.getOffset(), newtonERP.viewers.viewerData.SearchBar.getPossibleOrderNameList(), and newtonERP.viewers.viewerData.SearchBar.getTargetUrl().
The documentation for this class was generated from the following file:
src/newtonERP/viewers/secondStep/SearchBarViewer.java