Bee ERP: newtonERP.serveur.ConfigManager Class Reference
newtonERP.serveur.ConfigManager Class Reference
manage de config of the software from an XML file
Static Public Member Functions
static String loadStringProperty (String propertyName, String attributName, String defaultValue)
static String loadStringProperty (String propertyName, String defaultValue)
static String loadStringAttrProperty (String propertyName, String attributName)
static String loadStringProperty (String propertyName)
static int loadIntProperty (String propertyName, String attributName, Integer defaultValue)
static int loadIntProperty (String propertyName, Integer defaultValue)
static int loadIntAttrProperty (String propertyName, String attributName)
static int loadIntProperty (String propertyName)
static boolean loadBoolProperty (String propertyName, String attributName, Boolean defaultValue)
static boolean loadBoolProperty (String propertyName, Boolean defaultValue)
static boolean loadBoolAttrProperty (String propertyName, String attributName)
static boolean loadBoolProperty (String propertyName)
Detailed Description
manage de config of the software from an XML file
Author:
Guillaume Lacasse JoCloutier
Definition at line 19 of file ConfigManager.java.
Member Function Documentation
static boolean newtonERP.serveur.ConfigManager.loadBoolAttrProperty (String propertyName, String attributName) [static]
Parameters:
propertyName the propetry name
attributName the attribut name
Returns:
boolean property value
Definition at line 204 of file ConfigManager.java.
References newtonERP.serveur.ConfigManager.loadBoolProperty().
static boolean newtonERP.serveur.ConfigManager.loadBoolProperty (String propertyName, String attributName, Boolean defaultValue) [static]
Parameters:
propertyName the propetry name
attributName the attribut name
defaultValue a default value in case the property is'nt present in the config file
Returns:
boolean property value
Definition at line 180 of file ConfigManager.java.
References newtonERP.serveur.ConfigManager.loadStringProperty().
Referenced by newtonERP.serveur.ConfigManager.loadBoolAttrProperty(), and newtonERP.serveur.ConfigManager.loadBoolProperty().
static boolean newtonERP.serveur.ConfigManager.loadBoolProperty (String propertyName, Boolean defaultValue) [static]
Parameters:
propertyName the propetry name
defaultValue a default value in case the property is'nt present in the config file
Returns:
boolean property value
Definition at line 193 of file ConfigManager.java.
References newtonERP.serveur.ConfigManager.loadBoolProperty().
static boolean newtonERP.serveur.ConfigManager.loadBoolProperty (String propertyName) [static]
Parameters:
propertyName the propetry name
Returns:
boolean property value
Definition at line 214 of file ConfigManager.java.
References newtonERP.serveur.ConfigManager.loadBoolProperty().
static int newtonERP.serveur.ConfigManager.loadIntAttrProperty (String propertyName, String attributName) [static]
Parameters:
propertyName the propetry name
attributName the attribut name
Returns:
int property value
Definition at line 158 of file ConfigManager.java.
References newtonERP.serveur.ConfigManager.loadIntProperty().
static int newtonERP.serveur.ConfigManager.loadIntProperty (String propertyName) [static]
Parameters:
propertyName the propetry name
Returns:
int property value
Definition at line 168 of file ConfigManager.java.
References newtonERP.serveur.ConfigManager.loadIntProperty().
static int newtonERP.serveur.ConfigManager.loadIntProperty (String propertyName, Integer defaultValue) [static]
Parameters:
propertyName the propetry name
Returns:
int property value
Parameters:
defaultValue a default value in case the property is'nt present in the config file
Definition at line 147 of file ConfigManager.java.
References newtonERP.serveur.ConfigManager.loadIntProperty().
static int newtonERP.serveur.ConfigManager.loadIntProperty (String propertyName, String attributName, Integer defaultValue) [static]
Parameters:
propertyName the propetry name
attributName the attribut name
Returns:
int property value
Parameters:
defaultValue a default value in case the property is'nt present in the config file
Definition at line 134 of file ConfigManager.java.
References newtonERP.serveur.ConfigManager.loadStringProperty().
Referenced by newtonERP.serveur.ConfigManager.loadIntAttrProperty(), and newtonERP.serveur.ConfigManager.loadIntProperty().
static String newtonERP.serveur.ConfigManager.loadStringAttrProperty (String propertyName, String attributName) [static]
Parameters:
propertyName the propetry name
attributName the attribut name
Returns:
String property value
Definition at line 112 of file ConfigManager.java.
References newtonERP.serveur.ConfigManager.loadStringProperty().
static String newtonERP.serveur.ConfigManager.loadStringProperty (String propertyName) [static]
Parameters:
propertyName the propetry name
Returns:
String property value
Definition at line 122 of file ConfigManager.java.
References newtonERP.serveur.ConfigManager.loadStringProperty().
static String newtonERP.serveur.ConfigManager.loadStringProperty (String propertyName, String defaultValue) [static]
Parameters:
propertyName the propetry name
defaultValue a default value in case the property is'nt present in the config file
Returns:
String property value
Definition at line 101 of file ConfigManager.java.
References newtonERP.serveur.ConfigManager.loadStringProperty().
static String newtonERP.serveur.ConfigManager.loadStringProperty (String propertyName, String attributName, String defaultValue) [static]
Parameters:
propertyName the property name
attributName the attribut name
defaultValue a default value in case the property is'nt present in the config file
Returns:
String property value
Definition at line 53 of file ConfigManager.java.
Referenced by newtonERP.serveur.ConfigManager.loadBoolProperty(), newtonERP.serveur.ConfigManager.loadIntProperty(), newtonERP.serveur.ConfigManager.loadStringAttrProperty(), and newtonERP.serveur.ConfigManager.loadStringProperty().
The documentation for this class was generated from the following file:
src/newtonERP/serveur/ConfigManager.java