Bee ERP: newtonERP.viewers.secondStep.ButtonLinkViewer Class Reference
newtonERP.viewers.secondStep.ButtonLinkViewer Class Reference
Sert à formatter de l'argent.
Static Public Member Functions
static String getHtmlCode (ActionLink actionLink, AbstractEntity entity)
static String getHtmlCode (ActionLink actionLink)
Detailed Description
Sert à formatter de l'argent.
Author:
Guillaume
Definition at line 16 of file ButtonLinkViewer.java.
Member Function Documentation
static String newtonERP.viewers.secondStep.ButtonLinkViewer.getHtmlCode (ActionLink actionLink, AbstractEntity entity) [static]
Parameters:
actionLink representation du lien a effectuer
entity entity d'ou tiré les parametre, peu etre null
Returns:
bouton de lien
Definition at line 24 of file ButtonLinkViewer.java.
References newtonERP.common.ActionLink.getName(), newtonERP.common.ActionLink.getParameters(), newtonERP.module.AbstractEntity.getSystemName(), newtonERP.common.ActionLink.getUrl(), and newtonERP.common.ActionLink.isConfirm().
Referenced by newtonERP.viewers.secondStep.ButtonLinkViewer.getHtmlCode().
static String newtonERP.viewers.secondStep.ButtonLinkViewer.getHtmlCode (ActionLink actionLink) [static]
Parameters:
actionLink representation du lien a effectuer
Returns:
bouton de lien
Definition at line 96 of file ButtonLinkViewer.java.
References newtonERP.viewers.secondStep.ButtonLinkViewer.getHtmlCode().
The documentation for this class was generated from the following file:
src/newtonERP/viewers/secondStep/ButtonLinkViewer.java