Bee ERP: newtonERP.viewers.viewerData.SearchBar Class Reference
newtonERP.viewers.viewerData.SearchBar Class Reference
Modele d'une barre de recherche.
Inherits newtonERP::module::AbstractEntity.
Public Member Functions
SearchBar (String targetUrl, String currentSearchEntry, AbstractOrmEntity concernedEntity, String currentOrder, int limit, int offset)
String getTargetUrl ()
String getCurrentSearchEntry ()
Vector< String > getPossibleOrderNameList ()
String getCurrentOrder ()
int getOffset ()
int getLimit ()
Detailed Description
Modele d'une barre de recherche.
Author:
Guillaume Lacasse
Definition at line 13 of file SearchBar.java.
Constructor & Destructor Documentation
newtonERP.viewers.viewerData.SearchBar.SearchBar (String targetUrl, String currentSearchEntry, AbstractOrmEntity concernedEntity, String currentOrder, int limit, int offset)
Parameters:
targetUrl url de destination de la recherche
currentSearchEntry contenu textuel courant de la rercherche
concernedEntity entité concernée par la recherche
currentOrder ordre actuel
limit limite de recherche
offset offset de recherche
Definition at line 30 of file SearchBar.java.
Member Function Documentation
String newtonERP.viewers.viewerData.SearchBar.getCurrentOrder ()
Returns:
ordre actuel
Definition at line 84 of file SearchBar.java.
Referenced by newtonERP.viewers.secondStep.SearchBarViewer.getHtmlCode().
String newtonERP.viewers.viewerData.SearchBar.getCurrentSearchEntry ()
Returns:
contenu textuel courant de la rercherche
Definition at line 54 of file SearchBar.java.
Referenced by newtonERP.viewers.secondStep.SearchBarViewer.getHtmlCode().
int newtonERP.viewers.viewerData.SearchBar.getLimit ()
Returns:
search limit
Definition at line 100 of file SearchBar.java.
Referenced by newtonERP.viewers.secondStep.SearchBarViewer.getHtmlCode().
int newtonERP.viewers.viewerData.SearchBar.getOffset ()
Returns:
search offset
Definition at line 92 of file SearchBar.java.
Referenced by newtonERP.viewers.secondStep.SearchBarViewer.getHtmlCode().
Vector<String> newtonERP.viewers.viewerData.SearchBar.getPossibleOrderNameList ()
Returns:
liste des ordres possibles
Definition at line 62 of file SearchBar.java.
Referenced by newtonERP.viewers.secondStep.SearchBarViewer.getHtmlCode().
String newtonERP.viewers.viewerData.SearchBar.getTargetUrl ()
Returns:
Url de destination de la recherche
Definition at line 46 of file SearchBar.java.
Referenced by newtonERP.viewers.secondStep.SearchBarViewer.getHtmlCode().
The documentation for this class was generated from the following file:
src/newtonERP/viewers/viewerData/SearchBar.java