Bee ERP: newtonERP.module.AbstractOrmEntity Class Reference
newtonERP.module.AbstractOrmEntity Class Reference
Inherits newtonERP::module::AbstractEntity.
Inherited by modules.common.entityDefinitions.Address, modules.common.entityDefinitions.Country, modules.common.entityDefinitions.State, modules.taskModule.entityDefinitions.AccessorEntity, modules.taskModule.entityDefinitions.ActionEntity, modules.taskModule.entityDefinitions.EffectEntity, modules.taskModule.entityDefinitions.EffectEntityParameter, modules.taskModule.entityDefinitions.EntityEntity, modules.taskModule.entityDefinitions.FieldEntity, modules.taskModule.entityDefinitions.FieldTypeEntity, modules.taskModule.entityDefinitions.ModuleEntity, modules.taskModule.entityDefinitions.Parameter, modules.taskModule.entityDefinitions.SearchCriteria, modules.taskModule.entityDefinitions.SearchCriteriaOperator, modules.taskModule.entityDefinitions.SearchEntity, modules.taskModule.entityDefinitions.Specification, modules.taskModule.entityDefinitions.TaskEntity, modules.userRightModule.entityDefinitions.Groups, modules.userRightModule.entityDefinitions.GroupsRight, modules.userRightModule.entityDefinitions.Right, and modules.userRightModule.entityDefinitions.User.
Public Member Functions
abstract Fields initFields ()
initialise les champ de l'entity, doit etre overider si l'entity contient des champs, sinon initialise une liste de champ vide
final void setOrmizableData (Hashtable< String, Object > parameters)
AbstractEntity newUI (Hashtable< String, String > parameters)
BaseAction New.
final AbstractOrmEntity newE ()
enregistre l'entity en DB
AbstractEntity deleteUI (Hashtable< String, String > parameters)
BaseAction Delete.
final void delete (String whereClause)
supprime l'entity en DB
final void delete ()
supprime l'entity en DB, la clause where est definie par this
final void delete (AbstractOrmEntity whereClause)
supprime l'entity en DB corespondant au whereClause
final void delete (Vector< AbstractOrmEntity > whereClause)
supprime l'entity en DB corespondant aux whereClauses en utilisant le whereBuilder
BaseViewerData editUI (Hashtable< String, String > parameters)
BaseAction Edit.
BaseViewerData editUI (Hashtable< String, String > parameters, boolean isReadOnly)
BaseAction Edit.
final void edit (String whereClause)
met a jour l'entity en DB, l'ID doit etre présent
final void edit (AbstractOrmEntity changeToApply)
met a jour l'entity en DB, l'ID doit etre présent, le whereclause correspond a this
final void edit (AbstractOrmEntity whereClause, AbstractOrmEntity changeToApply)
met a jour l'entity en DB, l'ID doit etre présent
final void edit (Vector< AbstractOrmEntity > whereClause, AbstractOrmEntity changeToApply)
met a jour l'entity en DB, l'ID doit etre présent
AbstractEntity getUI (Hashtable< String, String > parameters)
BaseAction Get.
final ListViewerData getList ()
ListViewerData getList (Hashtable< String, String > parameters)
int getItemLimitListPerPage ()
Module getCurrentModule ()
final Vector< AbstractOrmEntity > get (String whereClause)
trouve l'entity selon les critere disponible, retourne le premier trouve
final Vector< AbstractOrmEntity > get ()
fais un get sur un criter simple exprimé par l'entity this
final Vector< AbstractOrmEntity > get (AbstractOrmEntity entity)
final Vector< AbstractOrmEntity > get (Vector< AbstractOrmEntity > entities)
final String getPrimaryKeyName ()
String getForeignKeyName ()
final Integer getPrimaryKeyValue ()
String getButtonCaption ()
Implémentation par default.
final String getVisibleName ()
final Hashtable< String, FlagPool > getPositiveFlagPoolList ()
Vector< String > getNaturalKeyNameList ()
String getNaturalKeyDescription ()
String getNaturalKeyName ()
final void setVisibleName (String visibleName)
final TreeMap< String,
PluralAccessor > getPluralAccessorList ()
final TreeMap< String,
AbstractOrmEntity > getSingleAccessorList ()
final AbstractOrmEntity getSingleAccessor (String accessorName)
String getInputValue (String inputName)
void addPositiveFlagPool (String visibleDescription, FlagPool flagPool)
void addNegativeFlagPool (String visibleDescription, FlagPool flagPool)
Hashtable< String, FlagPool > getNegativeFlagPoolList ()
PluralAccessor getPluralAccessor (String accessorName)
PluralAccessor getPluralAccessor (String accessorName, AbstractOrmEntity searchCriteriaEntity)
void assign (AbstractOrmEntity foreignEntity)
void save ()
Vector< String > getAccessorNameList ()
Vector< GateWay > getGateWayList ()
Detailed Description
Author:
cloutierJo
Definition at line 31 of file AbstractOrmEntity.java.
Member Function Documentation
void newtonERP.module.AbstractOrmEntity.addNegativeFlagPool (String visibleDescription, FlagPool flagPool)
Parameters:
visibleDescription description du flag pool
flagPool flag pool
Definition at line 749 of file AbstractOrmEntity.java.
References newtonERP.module.AbstractOrmEntity.getNegativeFlagPoolList().
void newtonERP.module.AbstractOrmEntity.addPositiveFlagPool (String visibleDescription, FlagPool flagPool)
Parameters:
visibleDescription description visible du flagPool
flagPool le flag pool
Definition at line 740 of file AbstractOrmEntity.java.
References newtonERP.module.AbstractOrmEntity.getPositiveFlagPoolList().
void newtonERP.module.AbstractOrmEntity.assign (AbstractOrmEntity foreignEntity)
Parameters:
foreignEntity entité étrangère
Definition at line 819 of file AbstractOrmEntity.java.
References newtonERP.orm.field.Fields.containsFieldName(), newtonERP.module.AbstractEntity.getFields(), newtonERP.module.AbstractOrmEntity.getForeignKeyName(), newtonERP.module.AbstractOrmEntity.getNaturalKeyName(), newtonERP.module.AbstractOrmEntity.getPrimaryKeyValue(), and newtonERP.module.AbstractEntity.setData().
Referenced by modules.taskModule.entityDefinitions.EntityEntity.ContainsPrimaryKeyField().
final void newtonERP.module.AbstractOrmEntity.delete (AbstractOrmEntity whereClause)
supprime l'entity en DB corespondant au whereClause
Parameters:
whereClause the where clause for the query
Definition at line 135 of file AbstractOrmEntity.java.
final void newtonERP.module.AbstractOrmEntity.delete (Vector< AbstractOrmEntity > whereClause)
supprime l'entity en DB corespondant aux whereClauses en utilisant le whereBuilder
Parameters:
whereClause the where clause for the query
See also:
Definition at line 150 of file AbstractOrmEntity.java.
final void newtonERP.module.AbstractOrmEntity.delete (String whereClause)
supprime l'entity en DB
Parameters:
whereClause the where clause for the query
Definition at line 113 of file AbstractOrmEntity.java.
final void newtonERP.module.AbstractOrmEntity.delete ()
supprime l'entity en DB, la clause where est definie par this
Definition at line 124 of file AbstractOrmEntity.java.
AbstractEntity newtonERP.module.AbstractOrmEntity.deleteUI (Hashtable< String, String > parameters)
BaseAction Delete.
Parameters:
parameters parametre suplementaire
Returns:
todo: qu'Est-ce que l'on devrai retourné en general?
Reimplemented in modules.taskModule.entityDefinitions.ActionEntity, modules.taskModule.entityDefinitions.EntityEntity, modules.taskModule.entityDefinitions.FieldEntity, modules.taskModule.entityDefinitions.SearchCriteriaOperator, and modules.userRightModule.entityDefinitions.Right.
Definition at line 97 of file AbstractOrmEntity.java.
References newtonERP.module.AbstractEntity.getDataString(), newtonERP.module.AbstractOrmEntity.getList(), and newtonERP.module.AbstractOrmEntity.getPrimaryKeyName().
Referenced by newtonERP.module.Module.doAction().
final void newtonERP.module.AbstractOrmEntity.edit (String whereClause)
met a jour l'entity en DB, l'ID doit etre présent
Parameters:
whereClause the where clause for the query
Definition at line 258 of file AbstractOrmEntity.java.
Referenced by newtonERP.module.AbstractOrmEntity.edit(), and newtonERP.module.AbstractOrmEntity.editUI().
final void newtonERP.module.AbstractOrmEntity.edit (AbstractOrmEntity changeToApply)
met a jour l'entity en DB, l'ID doit etre présent, le whereclause correspond a this
Parameters:
whereClause the where clause for the query
changeToApply the chang to apply to entity matching the where clause
Definition at line 273 of file AbstractOrmEntity.java.
References newtonERP.module.AbstractOrmEntity.edit().
final void newtonERP.module.AbstractOrmEntity.edit (AbstractOrmEntity whereClause, AbstractOrmEntity changeToApply)
met a jour l'entity en DB, l'ID doit etre présent
Parameters:
whereClause the where clause for the query
changeToApply the chang to apply to entity matching the where clause
Definition at line 285 of file AbstractOrmEntity.java.
References newtonERP.module.AbstractOrmEntity.edit().
final void newtonERP.module.AbstractOrmEntity.edit (Vector< AbstractOrmEntity > whereClause, AbstractOrmEntity changeToApply)
met a jour l'entity en DB, l'ID doit etre présent
Parameters:
whereClause the where clause for the query
changeToApply the chang to apply to entity matching the where clause
Definition at line 300 of file AbstractOrmEntity.java.
BaseViewerData newtonERP.module.AbstractOrmEntity.editUI (Hashtable< String, String > parameters)
BaseAction Edit.
Parameters:
parameters parametre suplementaire
Returns:
todo: qu'Est-ce que l'on devrai retourné en general?
Reimplemented in modules.taskModule.entityDefinitions.SearchCriteriaOperator, and modules.userRightModule.entityDefinitions.Right.
Definition at line 162 of file AbstractOrmEntity.java.
Referenced by modules.taskModule.entityDefinitions.FieldEntity.deleteUI(), newtonERP.module.Module.doAction(), modules.taskModule.actions.GenerateSourceCode.doAction(), modules.taskModule.actions.GenerateEntityCode.doAction(), modules.taskModule.actions.GenerateActionCode.doAction(), modules.taskModule.actions.AddFieldToOrm.doAction(), newtonERP.module.AbstractOrmEntity.editUI(), newtonERP.module.AbstractOrmEntity.getUI(), newtonERP.module.AbstractOrmEntity.newUI(), and modules.taskModule.entityDefinitions.FieldEntity.newUI().
BaseViewerData newtonERP.module.AbstractOrmEntity.editUI (Hashtable< String, String > parameters, boolean isReadOnly)
BaseAction Edit.
Parameters:
parameters parametre suplementaire
isReadOnly si on est en mode readOnly: true, sinon, false (default: false)
Returns:
todo: qu'Est-ce que l'on devrai retourné en general?
Definition at line 176 of file AbstractOrmEntity.java.
References newtonERP.viewers.viewerData.BaseViewerData.addAlertMessage(), newtonERP.viewers.viewerData.BaseViewerData.addNormalMessage(), newtonERP.module.AbstractOrmEntity.edit(), newtonERP.module.AbstractOrmEntity.editUI(), newtonERP.module.AbstractOrmEntity.get(), newtonERP.module.AbstractEntity.getData(), newtonERP.module.AbstractEntity.getFields(), newtonERP.module.AbstractOrmEntity.getPositiveFlagPoolList(), newtonERP.module.AbstractOrmEntity.getPrimaryKeyName(), newtonERP.module.AbstractOrmEntity.getPrimaryKeyValue(), newtonERP.module.AbstractOrmEntity.getVisibleName(), newtonERP.orm.field.Fields.isErrorState(), newtonERP.module.AbstractOrmEntity.newE(), newtonERP.viewers.viewerData.BaseViewerData.setBackLink(), newtonERP.viewers.viewerData.PromptViewerData.setButtonAction(), newtonERP.module.AbstractEntity.setCurrentAction(), newtonERP.viewers.viewerData.PromptViewerData.setData(), newtonERP.module.AbstractEntity.setData(), newtonERP.viewers.viewerData.PromptViewerData.setReadOnly(), and newtonERP.viewers.viewerData.BaseViewerData.setTitle().
final Vector<AbstractOrmEntity> newtonERP.module.AbstractOrmEntity.get (String whereClause)
trouve l'entity selon les critere disponible, retourne le premier trouve
Parameters:
whereClause the where clause for the query
Returns:
this
Definition at line 469 of file AbstractOrmEntity.java.
Referenced by newtonERP.module.AbstractOrmEntity.editUI(), newtonERP.common.Authentication.getCurrentUser(), newtonERP.orm.Orm.getOrCreateEntity(), and modules.userRightModule.UserRightModule.initDB().
final Vector<AbstractOrmEntity> newtonERP.module.AbstractOrmEntity.get ()
fais un get sur un criter simple exprimé par l'entity this
Returns:
the selected entities
Definition at line 494 of file AbstractOrmEntity.java.
final Vector<AbstractOrmEntity> newtonERP.module.AbstractOrmEntity.get (AbstractOrmEntity entity)
Parameters:
entity the search entity
Returns:
the selected entities
Definition at line 503 of file AbstractOrmEntity.java.
final Vector<AbstractOrmEntity> newtonERP.module.AbstractOrmEntity.get (Vector< AbstractOrmEntity > entities)
Parameters:
entities the entities from which we are going to select our data (where clause)
Returns:
the selected entities
Definition at line 516 of file AbstractOrmEntity.java.
Vector<String> newtonERP.module.AbstractOrmEntity.getAccessorNameList ()
Returns:
nom de tous les accesseurs
Definition at line 857 of file AbstractOrmEntity.java.
Referenced by newtonERP.orm.associations.AccessorManager.addAccessor().
String newtonERP.module.AbstractOrmEntity.getButtonCaption ()
Implémentation par default.
Returns:
Caption par default d'un bouton de modification pour cette entité
Definition at line 566 of file AbstractOrmEntity.java.
Module newtonERP.module.AbstractOrmEntity.getCurrentModule ()
Returns:
Module par default
Reimplemented from newtonERP.module.AbstractEntity.
Definition at line 441 of file AbstractOrmEntity.java.
Referenced by newtonERP.module.AbstractOrmEntity.getList().
String newtonERP.module.AbstractOrmEntity.getForeignKeyName ()
Returns:
nom de la clef étrangère pour cette entité lorsque les autres entités l'utilisent
Definition at line 539 of file AbstractOrmEntity.java.
References newtonERP.module.AbstractEntity.getSystemName().
Referenced by newtonERP.orm.associations.FlagPoolManager.addFlagPool(), modules.userRightModule.UserRightModule.addGroupsRight(), newtonERP.orm.associations.ListOfValueManager.addListOfValue(), newtonERP.module.AbstractOrmEntity.assign(), newtonERP.orm.associations.GateWayManager.getExternalEntity(), modules.taskModule.entityDefinitions.EntityEntity.getModuleEntity(), modules.taskModule.entityDefinitions.ActionEntity.getModuleEntity(), modules.userRightModule.UserRightModule.initDB(), modules.taskModule.entityDefinitions.TaskEntity.initFields(), modules.taskModule.entityDefinitions.Specification.initFields(), modules.taskModule.entityDefinitions.SearchEntity.initFields(), modules.taskModule.entityDefinitions.SearchCriteria.initFields(), modules.taskModule.entityDefinitions.FieldEntity.initFields(), modules.taskModule.entityDefinitions.EntityEntity.initFields(), modules.taskModule.entityDefinitions.EffectEntity.initFields(), modules.taskModule.entityDefinitions.ActionEntity.initFields(), modules.taskModule.entityDefinitions.AccessorEntity.initFields(), modules.common.entityDefinitions.Address.initFields(), newtonERP.orm.associations.GateWay.isColored(), and modules.userRightModule.UserRightModule.removeGroupsRight().
Vector<GateWay> newtonERP.module.AbstractOrmEntity.getGateWayList ()
Returns:
liste des gateways (accesseurs passant par un autre)
Definition at line 867 of file AbstractOrmEntity.java.
Referenced by newtonERP.orm.associations.GateWayManager.addGateWay(), newtonERP.viewers.viewerData.ListViewerData.getHeader(), and newtonERP.viewers.firstStep.PromptViewer.getHtmlCode().
String newtonERP.module.AbstractOrmEntity.getInputValue (String inputName)
Parameters:
inputName nom du field
Returns:
valeur contenue dans le field
Definition at line 731 of file AbstractOrmEntity.java.
References newtonERP.orm.field.Fields.getField().
int newtonERP.module.AbstractOrmEntity.getItemLimitListPerPage ()
Returns:
Nombre d'item par page
Definition at line 432 of file AbstractOrmEntity.java.
Referenced by newtonERP.module.AbstractOrmEntity.getList().
final ListViewerData newtonERP.module.AbstractOrmEntity.getList ()
Returns:
ne liste d'entité de ce type
Definition at line 323 of file AbstractOrmEntity.java.
Referenced by newtonERP.module.AbstractOrmEntity.deleteUI(), and newtonERP.module.Module.doAction().
ListViewerData newtonERP.module.AbstractOrmEntity.getList (Hashtable< String, String > parameters)
Parameters:
parameters parametres de sélection (à venir)
Returns:
une liste d'entité de ce type
Reimplemented in modules.taskModule.entityDefinitions.ActionEntity, modules.taskModule.entityDefinitions.EntityEntity, modules.taskModule.entityDefinitions.FieldEntity, modules.taskModule.entityDefinitions.ModuleEntity, modules.taskModule.entityDefinitions.SearchCriteriaOperator, and modules.userRightModule.entityDefinitions.Right.
Definition at line 332 of file AbstractOrmEntity.java.
References newtonERP.viewers.viewerData.ListViewerData.addEntity(), newtonERP.viewers.viewerData.BaseViewerData.addGlobalActions(), newtonERP.common.ActionLink.addParameters(), newtonERP.viewers.viewerData.GridViewerData.addSpecificActionButtonList(), newtonERP.module.AbstractOrmEntity.getCurrentModule(), newtonERP.module.AbstractEntity.getFields(), newtonERP.module.AbstractOrmEntity.getItemLimitListPerPage(), newtonERP.orm.field.Fields.getKeyList(), newtonERP.module.AbstractOrmEntity.getPrimaryKeyName(), newtonERP.module.AbstractEntity.getSystemName(), newtonERP.module.AbstractOrmEntity.getVisibleName(), newtonERP.common.ActionLink.setConfirm(), newtonERP.module.AbstractEntity.setCurrentModule(), newtonERP.viewers.viewerData.ListViewerData.setPageSelector(), newtonERP.viewers.viewerData.ListViewerData.setSearchBar(), and newtonERP.viewers.viewerData.BaseViewerData.setTitle().
String newtonERP.module.AbstractOrmEntity.getNaturalKeyDescription ()
Returns:
Description d'une entité par la valeur de sa clef naturelle
Definition at line 637 of file AbstractOrmEntity.java.
References newtonERP.module.AbstractEntity.getDataString(), newtonERP.module.AbstractEntity.getFields(), newtonERP.module.generalEntity.ListOfValue.getForeignValue(), newtonERP.module.AbstractOrmEntity.getNaturalKeyNameList(), and newtonERP.module.AbstractEntity.tryMatchListOfValue().
Referenced by newtonERP.viewers.viewerData.ListViewerData.getCases(), newtonERP.module.generalEntity.ListOfValue.getForeignValue(), and newtonERP.viewers.firstStep.PromptViewer.getHtmlCode().
String newtonERP.module.AbstractOrmEntity.getNaturalKeyName ()
Returns:
Nom de la clef naturelle
Definition at line 676 of file AbstractOrmEntity.java.
References newtonERP.orm.field.Fields.getField(), newtonERP.module.AbstractEntity.getFields(), newtonERP.module.AbstractOrmEntity.getNaturalKeyNameList(), and newtonERP.module.AbstractOrmEntity.getVisibleName().
Referenced by newtonERP.orm.associations.FlagPoolManager.addFlagPool(), newtonERP.module.AbstractOrmEntity.assign(), and newtonERP.viewers.firstStep.PromptViewer.getHtmlCode().
Vector<String> newtonERP.module.AbstractOrmEntity.getNaturalKeyNameList ()
Returns:
Liste des noms de champs correspondant à la clef naturelle de l'entité
Definition at line 597 of file AbstractOrmEntity.java.
References newtonERP.module.AbstractEntity.getFields(), and newtonERP.module.AbstractOrmEntity.getPrimaryKeyName().
Referenced by newtonERP.module.AbstractOrmEntity.getNaturalKeyDescription(), and newtonERP.module.AbstractOrmEntity.getNaturalKeyName().
Hashtable<String, FlagPool> newtonERP.module.AbstractOrmEntity.getNegativeFlagPoolList ()
Returns:
liste des référence de flag pool inversées
Definition at line 757 of file AbstractOrmEntity.java.
Referenced by newtonERP.module.AbstractOrmEntity.addNegativeFlagPool().
PluralAccessor newtonERP.module.AbstractOrmEntity.getPluralAccessor (String accessorName, AbstractOrmEntity searchCriteriaEntity)
Parameters:
accessorName nom de l'accesseur
searchCriteriaEntity entité de recherche pour accesseur multiple critérié
Returns:
accesseur multiple critérié
Definition at line 779 of file AbstractOrmEntity.java.
References newtonERP.orm.associations.PluralAccessor.getInternalEntityDefinition(), and newtonERP.module.AbstractOrmEntity.getPluralAccessor().
PluralAccessor newtonERP.module.AbstractOrmEntity.getPluralAccessor (String accessorName)
Parameters:
accessorName non de l'accesseur
Returns:
accesseur multiple voulu
Definition at line 768 of file AbstractOrmEntity.java.
Referenced by modules.userRightModule.actions.RightCheck.doAction(), modules.taskModule.entityDefinitions.ModuleEntity.getActionEntityList(), modules.taskModule.entityDefinitions.ModuleEntity.getEntityEntityList(), newtonERP.module.AbstractOrmEntity.getPluralAccessor(), and modules.userRightModule.entityDefinitions.Groups.getRightList().
final TreeMap<String, PluralAccessor> newtonERP.module.AbstractOrmEntity.getPluralAccessorList ()
Returns:
la liste des accessors plusieurs à plusieurs pour cette entité
Definition at line 696 of file AbstractOrmEntity.java.
final Hashtable<String, FlagPool> newtonERP.module.AbstractOrmEntity.getPositiveFlagPoolList ()
Returns:
the flag pool list
Definition at line 585 of file AbstractOrmEntity.java.
Referenced by newtonERP.module.AbstractOrmEntity.addPositiveFlagPool(), newtonERP.module.AbstractOrmEntity.editUI(), and newtonERP.viewers.firstStep.PromptViewer.getHtmlCode().
final String newtonERP.module.AbstractOrmEntity.getPrimaryKeyName ()
Returns:
Nom de la clef primaire
Definition at line 528 of file AbstractOrmEntity.java.
References newtonERP.module.AbstractEntity.getSystemName().
Referenced by newtonERP.orm.associations.FlagPoolManager.addFlagPool(), newtonERP.orm.sgbd.sqlite.SgbdSqlite.count(), newtonERP.module.AbstractOrmEntity.deleteUI(), newtonERP.module.AbstractOrmEntity.editUI(), newtonERP.taskManager.TaskManager.executeTasks(), newtonERP.viewers.viewerData.ListViewerData.getCases(), newtonERP.orm.associations.GateWayManager.getExternalEntity(), newtonERP.module.generalEntity.ListOfValue.getForeignValue(), modules.userRightModule.entityDefinitions.GroupsRight.getGroupsEntity(), newtonERP.viewers.firstStep.PromptViewer.getHtmlCode(), newtonERP.module.AbstractOrmEntity.getList(), modules.taskModule.entityDefinitions.ModuleEntity.getList(), modules.taskModule.entityDefinitions.FieldEntity.getList(), modules.taskModule.entityDefinitions.EntityEntity.getList(), modules.taskModule.entityDefinitions.ActionEntity.getList(), newtonERP.module.AbstractOrmEntity.getNaturalKeyNameList(), newtonERP.module.AbstractOrmEntity.getPrimaryKeyValue(), modules.userRightModule.entityDefinitions.GroupsRight.getRightEntity(), newtonERP.module.Module.initDB(), modules.userRightModule.UserRightModule.initDB(), modules.userRightModule.entityDefinitions.User.initFields(), modules.userRightModule.entityDefinitions.Right.initFields(), modules.userRightModule.entityDefinitions.Groups.initFields(), modules.taskModule.entityDefinitions.TaskEntity.initFields(), modules.taskModule.entityDefinitions.Specification.initFields(), modules.taskModule.entityDefinitions.SearchEntity.initFields(), modules.taskModule.entityDefinitions.SearchCriteriaOperator.initFields(), modules.taskModule.entityDefinitions.SearchCriteria.initFields(), modules.taskModule.entityDefinitions.Parameter.initFields(), modules.taskModule.entityDefinitions.ModuleEntity.initFields(), modules.taskModule.entityDefinitions.FieldTypeEntity.initFields(), modules.taskModule.entityDefinitions.FieldEntity.initFields(), modules.taskModule.entityDefinitions.EntityEntity.initFields(), modules.taskModule.entityDefinitions.EffectEntity.initFields(), modules.taskModule.entityDefinitions.ActionEntity.initFields(), modules.taskModule.entityDefinitions.AccessorEntity.initFields(), modules.common.entityDefinitions.State.initFields(), modules.common.entityDefinitions.Country.initFields(), modules.common.entityDefinitions.Address.initFields(), modules.taskModule.entityDefinitions.Specification.isSatisfied(), and newtonERP.module.AbstractOrmEntity.newE().
final Integer newtonERP.module.AbstractOrmEntity.getPrimaryKeyValue ()
Returns:
Valeur de la clef primaire
Definition at line 548 of file AbstractOrmEntity.java.
References newtonERP.orm.field.Fields.getField(), newtonERP.module.AbstractEntity.getFields(), and newtonERP.module.AbstractOrmEntity.getPrimaryKeyName().
Referenced by modules.userRightModule.UserRightModule.addGroupsRight(), newtonERP.module.AbstractOrmEntity.assign(), newtonERP.module.AbstractOrmEntity.editUI(), newtonERP.taskManager.TaskManager.executeTasks(), newtonERP.viewers.viewerData.ListViewerData.getCases(), newtonERP.viewers.firstStep.PromptViewer.getHtmlCode(), newtonERP.module.generalEntity.FlagPool.getPositivePluralForeignAccessor(), modules.userRightModule.entityDefinitions.GroupsRight.GroupsRight(), modules.userRightModule.UserRightModule.initDB(), modules.userRightModule.UserRightModule.isPermissionAllowed(), and modules.userRightModule.UserRightModule.removeGroupsRight().
final AbstractOrmEntity newtonERP.module.AbstractOrmEntity.getSingleAccessor (String accessorName)
Parameters:
accessorName nom de l'accessor
Returns:
accesseur singulier
Definition at line 721 of file AbstractOrmEntity.java.
References newtonERP.module.AbstractOrmEntity.getSingleAccessor().
Referenced by modules.taskModule.entityDefinitions.FieldEntity.deleteUI(), modules.taskModule.entityDefinitions.SearchEntity.getEntity(), modules.userRightModule.entityDefinitions.User.getGroupsEntity(), modules.taskModule.entityDefinitions.EntityEntity.getModuleEntity(), modules.taskModule.entityDefinitions.ActionEntity.getModuleEntity(), newtonERP.orm.associations.AccessorManager.getSingleAccessor(), and newtonERP.module.AbstractOrmEntity.getSingleAccessor().
final TreeMap<String, AbstractOrmEntity> newtonERP.module.AbstractOrmEntity.getSingleAccessorList ()
Returns:
la liste des accessors 1 à 1 ou plusieurs à 1 pour cette entité
Definition at line 708 of file AbstractOrmEntity.java.
AbstractEntity newtonERP.module.AbstractOrmEntity.getUI (Hashtable< String, String > parameters)
BaseAction Get.
Parameters:
parameters parametre suplementaire
Returns:
entity qui doit etre read only
Definition at line 312 of file AbstractOrmEntity.java.
References newtonERP.module.AbstractOrmEntity.editUI().
final String newtonERP.module.AbstractOrmEntity.getVisibleName ()
Returns:
Nom visible de l'entités
Definition at line 574 of file AbstractOrmEntity.java.
References newtonERP.module.AbstractEntity.getSystemName().
Referenced by newtonERP.module.AbstractOrmEntity.editUI(), newtonERP.module.generalEntity.ListOfValue.getForeignValue(), newtonERP.module.AbstractOrmEntity.getList(), modules.taskModule.entityDefinitions.FieldEntity.getList(), modules.taskModule.entityDefinitions.EntityEntity.getList(), modules.taskModule.entityDefinitions.ActionEntity.getList(), and newtonERP.module.AbstractOrmEntity.getNaturalKeyName().
abstract Fields newtonERP.module.AbstractOrmEntity.initFields () [pure virtual]
initialise les champ de l'entity, doit etre overider si l'entity contient des champs, sinon initialise une liste de champ vide
Returns:
le Fields initialiser
Reimplemented from newtonERP.module.AbstractEntity.
Implemented in modules.common.entityDefinitions.Address, modules.common.entityDefinitions.Country, modules.common.entityDefinitions.State, modules.taskModule.entityDefinitions.AccessorEntity, modules.taskModule.entityDefinitions.ActionEntity, modules.taskModule.entityDefinitions.EffectEntity, modules.taskModule.entityDefinitions.EffectEntityParameter, modules.taskModule.entityDefinitions.EntityEntity, modules.taskModule.entityDefinitions.FieldEntity, modules.taskModule.entityDefinitions.FieldTypeEntity, modules.taskModule.entityDefinitions.ModuleEntity, modules.taskModule.entityDefinitions.Parameter, modules.taskModule.entityDefinitions.SearchCriteria, modules.taskModule.entityDefinitions.SearchCriteriaOperator, modules.taskModule.entityDefinitions.SearchEntity, modules.taskModule.entityDefinitions.Specification, modules.taskModule.entityDefinitions.TaskEntity, modules.userRightModule.entityDefinitions.Groups, modules.userRightModule.entityDefinitions.GroupsRight, modules.userRightModule.entityDefinitions.Right, and modules.userRightModule.entityDefinitions.User.
Referenced by newtonERP.module.generalEntity.FlagPool.getPositivePluralForeignAccessor().
final AbstractOrmEntity newtonERP.module.AbstractOrmEntity.newE ()
enregistre l'entity en DB
Returns:
this
Definition at line 82 of file AbstractOrmEntity.java.
References newtonERP.module.AbstractEntity.getFields(), newtonERP.module.AbstractOrmEntity.getPrimaryKeyName(), and newtonERP.module.AbstractEntity.setData().
Referenced by newtonERP.module.AbstractOrmEntity.editUI(), newtonERP.orm.Orm.getOrCreateEntity(), modules.userRightModule.UserRightModule.initDB(), and modules.common.Common.initDB().
AbstractEntity newtonERP.module.AbstractOrmEntity.newUI (Hashtable< String, String > parameters)
BaseAction New.
Parameters:
parameters parametre suplementaire
Returns:
l'entity qui a été entré en DB (incluant la primaryKey)
Reimplemented in modules.taskModule.entityDefinitions.FieldEntity.
Definition at line 69 of file AbstractOrmEntity.java.
References newtonERP.module.AbstractOrmEntity.editUI(), newtonERP.module.AbstractEntity.getFields(), and newtonERP.orm.field.Fields.setDefaultValue().
Referenced by newtonERP.module.Module.doAction().
final void newtonERP.module.AbstractOrmEntity.setOrmizableData (Hashtable< String, Object > parameters)
Parameters:
parameters la hashTable de parametre qui sera transphormé en entity
Definition at line 57 of file AbstractOrmEntity.java.
References newtonERP.module.AbstractEntity.getFields(), and newtonERP.orm.field.Fields.setFromHashTable().
Referenced by newtonERP.orm.EntityCreator.createEntitiesFromResultSet().
final void newtonERP.module.AbstractOrmEntity.setVisibleName (String visibleName)
Parameters:
visibleName nom visible de l'entité
Definition at line 688 of file AbstractOrmEntity.java.
Referenced by modules.common.entityDefinitions.Address.Address().
The documentation for this class was generated from the following file:
src/newtonERP/module/AbstractOrmEntity.java