Bee ERP: newtonERP.module.generalEntity.VolatilEntity Class Reference
newtonERP.module.generalEntity.VolatilEntity Class Reference
Inherits newtonERP::module::AbstractEntity.
Public Member Functions
VolatilEntity ()
default constructor
Fields initFields ()
initialise les champ de l'entity, doit etre overider si l'entity contient des champs, sinon initialise une liste de champ vide
void addField (String label, String fieldName, String currentValue)
void addField (String label, String fieldName)
void addField (Field<?> field)
Detailed Description
Author:
CloutierJo
Definition at line 13 of file VolatilEntity.java.
Member Function Documentation
void newtonERP.module.generalEntity.VolatilEntity.addField (String label, String fieldName, String currentValue)
Parameters:
label étiquette du champ
fieldName nom du champ
currentValue valeur courante
Definition at line 34 of file VolatilEntity.java.
Referenced by newtonERP.module.generalEntity.VolatilEntity.addField().
void newtonERP.module.generalEntity.VolatilEntity.addField (Field<?> field)
Parameters:
field un field a ajouter
Definition at line 54 of file VolatilEntity.java.
References newtonERP.module.AbstractEntity.getFields().
void newtonERP.module.generalEntity.VolatilEntity.addField (String label, String fieldName)
Parameters:
label étiquette du champ
fieldName nom du champ
Definition at line 46 of file VolatilEntity.java.
References newtonERP.module.generalEntity.VolatilEntity.addField().
Fields newtonERP.module.generalEntity.VolatilEntity.initFields ()
initialise les champ de l'entity, doit etre overider si l'entity contient des champs, sinon initialise une liste de champ vide
Returns:
le Fields initialiser
Reimplemented from newtonERP.module.AbstractEntity.
Definition at line 24 of file VolatilEntity.java.
The documentation for this class was generated from the following file:
src/newtonERP/module/generalEntity/VolatilEntity.java