Bee ERP: modules.userRightModule.UserRightModule Class Reference
modules.userRightModule.UserRightModule Class Reference
Inherits newtonERP::module::Module.
Public Member Functions
UserRightModule ()
Default constructor for the user right module initializing himself.
void initDB ()
permet d'initialiser la base de donne lors de l'installation du module, ne doit pas prendre en compte la creation des table
void addGroupsRight (String groupName, String actionName, String entityName)
void addGroupsRight (String groupName, String rightActionName)
void removeGroupsRight (String groupName, String rightActionName)
boolean isPermissionAllowed (ActionLink actionLink)
Detailed Description
Author:
Gabriel Therrien, Guillaume Lacasse, CloutierJo
Class representing the user right module. Base module for the ERP.
Definition at line 25 of file UserRightModule.java.
Constructor & Destructor Documentation
modules.userRightModule.UserRightModule.UserRightModule ()
Default constructor for the user right module initializing himself.
Adds the actions and the entity defenitions
Definition at line 31 of file UserRightModule.java.
References newtonERP.module.Module.addGlobalActionMenuItem(), and newtonERP.module.Module.setVisibleName().
Member Function Documentation
void modules.userRightModule.UserRightModule.addGroupsRight (String groupName, String actionName, String entityName)
Parameters:
groupName nom du groupe
actionName nom de l'action
entityName nom de l'entité
Definition at line 116 of file UserRightModule.java.
References newtonERP.module.AbstractOrmEntity.getForeignKeyName(), and newtonERP.module.AbstractOrmEntity.getPrimaryKeyValue().
void modules.userRightModule.UserRightModule.addGroupsRight (String groupName, String rightActionName)
Parameters:
groupName group's name
rightActionName right's name
Definition at line 137 of file UserRightModule.java.
References newtonERP.module.AbstractOrmEntity.getForeignKeyName(), and newtonERP.module.AbstractOrmEntity.getPrimaryKeyValue().
boolean modules.userRightModule.UserRightModule.isPermissionAllowed (ActionLink actionLink)
Parameters:
actionLink un actionLink
Returns:
vrai si les permission sont présentement accordées, sinon, faux
Definition at line 178 of file UserRightModule.java.
References newtonERP.common.ActionLink.getAction(), newtonERP.module.AbstractAction.getEntityUsable(), newtonERP.module.AbstractOrmEntity.getPrimaryKeyValue(), newtonERP.module.AbstractEntity.getSystemName(), and newtonERP.module.AbstractAction.getSystemName().
void modules.userRightModule.UserRightModule.removeGroupsRight (String groupName, String rightActionName)
Parameters:
groupName group's name
rightActionName right's name
Definition at line 158 of file UserRightModule.java.
References newtonERP.module.AbstractOrmEntity.getForeignKeyName(), and newtonERP.module.AbstractOrmEntity.getPrimaryKeyValue().
The documentation for this class was generated from the following file:
src/modules/userRightModule/UserRightModule.java