Bee ERP: newtonERP.module.generalEntity.FlagPool Class Reference
newtonERP.module.generalEntity.FlagPool Class Reference
Inherits newtonERP::viewers::viewables::CheckListViewable.
Public Member Functions
FlagPool (AbstractOrmEntity sourceEntityDefinition, String visibleDescription, AbstractOrmEntity intermediateEntityDefinition, String intermediateKeyIn, String intermediateKeyOut, AbstractOrmEntity foreignEntityDefinition, String foreignKey, Vector< String > foreignDescriptionUiControls)
String getVisibleDescription ()
TreeMap< String, String > getAvailableElementList ()
HashSet< String > getCheckedElementList ()
void query (String currentSourceKeyName, Integer currentSourceKeyValue)
AbstractOrmEntity getIntermediateEntityDefinition ()
AbstractOrmEntity getForeignEntityDefinition ()
String getIntermediateKeyIn ()
String getIntermediateKeyOut ()
String getSourceKeyValue ()
AbstractOrmEntity getSourceEntityDefinition ()
Vector< AbstractOrmEntity > getPositivePluralIntermediateAccessor ()
PluralAccessor getPositivePluralForeignAccessor (AbstractOrmEntity searchCriteriaEntity)
Detailed Description
Author:
Guillaume Lacasse cette classe sert à faire des liste de flag qu'on peut attribuer à une entité lorsque ces flags sont dans une table étrangère passant par une table intermédiaire. Exemple: attribution de droits pour un groupe (ça passe par GroupsRight)
Definition at line 19 of file FlagPool.java.
Constructor & Destructor Documentation
newtonERP.module.generalEntity.FlagPool.FlagPool (AbstractOrmEntity sourceEntityDefinition, String visibleDescription, AbstractOrmEntity intermediateEntityDefinition, String intermediateKeyIn, String intermediateKeyOut, AbstractOrmEntity foreignEntityDefinition, String foreignKey, Vector< String > foreignDescriptionUiControls)
Parameters:
sourceEntityDefinition Definition de l'entité de source, exemple: groupe
visibleDescription Description visible
intermediateEntityDefinition Entité de table intermédiaire, exemple: GroupsRight
intermediateKeyIn Colonne d'entré de table intermédiaire, exemple: groupID
intermediateKeyOut Colonne de sortie de table intermédiaire, exemple: rightID
foreignEntityDefinition entité de table étrangère, exemple: Right
foreignKey clef d'identification de table étrangère, exemple: PKrightID
foreignDescriptionUiControls liste de colonne de description de table étrangère, exemple: Action, Module
Definition at line 48 of file FlagPool.java.
Member Function Documentation
TreeMap<String, String> newtonERP.module.generalEntity.FlagPool.getAvailableElementList ()
Returns:
a tree map of the available elements
Implements newtonERP.viewers.viewables.CheckListViewable.
Definition at line 76 of file FlagPool.java.
References newtonERP.module.AbstractEntity.getSystemName().
HashSet<String> newtonERP.module.generalEntity.FlagPool.getCheckedElementList ()
Returns:
a hash set of cheked elements
Implements newtonERP.viewers.viewables.CheckListViewable.
Definition at line 132 of file FlagPool.java.
References newtonERP.module.AbstractEntity.getDataString(), newtonERP.module.generalEntity.FlagPool.getPositivePluralIntermediateAccessor(), and newtonERP.module.AbstractEntity.getSystemName().
AbstractOrmEntity newtonERP.module.generalEntity.FlagPool.getForeignEntityDefinition ()
Returns:
définition d'entité de table étrangère
Definition at line 166 of file FlagPool.java.
AbstractOrmEntity newtonERP.module.generalEntity.FlagPool.getIntermediateEntityDefinition ()
Returns:
définition d'entité de table intermédiaire
Definition at line 158 of file FlagPool.java.
String newtonERP.module.generalEntity.FlagPool.getIntermediateKeyIn ()
Returns:
clef d'entré dans table étrangère
Definition at line 174 of file FlagPool.java.
String newtonERP.module.generalEntity.FlagPool.getIntermediateKeyOut ()
Returns:
clef de sortie dans table étrangère (cible)
Definition at line 182 of file FlagPool.java.
PluralAccessor newtonERP.module.generalEntity.FlagPool.getPositivePluralForeignAccessor (AbstractOrmEntity searchCriteriaEntity)
Parameters:
searchCriteriaEntity critères de recherche facultatifs
Returns:
accessor multiple vers entité étrangère
Definition at line 237 of file FlagPool.java.
References newtonERP.module.generalEntity.FlagPool.getPositivePluralIntermediateAccessor(), newtonERP.module.AbstractOrmEntity.getPrimaryKeyValue(), newtonERP.module.AbstractOrmEntity.initFields(), and newtonERP.module.AbstractEntity.setData().
Vector<AbstractOrmEntity> newtonERP.module.generalEntity.FlagPool.getPositivePluralIntermediateAccessor ()
Returns:
retourne un accessor multiple
Definition at line 207 of file FlagPool.java.
References newtonERP.module.AbstractEntity.setData().
Referenced by newtonERP.module.generalEntity.FlagPool.getCheckedElementList(), and newtonERP.module.generalEntity.FlagPool.getPositivePluralForeignAccessor().
AbstractOrmEntity newtonERP.module.generalEntity.FlagPool.getSourceEntityDefinition ()
Returns:
définition d'entité source (entité de départ dans laquelle on met un flagPool)
Definition at line 199 of file FlagPool.java.
String newtonERP.module.generalEntity.FlagPool.getSourceKeyValue ()
Returns:
valeur de clef primaire de table d'entité de table source
Definition at line 190 of file FlagPool.java.
String newtonERP.module.generalEntity.FlagPool.getVisibleDescription ()
Returns:
the visible description
Implements newtonERP.viewers.viewables.CheckListViewable.
Definition at line 70 of file FlagPool.java.
void newtonERP.module.generalEntity.FlagPool.query (String currentSourceKeyName, Integer currentSourceKeyValue)
Parameters:
currentSourceKeyName nom de clef
currentSourceKeyValue valeur de clef
Definition at line 149 of file FlagPool.java.
The documentation for this class was generated from the following file:
src/newtonERP/module/generalEntity/FlagPool.java