Bee ERP: modules.taskModule.entityDefinitions.ModuleEntity Class Reference
modules.taskModule.entityDefinitions.ModuleEntity Class Reference
Entité représentant un module.
Inherits newtonERP::module::AbstractOrmEntity.
Public Member Functions
Fields initFields ()
initialise les champ de l'entity, doit etre overider si l'entity contient des champs, sinon initialise une liste de champ vide
Module getModule ()
ListViewerData getList (Hashtable< String, String > parameters)
Vector< EntityEntity > getEntityEntityList ()
Vector< ActionEntity > getActionEntityList ()
Protected Member Functions
Fields preInitFields ()
Detailed Description
Entité représentant un module.
Author:
Guillaume Lacasse
Definition at line 23 of file ModuleEntity.java.
Member Function Documentation
Vector<ActionEntity> modules.taskModule.entityDefinitions.ModuleEntity.getActionEntityList ()
Returns:
list of action entity for this module
Definition at line 99 of file ModuleEntity.java.
References newtonERP.module.AbstractOrmEntity.getPluralAccessor(), and newtonERP.module.AbstractEntity.getSystemName().
Vector<EntityEntity> modules.taskModule.entityDefinitions.ModuleEntity.getEntityEntityList ()
Returns:
list of entity entity for this module
Definition at line 86 of file ModuleEntity.java.
References newtonERP.module.AbstractOrmEntity.getPluralAccessor(), and newtonERP.module.AbstractEntity.getSystemName().
ListViewerData modules.taskModule.entityDefinitions.ModuleEntity.getList (Hashtable< String, String > parameters)
Parameters:
parameters parametres de sélection (à venir)
Returns:
une liste d'entité de ce type
Reimplemented from newtonERP.module.AbstractOrmEntity.
Definition at line 68 of file ModuleEntity.java.
References newtonERP.viewers.viewerData.GridViewerData.addSpecificActionButtonList(), and newtonERP.module.AbstractOrmEntity.getPrimaryKeyName().
Module modules.taskModule.entityDefinitions.ModuleEntity.getModule ()
Returns:
vrai module
Definition at line 57 of file ModuleEntity.java.
Referenced by modules.taskModule.entityDefinitions.ActionEntity.getAction(), and modules.taskModule.entityDefinitions.EntityEntity.getEntityDefinition().
Fields modules.taskModule.entityDefinitions.ModuleEntity.initFields () [virtual]
initialise les champ de l'entity, doit etre overider si l'entity contient des champs, sinon initialise une liste de champ vide
Returns:
le Fields initialiser
Implements newtonERP.module.AbstractOrmEntity.
Definition at line 42 of file ModuleEntity.java.
References newtonERP.module.AbstractOrmEntity.getPrimaryKeyName().
The documentation for this class was generated from the following file:
src/modules/taskModule/entityDefinitions/ModuleEntity.java