Bee ERP: newtonERP.module.AbstractEntity Class Reference
newtonERP.module.AbstractEntity Class Reference
Inherited by newtonERP.module.AbstractOrmEntity, newtonERP.module.generalEntity.AlertEntity, newtonERP.module.generalEntity.ForwardEntity, newtonERP.module.generalEntity.ImageFile, newtonERP.module.generalEntity.ScrollList, newtonERP.module.generalEntity.SplashScreen, newtonERP.module.generalEntity.StaticTextEntity, newtonERP.module.generalEntity.VolatilEntity, newtonERP.viewers.viewerData.BandDiagramViewerData, newtonERP.viewers.viewerData.BaseViewerData, newtonERP.viewers.viewerData.FloorViewerData, newtonERP.viewers.viewerData.PageSelector, and newtonERP.viewers.viewerData.SearchBar.
Public Member Functions
AbstractEntity ()
construit une entity ne comportant aucun champ
Fields initFields ()
initialise les champ de l'entity, doit etre overider si l'entity contient des champs, sinon initialise une liste de champ vide
boolean equals (Object obj)
Fields getFields ()
String toString ()
String getDataString (String shortName)
methode d'Accces rapide au donnees sous forme de string
Object getData (String shortName)
void setData (String shortName, Object data)
ListOfValue tryMatchListOfValue (String fieldKeyName)
AbstractAction getCurrentAction ()
Module getCurrentModule ()
final void setCurrentModule (Module currentModule)
final void setCurrentAction (AbstractAction currentAction)
String getSystemName ()
String getLabelName (String inputName)
Hashtable< String, ListOfValue > getPositiveListOfValueList ()
HashSet< ListOfValue > getNegativeListOfValueList ()
void addPositiveListOfValue (String foreignKeyName, ListOfValue listOfValue)
void addNegativeListOfValue (ListOfValue listOfValue)
boolean isMatchCheckBox (String inputName)
void reset ()
remet l'etat de l'entity a ses valeur initial
String getDetailedDescription ()
void setDetailedDescription (String detailedDescription)
Protected Member Functions
Fields preInitFields ()
Protected Attributes
Fields fields
Module currentModule
Detailed Description
Author:
r3lemaypa, r3lacasgu, CloutierJo
Definition at line 21 of file AbstractEntity.java.
Member Function Documentation
void newtonERP.module.AbstractEntity.addNegativeListOfValue (ListOfValue listOfValue)
Parameters:
foreignKeyName nom de la clef etrangère de la listOfValue
listOfValue listOfValue à ajouter
Definition at line 278 of file AbstractEntity.java.
References newtonERP.module.AbstractEntity.getNegativeListOfValueList().
Referenced by newtonERP.orm.associations.ListOfValueManager.addListOfValue().
void newtonERP.module.AbstractEntity.addPositiveListOfValue (String foreignKeyName, ListOfValue listOfValue)
Parameters:
foreignKeyName nom de la clef etrangère de la listOfValue
listOfValue listOfValue à ajouter
Definition at line 267 of file AbstractEntity.java.
References newtonERP.module.AbstractEntity.getPositiveListOfValueList().
Referenced by newtonERP.orm.associations.ListOfValueManager.addListOfValue().
AbstractAction newtonERP.module.AbstractEntity.getCurrentAction ()
Returns:
action courante
Reimplemented in newtonERP.viewers.viewerData.PromptViewerData.
Definition at line 189 of file AbstractEntity.java.
Module newtonERP.module.AbstractEntity.getCurrentModule ()
Returns:
module courant
Reimplemented in newtonERP.module.AbstractOrmEntity, and newtonERP.viewers.viewerData.PromptViewerData.
Definition at line 197 of file AbstractEntity.java.
Object newtonERP.module.AbstractEntity.getData (String shortName)
Parameters:
shortName le nom du champ voulu
Returns:
the data
Definition at line 160 of file AbstractEntity.java.
References newtonERP.orm.field.Fields.getField(), and newtonERP.module.AbstractEntity.getFields().
Referenced by newtonERP.module.AbstractOrmEntity.editUI(), newtonERP.orm.associations.GateWayManager.getExternalEntity(), modules.taskModule.entityDefinitions.FieldEntity.getFieldInstance(), modules.taskModule.entityDefinitions.SearchCriteria.getKey(), modules.userRightModule.UserRightModule.initDB(), modules.taskModule.entityDefinitions.TaskEntity.isActive(), and modules.taskModule.entityDefinitions.TaskEntity.isStraightSearch().
String newtonERP.module.AbstractEntity.getDataString (String shortName)
methode d'Accces rapide au donnees sous forme de string
Parameters:
shortName le nom du champ voulu
Returns:
la valeur sous forme de string
Definition at line 151 of file AbstractEntity.java.
References newtonERP.orm.field.Fields.getField(), and newtonERP.module.AbstractEntity.getFields().
Referenced by modules.taskModule.entityDefinitions.EntityEntity.buildPrimaryKeyName(), newtonERP.module.AbstractOrmEntity.deleteUI(), modules.taskModule.entityDefinitions.FieldEntity.deleteUI(), modules.taskModule.entityDefinitions.ActionEntity.getActionName(), newtonERP.module.generalEntity.FlagPool.getCheckedElementList(), modules.taskModule.entityDefinitions.FieldEntity.getFieldInstance(), modules.taskModule.entityDefinitions.Parameter.getKey(), newtonERP.module.AbstractOrmEntity.getNaturalKeyDescription(), modules.taskModule.entityDefinitions.SearchCriteriaOperator.getOperator(), newtonERP.common.ActionLink.getParameters(), modules.taskModule.entityDefinitions.SearchCriteria.getValue(), and modules.taskModule.entityDefinitions.Parameter.getValue().
String newtonERP.module.AbstractEntity.getDetailedDescription ()
Returns:
description détaillée facultative
Definition at line 316 of file AbstractEntity.java.
Fields newtonERP.module.AbstractEntity.getFields ()
Returns:
the fields
Definition at line 135 of file AbstractEntity.java.
Referenced by newtonERP.module.generalEntity.VolatilEntity.addField(), newtonERP.orm.associations.ListOfValueManager.addListOfValue(), newtonERP.module.AbstractOrmEntity.assign(), newtonERP.orm.EntityCreator.createEntitiesFromResultSet(), newtonERP.module.Module.doAction(), newtonERP.module.AbstractOrmEntity.editUI(), newtonERP.taskManager.TaskManager.executeTasks(), newtonERP.module.AbstractEntity.getData(), newtonERP.module.AbstractEntity.getDataString(), modules.userRightModule.entityDefinitions.GroupsRight.getGroupsEntity(), newtonERP.viewers.viewerData.ListViewerData.getHeader(), newtonERP.viewers.firstStep.PromptViewer.getHtmlCode(), newtonERP.module.AbstractEntity.getLabelName(), newtonERP.module.AbstractOrmEntity.getList(), newtonERP.module.AbstractOrmEntity.getNaturalKeyDescription(), newtonERP.module.AbstractOrmEntity.getNaturalKeyName(), newtonERP.module.AbstractOrmEntity.getNaturalKeyNameList(), newtonERP.module.AbstractOrmEntity.getPrimaryKeyValue(), modules.userRightModule.entityDefinitions.GroupsRight.getRightEntity(), modules.userRightModule.entityDefinitions.GroupsRight.GroupsRight(), newtonERP.orm.sgbd.sqlite.SgbdSqlite.insert(), newtonERP.orm.associations.GateWay.isColored(), newtonERP.module.AbstractEntity.isMatchCheckBox(), newtonERP.module.AbstractOrmEntity.newE(), newtonERP.module.AbstractOrmEntity.newUI(), modules.taskModule.entityDefinitions.FieldEntity.newUI(), newtonERP.module.AbstractAction.perform(), newtonERP.module.AbstractEntity.setData(), newtonERP.module.AbstractOrmEntity.setOrmizableData(), newtonERP.orm.sgbd.sqlite.SgbdSqlite.update(), and newtonERP.orm.sgbd.sqlite.SgbdSqlite.updateUnique().
String newtonERP.module.AbstractEntity.getLabelName (String inputName)
Parameters:
inputName nom d'un field
Returns:
nom complete d'un field
Reimplemented in newtonERP.viewers.viewerData.PromptViewerData.
Definition at line 236 of file AbstractEntity.java.
References newtonERP.orm.field.Fields.getField(), and newtonERP.module.AbstractEntity.getFields().
HashSet<ListOfValue> newtonERP.module.AbstractEntity.getNegativeListOfValueList ()
Returns:
liste des listOfValue
Definition at line 255 of file AbstractEntity.java.
Referenced by newtonERP.module.AbstractEntity.addNegativeListOfValue().
Hashtable<String, ListOfValue> newtonERP.module.AbstractEntity.getPositiveListOfValueList ()
Returns:
liste des listOfValue
Definition at line 244 of file AbstractEntity.java.
Referenced by newtonERP.module.AbstractEntity.addPositiveListOfValue(), newtonERP.orm.associations.SingleAccessorManager.getSingleAccessor(), and newtonERP.orm.associations.SingleAccessorManager.getSingleAccessorList().
String newtonERP.module.AbstractEntity.getSystemName ()
Returns:
nom de l'entité dans le système (normalement nom de la classe mais peut être overridé si c'est une entité dynamique)
Definition at line 227 of file AbstractEntity.java.
Referenced by newtonERP.orm.associations.AccessorManager.addAccessor(), newtonERP.orm.sgbd.sqlite.SgbdSqlite.addColumnToTable(), newtonERP.orm.associations.ListOfValueManager.addListOfValue(), newtonERP.orm.sgbd.sqlite.SgbdSqlite.count(), newtonERP.orm.Orm.createIndex(), newtonERP.orm.sgbd.sqlite.SgbdSqlite.createTableForEntity(), modules.taskModule.actions.AddFieldToOrm.doAction(), newtonERP.module.generalEntity.ListOfValue.equals(), newtonERP.taskManager.TaskManager.executeTasks(), modules.taskModule.entityDefinitions.ModuleEntity.getActionEntityList(), newtonERP.module.generalEntity.FlagPool.getAvailableElementList(), newtonERP.module.generalEntity.FlagPool.getCheckedElementList(), modules.taskModule.entityDefinitions.ModuleEntity.getEntityEntityList(), newtonERP.module.AbstractOrmEntity.getForeignKeyName(), newtonERP.viewers.secondStep.ButtonLinkViewer.getHtmlCode(), newtonERP.module.AbstractOrmEntity.getList(), newtonERP.module.AbstractOrmEntity.getPrimaryKeyName(), newtonERP.module.AbstractOrmEntity.getVisibleName(), newtonERP.orm.sgbd.sqlite.SgbdSqlite.insert(), modules.userRightModule.UserRightModule.isPermissionAllowed(), newtonERP.orm.sgbd.sqlite.SgbdSqlite.select(), newtonERP.viewers.viewerData.PromptViewerData.setData(), newtonERP.orm.sgbd.sqlite.SgbdSqlite.update(), and newtonERP.orm.sgbd.sqlite.SgbdSqlite.updateUnique().
Fields newtonERP.module.AbstractEntity.initFields ()
initialise les champ de l'entity, doit etre overider si l'entity contient des champs, sinon initialise une liste de champ vide
Returns:
le Fields initialiser
Reimplemented in modules.common.entityDefinitions.Address, modules.common.entityDefinitions.Country, modules.common.entityDefinitions.State, modules.taskModule.entityDefinitions.AccessorEntity, modules.taskModule.entityDefinitions.ActionEntity, modules.taskModule.entityDefinitions.EffectEntity, modules.taskModule.entityDefinitions.EffectEntityParameter, modules.taskModule.entityDefinitions.EntityEntity, modules.taskModule.entityDefinitions.FieldEntity, modules.taskModule.entityDefinitions.FieldTypeEntity, modules.taskModule.entityDefinitions.ModuleEntity, modules.taskModule.entityDefinitions.Parameter, modules.taskModule.entityDefinitions.SearchCriteria, modules.taskModule.entityDefinitions.SearchCriteriaOperator, modules.taskModule.entityDefinitions.SearchEntity, modules.taskModule.entityDefinitions.Specification, modules.taskModule.entityDefinitions.TaskEntity, modules.userRightModule.entityDefinitions.Groups, modules.userRightModule.entityDefinitions.GroupsRight, modules.userRightModule.entityDefinitions.Right, modules.userRightModule.entityDefinitions.User, newtonERP.module.AbstractOrmEntity, and newtonERP.module.generalEntity.VolatilEntity.
Definition at line 82 of file AbstractEntity.java.
boolean newtonERP.module.AbstractEntity.isMatchCheckBox (String inputName)
Parameters:
inputName nom du champ
Returns:
si le champ est un checkbox
Reimplemented in newtonERP.viewers.viewerData.PromptViewerData.
Definition at line 293 of file AbstractEntity.java.
References newtonERP.orm.field.Fields.getField(), and newtonERP.module.AbstractEntity.getFields().
final void newtonERP.module.AbstractEntity.setCurrentAction (AbstractAction currentAction)
Parameters:
currentAction Action qui sera utilisée
Definition at line 218 of file AbstractEntity.java.
Referenced by newtonERP.module.AbstractOrmEntity.editUI(), and newtonERP.module.generalEntity.Form.Form().
final void newtonERP.module.AbstractEntity.setCurrentModule (Module currentModule)
Parameters:
currentModule Défini le module utilisé en ce moment pour cette entité
Definition at line 210 of file AbstractEntity.java.
Referenced by newtonERP.module.generalEntity.Form.Form(), and newtonERP.module.AbstractOrmEntity.getList().
void newtonERP.module.AbstractEntity.setData (String shortName, Object data)
Parameters:
shortName le nom du champ voulu
data the data to set
Definition at line 169 of file AbstractEntity.java.
References newtonERP.module.AbstractEntity.getFields(), and newtonERP.orm.field.Fields.setData().
Referenced by newtonERP.module.AbstractOrmEntity.assign(), modules.taskModule.entityDefinitions.EntityEntity.ContainsPrimaryKeyField(), modules.taskModule.actions.GenerateEntityCode.createRightIfNotExist(), newtonERP.orm.Orm.delete(), modules.userRightModule.actions.RightCheck.doAction(), modules.userRightModule.actions.CreateAllRight.doAction(), newtonERP.module.AbstractOrmEntity.editUI(), newtonERP.common.Authentication.getCurrentUser(), newtonERP.orm.associations.GateWayManager.getExternalEntity(), newtonERP.orm.Orm.getOrCreateEntity(), newtonERP.module.generalEntity.FlagPool.getPositivePluralForeignAccessor(), newtonERP.module.generalEntity.FlagPool.getPositivePluralIntermediateAccessor(), newtonERP.module.Module.initDB(), modules.userRightModule.UserRightModule.initDB(), modules.common.Common.initDB(), modules.taskModule.entityDefinitions.Specification.isSatisfied(), and newtonERP.module.AbstractOrmEntity.newE().
void newtonERP.module.AbstractEntity.setDetailedDescription (String detailedDescription)
Parameters:
detailedDescription description détaillée facultative
Definition at line 324 of file AbstractEntity.java.
ListOfValue newtonERP.module.AbstractEntity.tryMatchListOfValue (String fieldKeyName)
Parameters:
fieldKeyName the field name
Returns:
If list of value exist, return it, else, return null
Reimplemented in newtonERP.viewers.viewerData.PromptViewerData.
Definition at line 178 of file AbstractEntity.java.
Referenced by newtonERP.viewers.viewerData.ListViewerData.getHeader(), newtonERP.viewers.firstStep.PromptViewer.getHtmlCode(), newtonERP.module.AbstractOrmEntity.getNaturalKeyDescription(), and newtonERP.orm.associations.SingleAccessorManager.getSingleAccessor().
The documentation for this class was generated from the following file:
src/newtonERP/module/AbstractEntity.java