Bee ERP: newtonERP.serveur.Servlet Class Reference
newtonERP.serveur.Servlet Class Reference
la gestion du serveur, request manager
Inherits org::mortbay::jetty::servlet::ServletHandler.
Public Member Functions
Servlet ()
constructeur
void handle (String target, HttpServletRequest request, HttpServletResponse response, int dispatch) throws IOException, ServletException
AbstractEntity urlToAction (String target, HttpServletRequest request)
Static Public Member Functions
static String makeLink (Module module)
static String makeLink (Module module, AbstractAction action)
static String makeLink (AbstractAction action)
Package Attributes
ResourceHandler resourceHandler = new ResourceHandler()
Detailed Description
la gestion du serveur, request manager
Author:
JoCloutier
Definition at line 33 of file Servlet.java.
Member Function Documentation
static String newtonERP.serveur.Servlet.makeLink (AbstractAction action) [static]
Parameters:
action action a lier
Returns:
le lien relatif vers les ressource demander
Definition at line 204 of file Servlet.java.
References newtonERP.module.AbstractAction.getOwnedByModule(), and newtonERP.serveur.Servlet.makeLink().
static String newtonERP.serveur.Servlet.makeLink (Module module, AbstractAction action) [static]
Parameters:
module module a lier
action action a lier
Returns:
le lien relatif vers les ressource demander
Definition at line 182 of file Servlet.java.
References newtonERP.module.AbstractAction.getSystemName(), and newtonERP.module.Module.getSystemName().
static String newtonERP.serveur.Servlet.makeLink (Module module) [static]
Parameters:
module module a lier
Returns:
le lien relatif vers les ressource demander
Definition at line 172 of file Servlet.java.
References newtonERP.module.Module.getSystemName().
Referenced by newtonERP.serveur.Servlet.makeLink().
AbstractEntity newtonERP.serveur.Servlet.urlToAction (String target, HttpServletRequest request)
Parameters:
target url d'apelle
request la request
Returns:
le Viewable
Definition at line 102 of file Servlet.java.
References newtonERP.serveur.CommandRouteur.routeCommand().
The documentation for this class was generated from the following file:
src/newtonERP/serveur/Servlet.java