Bee ERP: modules.taskModule.entityDefinitions.EntityEntity Class Reference
modules.taskModule.entityDefinitions.EntityEntity Class Reference
Représente une définition d'entité pour une entité.
Inherits newtonERP::module::AbstractOrmEntity.
Public Member Functions
Fields initFields ()
initialise les champ de l'entity, doit etre overider si l'entity contient des champs, sinon initialise une liste de champ vide
AbstractEntity deleteUI (Hashtable< String, String > parameters)
BaseAction Delete.
ListViewerData getList (Hashtable< String, String > parameters)
AbstractOrmEntity getEntityDefinition ()
ModuleEntity getModuleEntity ()
Iterator< FieldEntity > iterator ()
boolean ContainsPrimaryKeyField ()
String buildPrimaryKeyName ()
Protected Member Functions
Fields preInitFields ()
Detailed Description
Représente une définition d'entité pour une entité.
Author:
Guillaume Lacasse
Definition at line 26 of file EntityEntity.java.
Member Function Documentation
String modules.taskModule.entityDefinitions.EntityEntity.buildPrimaryKeyName ()
Returns:
primary key name for real entity (not entity entity)
Definition at line 149 of file EntityEntity.java.
References newtonERP.module.AbstractEntity.getDataString().
Referenced by modules.taskModule.entityDefinitions.EntityEntity.ContainsPrimaryKeyField(), and modules.taskModule.entityDefinitions.FieldEntity.newUI().
boolean modules.taskModule.entityDefinitions.EntityEntity.ContainsPrimaryKeyField ()
Returns:
true si l'entité d'entité a un entité de field qui correspond à sa clef primaire
Definition at line 135 of file EntityEntity.java.
References newtonERP.module.AbstractOrmEntity.assign(), modules.taskModule.entityDefinitions.EntityEntity.buildPrimaryKeyName(), and newtonERP.module.AbstractEntity.setData().
Referenced by modules.taskModule.entityDefinitions.FieldEntity.newUI().
AbstractEntity modules.taskModule.entityDefinitions.EntityEntity.deleteUI (Hashtable< String, String > parameters)
BaseAction Delete.
Parameters:
parameters parametre suplementaire
Returns:
todo: qu'Est-ce que l'on devrai retourné en general?
Reimplemented from newtonERP.module.AbstractOrmEntity.
Definition at line 66 of file EntityEntity.java.
AbstractOrmEntity modules.taskModule.entityDefinitions.EntityEntity.getEntityDefinition ()
Returns:
definition réele d'entité selon EntityEntity
Definition at line 98 of file EntityEntity.java.
References newtonERP.module.Module.getEntityDefinition(), modules.taskModule.entityDefinitions.ModuleEntity.getModule(), and modules.taskModule.entityDefinitions.EntityEntity.getModuleEntity().
Referenced by modules.taskModule.actions.AddFieldToOrm.doAction(), and modules.taskModule.entityDefinitions.SearchEntity.getEntity().
ListViewerData modules.taskModule.entityDefinitions.EntityEntity.getList (Hashtable< String, String > parameters)
Parameters:
parameters parametres de sélection (à venir)
Returns:
une liste d'entité de ce type
Reimplemented from newtonERP.module.AbstractOrmEntity.
Definition at line 78 of file EntityEntity.java.
References newtonERP.viewers.viewerData.GridViewerData.addSpecificActionButtonList(), newtonERP.module.AbstractOrmEntity.getPrimaryKeyName(), newtonERP.module.AbstractOrmEntity.getVisibleName(), and newtonERP.viewers.viewerData.BaseViewerData.removeGlobalActions().
ModuleEntity modules.taskModule.entityDefinitions.EntityEntity.getModuleEntity ()
Returns:
entité du module
Definition at line 113 of file EntityEntity.java.
References newtonERP.module.AbstractOrmEntity.getForeignKeyName(), and newtonERP.module.AbstractOrmEntity.getSingleAccessor().
Referenced by modules.taskModule.entityDefinitions.EntityEntity.getEntityDefinition().
Fields modules.taskModule.entityDefinitions.EntityEntity.initFields () [virtual]
initialise les champ de l'entity, doit etre overider si l'entity contient des champs, sinon initialise une liste de champ vide
Returns:
le Fields initialiser
Implements newtonERP.module.AbstractOrmEntity.
Definition at line 47 of file EntityEntity.java.
References newtonERP.module.AbstractOrmEntity.getForeignKeyName(), and newtonERP.module.AbstractOrmEntity.getPrimaryKeyName().
The documentation for this class was generated from the following file:
src/modules/taskModule/entityDefinitions/EntityEntity.java