Bee ERP: modules.taskModule.entityDefinitions.ActionEntity Class Reference
modules.taskModule.entityDefinitions.ActionEntity Class Reference
Représente une action définie dans une entitée.
Inherits newtonERP::module::AbstractOrmEntity.
Public Member Functions
Fields initFields ()
initialise les champ de l'entity, doit etre overider si l'entity contient des champs, sinon initialise une liste de champ vide
AbstractEntity deleteUI (Hashtable< String, String > parameters)
BaseAction Delete.
final ListViewerData getList (Hashtable< String, String > parameters)
AbstractAction getAction ()
ModuleEntity getModuleEntity ()
String getActionName ()
BaseAction getBaseAction (AbstractOrmEntity entity)
Detailed Description
Représente une action définie dans une entitée.
Author:
Guillaume Lacasse
Definition at line 25 of file ActionEntity.java.
Member Function Documentation
AbstractEntity modules.taskModule.entityDefinitions.ActionEntity.deleteUI (Hashtable< String, String > parameters)
BaseAction Delete.
Parameters:
parameters parametre suplementaire
Returns:
todo: qu'Est-ce que l'on devrai retourné en general?
Reimplemented from newtonERP.module.AbstractOrmEntity.
Definition at line 54 of file ActionEntity.java.
AbstractAction modules.taskModule.entityDefinitions.ActionEntity.getAction ()
Returns:
retourne une instance de vrai action selon l'entité d'action
Definition at line 86 of file ActionEntity.java.
References newtonERP.module.Module.getAction(), modules.taskModule.entityDefinitions.ActionEntity.getActionName(), modules.taskModule.entityDefinitions.ModuleEntity.getModule(), and modules.taskModule.entityDefinitions.ActionEntity.getModuleEntity().
String modules.taskModule.entityDefinitions.ActionEntity.getActionName ()
Returns:
nom de l'action
Definition at line 105 of file ActionEntity.java.
References newtonERP.module.AbstractEntity.getDataString().
Referenced by modules.taskModule.entityDefinitions.ActionEntity.getAction(), and modules.taskModule.entityDefinitions.ActionEntity.getBaseAction().
BaseAction modules.taskModule.entityDefinitions.ActionEntity.getBaseAction (AbstractOrmEntity entity)
Parameters:
entity entité
Returns:
base action correspondant à la définition d'entité
Definition at line 114 of file ActionEntity.java.
References modules.taskModule.entityDefinitions.ActionEntity.getActionName().
final ListViewerData modules.taskModule.entityDefinitions.ActionEntity.getList (Hashtable< String, String > parameters)
Parameters:
parameters parametres de sélection (à venir)
Returns:
une liste d'entité de ce type
Reimplemented from newtonERP.module.AbstractOrmEntity.
Definition at line 66 of file ActionEntity.java.
References newtonERP.viewers.viewerData.GridViewerData.addSpecificActionButtonList(), newtonERP.module.AbstractOrmEntity.getPrimaryKeyName(), newtonERP.module.AbstractOrmEntity.getVisibleName(), and newtonERP.viewers.viewerData.BaseViewerData.removeGlobalActions().
ModuleEntity modules.taskModule.entityDefinitions.ActionEntity.getModuleEntity ()
Returns:
module entity
Definition at line 96 of file ActionEntity.java.
References newtonERP.module.AbstractOrmEntity.getForeignKeyName(), and newtonERP.module.AbstractOrmEntity.getSingleAccessor().
Referenced by modules.taskModule.entityDefinitions.ActionEntity.getAction().
Fields modules.taskModule.entityDefinitions.ActionEntity.initFields () [virtual]
initialise les champ de l'entity, doit etre overider si l'entity contient des champs, sinon initialise une liste de champ vide
Returns:
le Fields initialiser
Implements newtonERP.module.AbstractOrmEntity.
Definition at line 37 of file ActionEntity.java.
References newtonERP.module.AbstractOrmEntity.getForeignKeyName(), and newtonERP.module.AbstractOrmEntity.getPrimaryKeyName().
The documentation for this class was generated from the following file:
src/modules/taskModule/entityDefinitions/ActionEntity.java