Bee ERP: newtonERP.orm.Orm Class Reference
newtonERP.orm.Orm Class Reference
Basic class for the orm.
Static Public Member Functions
static AbstractOrmEntity getOrCreateEntity (AbstractOrmEntity entityAsType, String fieldName, String fieldValue)
static AbstractOrmEntity getOrCreateEntity (AbstractOrmEntity entityAsType, String fieldName1, String fieldValue1, String fieldName2, String fieldValue2)
static void delete (AbstractOrmEntity entityAsType, String fieldName1, String fieldValue1, String fieldName2, String fieldValue2)
static Vector< AbstractOrmEntity > select (AbstractOrmEntity searchEntity, Vector< String > searchParameters, int limit, int offset, String orderBy)
static boolean isEntityExists (String entitySystemName)
static Vector< AbstractOrmEntity > select (AbstractOrmEntity searchEntity, Vector< String > searchCriteriasParam, int limit, int offset)
static int count (AbstractOrmEntity searchEntity)
static int count (AbstractOrmEntity searchEntity, Vector< String > searchParameterList)
static void createIndex (AbstractOrmEntity entity, Field<?> field)
Sert à ajouter un index dans la table SQL de l'entité pour un field en particulier.
static void createIndex (String entityName, String fieldName)
Sert à ajouter un index dans la table SQL de l'entité pour un field en particulier.
static void connect ()
Used to initialize the connection.
static void disconnect ()
Used to disconnect from the db.
static void executeCustomQuery (String sqlQuery)
To execute a custom query.
static Vector< AbstractOrmEntity > select (AbstractOrmEntity searchEntity, Vector< String > searchCriteriasParam)
Use only for complex queries.
static Vector< AbstractOrmEntity > select (Vector< AbstractOrmEntity > searchEntities)
Uses the new where builder.
static Vector< AbstractOrmEntity > select (AbstractOrmEntity searchEntity)
static AbstractOrmEntity selectUnique (AbstractOrmEntity searchEntity)
Select.
static AbstractOrmEntity selectUnique (Vector< AbstractOrmEntity > searchEntities)
Select.
static int insert (AbstractOrmEntity newEntity)
Method used to insert an entity in the databse based into the entity passed in parameter.
static int insertUnique (AbstractOrmEntity newUniqueEntity)
Insert an entity if no entity matches current field.
static void delete (AbstractOrmEntity searchEntity, Vector< String > searchCriterias)
Method used to delete an entity from the database.
static void delete (Vector< AbstractOrmEntity > searchEntities)
Uses the new where builder.
static void delete (AbstractOrmEntity searchEntity)
Using new where builder.
static void update (AbstractOrmEntity entityContainingChanges, Vector< String > searchCriterias)
Method used to update / change an entity.
static void update (Vector< AbstractOrmEntity > searchEntities, AbstractOrmEntity entityContainingChanges)
Uses the new where builder.
static void updateUnique (AbstractOrmEntity searchEntity, AbstractOrmEntity entityContainingChanges)
Uses the new where builder.
static ResultSet addColumnToTable (AbstractOrmEntity entity, Field<?> field)
Alter table.
static void createNonExistentTables ()
Creates the non-existent table from the modules in the database.
static void doBackupIfTimeIntervalAllows ()
Fait un backup de la DB si l'intervale de temps est assez grande.
Detailed Description
Basic class for the orm.
It is used to put the objects in the databse using a sgdb and its java binding. The orm will receive an entity from which the orm will perform various tasks such as generating the query and executing it obviously. Then it's gonna send the query to the SgbdSqlite class to execute it.
http://www.sqlite.org/lang_keywords.html
TODO: Drop a module (maybe a an array of the entities to drop?)
Author:
r3hallejo, r3lacasgu
Definition at line 25 of file Orm.java.
Member Function Documentation
static ResultSet newtonERP.orm.Orm.addColumnToTable (AbstractOrmEntity entity, Field<?> field) [static]
Alter table.
Parameters:
entity the entity containing the new field
field the field to add
Returns:
?
Definition at line 422 of file Orm.java.
References newtonERP.orm.sgbd.AbstractSgbd.addColumnToTable().
static int newtonERP.orm.Orm.count (AbstractOrmEntity searchEntity) [static]
Parameters:
searchEntity entité de recherche
Returns:
nombre d'occurence du type de l'entité de recherche
Definition at line 154 of file Orm.java.
static int newtonERP.orm.Orm.count (AbstractOrmEntity searchEntity, Vector< String > searchParameterList) [static]
Parameters:
searchEntity entité de recherche
searchParameterList liste de paramètres de recherche
Returns:
nombre d'occurence du type de l'entité de recherche
Definition at line 165 of file Orm.java.
References newtonERP.orm.sgbd.AbstractSgbd.count().
static void newtonERP.orm.Orm.createIndex (AbstractOrmEntity entity, Field<?> field) [static]
Sert à ajouter un index dans la table SQL de l'entité pour un field en particulier.
Parameters:
entity entité
field champ
Definition at line 177 of file Orm.java.
References newtonERP.module.AbstractEntity.getSystemName().
static void newtonERP.orm.Orm.createIndex (String entityName, String fieldName) [static]
Sert à ajouter un index dans la table SQL de l'entité pour un field en particulier.
Parameters:
entityName nom de l'entité
fieldName nom du field
Definition at line 188 of file Orm.java.
References newtonERP.orm.sgbd.AbstractSgbd.createIndex().
static void newtonERP.orm.Orm.delete (AbstractOrmEntity searchEntity, Vector< String > searchCriterias) [static]
Method used to delete an entity from the database.
Parameters:
searchEntity the entity to be researched
searchCriterias the search criterias for the where clause
Definition at line 338 of file Orm.java.
References newtonERP.orm.sgbd.AbstractSgbd.delete().
static void newtonERP.orm.Orm.delete (Vector< AbstractOrmEntity > searchEntities) [static]
Uses the new where builder.
Method used to delete an entity from the database
Parameters:
searchEntities the entities from which we will build our where clause
Definition at line 352 of file Orm.java.
References newtonERP.orm.sgbd.AbstractSgbd.delete().
static void newtonERP.orm.Orm.delete (AbstractOrmEntity searchEntity) [static]
Using new where builder.
Method used to delete an entity from the database
Parameters:
searchEntity the entity from which we will build our where
Definition at line 364 of file Orm.java.
static void newtonERP.orm.Orm.delete (AbstractOrmEntity entityAsType, String fieldName1, String fieldValue1, String fieldName2, String fieldValue2) [static]
Parameters:
entityAsType entité en tant que référence de type ou entité vide pour ajouter des champs
fieldName1 key1
fieldValue1 value1
fieldName2 key2
fieldValue2 value2
Definition at line 93 of file Orm.java.
References newtonERP.module.AbstractEntity.setData().
static void newtonERP.orm.Orm.executeCustomQuery (String sqlQuery) [static]
To execute a custom query.
Parameters:
sqlQuery the executed
Definition at line 214 of file Orm.java.
References newtonERP.orm.sgbd.AbstractSgbd.execute().
static AbstractOrmEntity newtonERP.orm.Orm.getOrCreateEntity (AbstractOrmEntity entityAsType, String fieldName1, String fieldValue1, String fieldName2, String fieldValue2) [static]
Parameters:
entityAsType entity as a type reference or empty entity to fill
fieldName1 key1
fieldValue1 value2
fieldName2 key2
fieldValue2 value2
Returns:
new entity or found entity
Definition at line 66 of file Orm.java.
References newtonERP.module.AbstractOrmEntity.get(), newtonERP.module.AbstractOrmEntity.newE(), and newtonERP.module.AbstractEntity.setData().
static AbstractOrmEntity newtonERP.orm.Orm.getOrCreateEntity (AbstractOrmEntity entityAsType, String fieldName, String fieldValue) [static]
Parameters:
entityAsType entity as a type reference or empty entity to fill data from orm
fieldName key
fieldValue value
Returns:
new entity or found entity
Definition at line 41 of file Orm.java.
References newtonERP.module.AbstractOrmEntity.get(), newtonERP.module.AbstractOrmEntity.newE(), and newtonERP.module.AbstractEntity.setData().
static int newtonERP.orm.Orm.insert (AbstractOrmEntity newEntity) [static]
Method used to insert an entity in the databse based into the entity passed in parameter.
Parameters:
newEntity the entity to add
Returns:
le id de clé primaire ajoutée
Definition at line 301 of file Orm.java.
References newtonERP.orm.sgbd.AbstractSgbd.insert().
Referenced by newtonERP.orm.Orm.insertUnique().
static int newtonERP.orm.Orm.insertUnique (AbstractOrmEntity newUniqueEntity) [static]
Insert an entity if no entity matches current field.
Parameters:
newUniqueEntity New unique entity to insert
Returns:
le id de clé primaire ajoutée ou qui avais déja été inséré
Definition at line 318 of file Orm.java.
References newtonERP.orm.Orm.insert(), and newtonERP.orm.Orm.select().
static boolean newtonERP.orm.Orm.isEntityExists (String entitySystemName) [static]
Parameters:
entitySystemName nom système d'une entité
Returns:
true si l'entité a une table dans la base de donnée, sinon false
Definition at line 131 of file Orm.java.
References newtonERP.orm.sgbd.AbstractSgbd.isEntityExists().
static Vector<AbstractOrmEntity> newtonERP.orm.Orm.select (AbstractOrmEntity searchEntity) [static]
Parameters:
searchEntity the single search entity
Returns:
the entities that have been selected in the db
Definition at line 261 of file Orm.java.
References newtonERP.orm.Orm.select().
static Vector<AbstractOrmEntity> newtonERP.orm.Orm.select (AbstractOrmEntity searchEntity, Vector< String > searchParameters, int limit, int offset, String orderBy) [static]
Parameters:
searchEntity entité
searchParameters critère de recherche
limit limite
offset offset
orderBy ordre
Returns:
liste d'entité
Definition at line 118 of file Orm.java.
Referenced by newtonERP.orm.Orm.insertUnique(), newtonERP.orm.Orm.select(), and newtonERP.orm.Orm.selectUnique().
static Vector<AbstractOrmEntity> newtonERP.orm.Orm.select (AbstractOrmEntity searchEntity, Vector< String > searchCriteriasParam) [static]
Use only for complex queries.
Use the select that takes only a vector of entities instead
Method used to do search queries done from the views to the databse. The search criterias that has been passed in parameter are a list of string that has been generated by the view modules
Parameters:
searchEntity the entity that has to be researched
searchCriteriasParam the search criterias formatted into strings
Returns:
a vector of ormizable entities
Definition at line 232 of file Orm.java.
References newtonERP.orm.Orm.select().
static Vector<AbstractOrmEntity> newtonERP.orm.Orm.select (AbstractOrmEntity searchEntity, Vector< String > searchCriteriasParam, int limit, int offset) [static]
Parameters:
searchEntity entité de recherche
searchCriteriasParam critères de recherche
limit limite de résultats
offset offset de début de résultats
Returns:
liste d'entités trouvées
Definition at line 143 of file Orm.java.
References newtonERP.orm.Orm.select().
static Vector<AbstractOrmEntity> newtonERP.orm.Orm.select (Vector< AbstractOrmEntity > searchEntities) [static]
Uses the new where builder.
Method used to do search queries done from the views to the databse. The search criterias that has been passed in parameter are a list of string that has been generated by the view modules
Parameters:
searchEntities the entities from which we will perform the search
Returns:
the entities
Definition at line 250 of file Orm.java.
References newtonERP.orm.Orm.select().
static AbstractOrmEntity newtonERP.orm.Orm.selectUnique (AbstractOrmEntity searchEntity) [static]
Select.
Use only if you are sure that it will return only 1 entity (or that you want the first entity)
Parameters:
searchEntity the entity from which we will perform our search
Returns:
the first entity from the result set
Definition at line 276 of file Orm.java.
References newtonERP.orm.Orm.select().
static AbstractOrmEntity newtonERP.orm.Orm.selectUnique (Vector< AbstractOrmEntity > searchEntities) [static]
Select.
Use only if you are sure that it will return only 1 entity (or that you want the first entity)
Parameters:
searchEntities the entity from which we will perform our search
Returns:
the first entity from the result set
Definition at line 288 of file Orm.java.
References newtonERP.orm.Orm.select().
static void newtonERP.orm.Orm.update (AbstractOrmEntity entityContainingChanges, Vector< String > searchCriterias) [static]
Method used to update / change an entity.
Parameters:
entityContainingChanges the entity that has been changed and will be in the orm
searchCriterias the criterias used by the update
Definition at line 379 of file Orm.java.
References newtonERP.orm.sgbd.AbstractSgbd.update().
static void newtonERP.orm.Orm.update (Vector< AbstractOrmEntity > searchEntities, AbstractOrmEntity entityContainingChanges) [static]
Uses the new where builder.
Method used to update / change an entity
Parameters:
searchEntities the entities from which we will build our where clause
entityContainingChanges the changes to apply
Definition at line 394 of file Orm.java.
References newtonERP.orm.sgbd.AbstractSgbd.update().
static void newtonERP.orm.Orm.updateUnique (AbstractOrmEntity searchEntity, AbstractOrmEntity entityContainingChanges) [static]
Uses the new where builder.
Method used to update / change an entity
Parameters:
searchEntity the entities from which we will build our where clause
entityContainingChanges the changes to apply
Definition at line 409 of file Orm.java.
References newtonERP.orm.sgbd.AbstractSgbd.updateUnique().
The documentation for this class was generated from the following file:
src/newtonERP/orm/Orm.java