Bee ERP: newtonERP.orm.field.Fields Class Reference
newtonERP.orm.field.Fields Class Reference
All the fields of an entity.
Inherited by newtonERP.orm.field.VolatileFields.
Public Member Functions
Fields ()
constructeur vide, permet de construire un Fields sans aucun champ
Fields (Vector< Field<?>> fields)
Collection< Field<?> > getFields ()
Field<?> getField (String shortName)
void setData (String shortName, Object data)
methode pour changer la valeur d'un champ
void setFromHashTable (Hashtable< String,?> parameters)
boolean equals (Object obj)
String toString ()
Iterator< Field<?> > iterator ()
iterate over the fields (not the keys)
Collection< String > getKeyList ()
Collection< String > getLongFieldNameList ()
void setDefaultValue (boolean allField)
met les valeur par defaut dans les field pour ne pas avoir de valeur null
void setDefaultValue ()
identique a setDefaultValue(true);
boolean containsFieldName (String fieldName)
boolean containsValues ()
boolean isErrorState ()
void setErrorState (boolean errorState)
void reset ()
remet les valeur a null
Package Attributes
Hashtable< String, Field<?> > fieldsDataMap
Collection< Field<?> > fieldsDataVector
boolean ErrorState = false
Detailed Description
All the fields of an entity.
Author:
CloutierJo
Definition at line 15 of file Fields.java.
Constructor & Destructor Documentation
newtonERP.orm.field.Fields.Fields (Vector< Field<?>> fields)
Parameters:
fields une liste de champ a inclure dans le Fields
Definition at line 34 of file Fields.java.
Member Function Documentation
boolean newtonERP.orm.field.Fields.containsFieldName (String fieldName)
Parameters:
fieldName nom du champ
Returns:
true si nom du champ existe dans les fields
Definition at line 202 of file Fields.java.
Referenced by newtonERP.module.AbstractOrmEntity.assign().
boolean newtonERP.orm.field.Fields.containsValues ()
Returns:
true si au moins un field n'a pas une valeur null, sinon false
Definition at line 210 of file Fields.java.
Field<?> newtonERP.orm.field.Fields.getField (String shortName)
Parameters:
shortName le nom du champ voulu
Returns:
the named field
Definition at line 59 of file Fields.java.
Referenced by newtonERP.module.AbstractEntity.getData(), newtonERP.module.AbstractEntity.getDataString(), modules.userRightModule.entityDefinitions.GroupsRight.getGroupsEntity(), newtonERP.module.AbstractOrmEntity.getInputValue(), newtonERP.module.AbstractEntity.getLabelName(), newtonERP.module.AbstractOrmEntity.getNaturalKeyName(), newtonERP.module.AbstractOrmEntity.getPrimaryKeyValue(), modules.userRightModule.entityDefinitions.GroupsRight.getRightEntity(), and newtonERP.module.AbstractEntity.isMatchCheckBox().
Collection<Field<?> > newtonERP.orm.field.Fields.getFields ()
Returns:
the fields
Definition at line 50 of file Fields.java.
Referenced by newtonERP.orm.field.Fields.setDefaultValue().
Collection<String> newtonERP.orm.field.Fields.getKeyList ()
Returns:
Liste des clefs des fields
Definition at line 155 of file Fields.java.
Referenced by newtonERP.module.AbstractOrmEntity.getList().
Collection<String> newtonERP.orm.field.Fields.getLongFieldNameList ()
Returns:
Liste des nom utilisateur des fields
Definition at line 163 of file Fields.java.
boolean newtonERP.orm.field.Fields.isErrorState ()
Returns:
the errorState
Definition at line 221 of file Fields.java.
Referenced by newtonERP.module.AbstractOrmEntity.editUI().
void newtonERP.orm.field.Fields.setData (String shortName, Object data)
methode pour changer la valeur d'un champ
Parameters:
shortName nom du champ
data valeur modifie
Definition at line 70 of file Fields.java.
Referenced by modules.userRightModule.entityDefinitions.GroupsRight.getRightEntity(), modules.userRightModule.entityDefinitions.GroupsRight.GroupsRight(), newtonERP.module.AbstractEntity.setData(), and newtonERP.orm.field.Fields.setFromHashTable().
void newtonERP.orm.field.Fields.setDefaultValue (boolean allField)
met les valeur par defaut dans les field pour ne pas avoir de valeur null
*ATTENTION* NE PAS UTILISE UNE ENTITY COMME SEARCHCRITERIA APRES AVOIR UTILISER CETTE FONCTION
Parameters:
allField true pour mettre tous les champ a leur valeur par defaut false pour ne mettre les valeurpar defaut qu'au field n'étant pas settez
Definition at line 181 of file Fields.java.
References newtonERP.orm.field.Fields.getFields().
Referenced by newtonERP.module.AbstractOrmEntity.newUI(), and modules.taskModule.entityDefinitions.FieldEntity.newUI().
void newtonERP.orm.field.Fields.setErrorState (boolean errorState)
Parameters:
errorState the errorState to set
Definition at line 229 of file Fields.java.
void newtonERP.orm.field.Fields.setFromHashTable (Hashtable< String,?> parameters)
Parameters:
parameters Hashtable de parametre
Definition at line 88 of file Fields.java.
References newtonERP.orm.field.Fields.setData().
Referenced by newtonERP.module.Module.doAction(), newtonERP.module.AbstractAction.perform(), and newtonERP.module.AbstractOrmEntity.setOrmizableData().
The documentation for this class was generated from the following file:
src/newtonERP/orm/field/Fields.java