Bee ERP: newtonERP.viewers.viewerData.PromptViewerData Class Reference
newtonERP.viewers.viewerData.PromptViewerData Class Reference
data du promptViewer
Inherits newtonERP::viewers::viewerData::BaseViewerData.
Inherited by newtonERP.module.generalEntity.Form.
Public Member Functions
PromptViewerData ()
default constructor
ActionLink getButtonAction ()
void setButtonAction (ActionLink buttonAction)
void setData (AbstractEntity data)
AbstractEntity getData ()
boolean isMatchCheckBox (String inputName)
ListOfValue tryMatchListOfValue (String fieldKeyName)
Hashtable< String, FlagPool > getPositiveFlagPoolList ()
String getInputValue (String inputName)
Retourne la valeur actuelle d'un champ.
String getLabelName (String inputName)
AbstractAction getCurrentAction ()
Module getCurrentModule ()
void setReadOnly (boolean isReadOnly)
boolean isReadOnly ()
Detailed Description
data du promptViewer
Author:
CloutierJo
Definition at line 16 of file PromptViewerData.java.
Member Function Documentation
ActionLink newtonERP.viewers.viewerData.PromptViewerData.getButtonAction ()
Returns:
nom du bouton "ok"
Definition at line 33 of file PromptViewerData.java.
Referenced by newtonERP.viewers.firstStep.PromptViewer.getHtmlCode().
AbstractAction newtonERP.viewers.viewerData.PromptViewerData.getCurrentAction ()
Returns:
the current action
Reimplemented from newtonERP.module.AbstractEntity.
Definition at line 113 of file PromptViewerData.java.
Module newtonERP.viewers.viewerData.PromptViewerData.getCurrentModule ()
Returns:
the current module
Reimplemented from newtonERP.module.AbstractEntity.
Definition at line 121 of file PromptViewerData.java.
AbstractEntity newtonERP.viewers.viewerData.PromptViewerData.getData ()
Returns:
the data
Definition at line 59 of file PromptViewerData.java.
Referenced by newtonERP.module.generalEntity.Form.addField(), and newtonERP.viewers.firstStep.PromptViewer.getHtmlCode().
String newtonERP.viewers.viewerData.PromptViewerData.getInputValue (String inputName)
Retourne la valeur actuelle d'un champ.
Parameters:
inputName nom du champ
Returns:
valeur contenue dans le champ
Definition at line 96 of file PromptViewerData.java.
String newtonERP.viewers.viewerData.PromptViewerData.getLabelName (String inputName)
Parameters:
inputName nom d'un field
Returns:
nom complete d'un field
Reimplemented from newtonERP.module.AbstractEntity.
Definition at line 105 of file PromptViewerData.java.
Hashtable<String, FlagPool> newtonERP.viewers.viewerData.PromptViewerData.getPositiveFlagPoolList ()
Returns:
the flag pool list
Definition at line 86 of file PromptViewerData.java.
boolean newtonERP.viewers.viewerData.PromptViewerData.isMatchCheckBox (String inputName)
Parameters:
inputName nom du champ
Returns:
is le champ est un check box (bool)
Reimplemented from newtonERP.module.AbstractEntity.
Definition at line 69 of file PromptViewerData.java.
boolean newtonERP.viewers.viewerData.PromptViewerData.isReadOnly ()
Returns:
si entité est présentement readonly
Definition at line 138 of file PromptViewerData.java.
void newtonERP.viewers.viewerData.PromptViewerData.setButtonAction (ActionLink buttonAction)
Parameters:
buttonAction nom du bouton "ok"
Definition at line 41 of file PromptViewerData.java.
Referenced by modules.userRightModule.actions.Login.doAction(), and newtonERP.module.AbstractOrmEntity.editUI().
void newtonERP.viewers.viewerData.PromptViewerData.setData (AbstractEntity data)
Parameters:
data the data to set
Definition at line 49 of file PromptViewerData.java.
References newtonERP.module.AbstractEntity.getSystemName(), newtonERP.viewers.viewerData.BaseViewerData.getTitle(), and newtonERP.viewers.viewerData.BaseViewerData.setTitle().
Referenced by newtonERP.module.AbstractOrmEntity.editUI(), and newtonERP.module.generalEntity.Form.Form().
void newtonERP.viewers.viewerData.PromptViewerData.setReadOnly (boolean isReadOnly)
Parameters:
isReadOnly si entité est présentement readonly dans le contexte actuel
Definition at line 130 of file PromptViewerData.java.
Referenced by newtonERP.module.AbstractOrmEntity.editUI().
ListOfValue newtonERP.viewers.viewerData.PromptViewerData.tryMatchListOfValue (String fieldKeyName)
Parameters:
fieldKeyName the field key name
Returns:
If list of value exist, return it, else, return null
Reimplemented from newtonERP.module.AbstractEntity.
Definition at line 78 of file PromptViewerData.java.
The documentation for this class was generated from the following file:
src/newtonERP/viewers/viewerData/PromptViewerData.java