Bee ERP: newtonERP.viewers.firstStep.PromptViewer Class Reference
newtonERP.viewers.firstStep.PromptViewer Class Reference
Represents the prompt viewer.
Static Public Member Functions
static String getHtmlCode (PromptViewerData promptData)
Return the html code for the web page.
Detailed Description
Represents the prompt viewer.
Author:
Guillaume Lacasse, Pascal Lemay
Definition at line 26 of file PromptViewer.java.
Member Function Documentation
static String newtonERP.viewers.firstStep.PromptViewer.getHtmlCode (PromptViewerData promptData) [static]
Return the html code for the web page.
Parameters:
promptData the entity to view
Returns:
html
Definition at line 33 of file PromptViewer.java.
References newtonERP.viewers.viewerData.PromptViewerData.getButtonAction(), newtonERP.viewers.viewerData.BaseViewerData.getComplementaryInfoLineList(), newtonERP.viewers.viewerData.PromptViewerData.getData(), newtonERP.module.AbstractEntity.getFields(), newtonERP.module.AbstractOrmEntity.getGateWayList(), newtonERP.common.ActionLink.getName(), newtonERP.module.AbstractOrmEntity.getNaturalKeyDescription(), newtonERP.module.AbstractOrmEntity.getNaturalKeyName(), newtonERP.module.AbstractOrmEntity.getPositiveFlagPoolList(), newtonERP.module.AbstractOrmEntity.getPrimaryKeyName(), newtonERP.module.AbstractOrmEntity.getPrimaryKeyValue(), newtonERP.common.ActionLink.getUrlParam(), and newtonERP.module.AbstractEntity.tryMatchListOfValue().
The documentation for this class was generated from the following file:
src/newtonERP/viewers/firstStep/PromptViewer.java