Bee ERP: modules.userRightModule.actions.CreateAllRight Class Reference
modules.userRightModule.actions.CreateAllRight Class Reference
Action class that creates all the rights for every module.
Inherits newtonERP::module::AbstractAction.
Public Member Functions
CreateAllRight ()
constructeur
AbstractEntity doAction (AbstractEntity entity, Hashtable< String, String > parameters)
Abstract method that will be reused by all the actions.
Detailed Description
Action class that creates all the rights for every module.
Author:
cloutierJo
Definition at line 17 of file CreateAllRight.java.
Member Function Documentation
AbstractEntity modules.userRightModule.actions.CreateAllRight.doAction (AbstractEntity entity, Hashtable< String, String > parameters) [virtual]
Abstract method that will be reused by all the actions.
Parameters:
entity entite a utiliser a l'intérieur du doAction
parameters list de parametre autre que l'entite
Returns:
l'entite resultante
Implements newtonERP.module.AbstractAction.
Definition at line 27 of file CreateAllRight.java.
References newtonERP.module.Module.getActionList(), newtonERP.module.Module.getEntityDefinitionList(), newtonERP.module.Module.initDB(), and newtonERP.module.AbstractEntity.setData().
The documentation for this class was generated from the following file:
src/modules/userRightModule/actions/CreateAllRight.java