Bee ERP: newtonERP.common.ListModule Class Reference
newtonERP.common.ListModule Class Reference
pour créé le jar il faut, en ligne de commande, allé dans le dossier du javaSDK/bin et faire la commande suivant jar cf0 chemin:.jar chemin: attention de mettre le nom du jarFile en majuscule ex: jar cf0 J:.jar J:
Static Public Member Functions
static void addModule (String moduleName, String path)
ajoute un module a la liste
static void removeModule (String moduleName)
retire un module de la liste
static Set< String > getAllModules ()
permet d'avoir la liste de tout les modules du programe
static Module getModule (String moduleName)
retourne le module de nom moduleName
static void initAllModule ()
initialise la liste de module
Detailed Description
pour créé le jar il faut, en ligne de commande, allé dans le dossier du javaSDK/bin et faire la commande suivant jar cf0 chemin:.jar chemin: attention de mettre le nom du jarFile en majuscule ex: jar cf0 J:.jar J:
Author:
Gabriel Therrien JoCloutier
Definition at line 25 of file ListModule.java.
Member Function Documentation
static void newtonERP.common.ListModule.addModule (String moduleName, String path) [static]
ajoute un module a la liste
Parameters:
moduleName le nom du module a ajoute
path system path to the module
Definition at line 36 of file ListModule.java.
References newtonERP.common.FileModule.getName().
Referenced by newtonERP.common.ListModule.initAllModule().
static Set<String> newtonERP.common.ListModule.getAllModules () [static]
permet d'avoir la liste de tout les modules du programe
Returns:
liste de tout les modules
Definition at line 57 of file ListModule.java.
static Module newtonERP.common.ListModule.getModule (String moduleName) [static]
retourne le module de nom moduleName
Parameters:
moduleName nom du module
Returns:
le module
Definition at line 68 of file ListModule.java.
References newtonERP.module.Module.initAction(), and newtonERP.module.Module.initEntityDefinition().
static void newtonERP.common.ListModule.removeModule (String moduleName) [static]
retire un module de la liste
Parameters:
moduleName nom du module a retirer
Definition at line 47 of file ListModule.java.
The documentation for this class was generated from the following file:
src/newtonERP/common/ListModule.java