Bee ERP: newtonERP.module.AbstractAction Class Reference
newtonERP.module.AbstractAction Class Reference
Inherited by modules.taskModule.actions.AddFieldToOrm, modules.taskModule.actions.DbGraph, modules.taskModule.actions.GenerateActionCode, modules.taskModule.actions.GenerateEntityCode, modules.taskModule.actions.GenerateSourceCode, modules.taskModule.actions.ViewActionSource, modules.taskModule.actions.ViewEntitySource, modules.taskModule.actions.ViewModuleSource, modules.userRightModule.actions.CreateAllRight, modules.userRightModule.actions.Login, modules.userRightModule.actions.Logout, modules.userRightModule.actions.RightCheck, and newtonERP.module.BaseAction.
Public Member Functions
final AbstractEntity perform (Hashtable< String, String > parameters)
Abstract method that will be used to perform the actions.
abstract AbstractEntity doAction (AbstractEntity entity, Hashtable< String, String > parameters)
Abstract method that will be reused by all the actions.
AbstractEntity getEntityUsable ()
void setOwnedByModul (Module ownedByModul)
Module getOwnedByModule ()
boolean equals (Object obj)
String getSystemName ()
String getDetailedDescription ()
void setDetailedDescription (String detailedDescription)
Protected Member Functions
AbstractAction (AbstractEntity entityUsable)
Default constructor for the action.
Detailed Description
Author:
r3lacasgu cloutierJo
Class representing an abstract action
Definition at line 10 of file AbstractAction.java.
Constructor & Destructor Documentation
newtonERP.module.AbstractAction.AbstractAction (AbstractEntity entityUsable) [protected]
Default constructor for the action.
Parameters:
entityUsable le type d'entité qui sera utiliser par la methode
Definition at line 25 of file AbstractAction.java.
Member Function Documentation
abstract AbstractEntity newtonERP.module.AbstractAction.doAction (AbstractEntity entity, Hashtable< String, String > parameters) [pure virtual]
Abstract method that will be reused by all the actions.
Parameters:
entity entite a utiliser a l'intérieur du doAction
parameters list de parametre autre que l'entite
Returns:
l'entite resultante
Implemented in modules.taskModule.actions.AddFieldToOrm, modules.taskModule.actions.DbGraph, modules.taskModule.actions.GenerateActionCode, modules.taskModule.actions.GenerateEntityCode, modules.taskModule.actions.GenerateSourceCode, modules.taskModule.actions.ViewActionSource, modules.taskModule.actions.ViewEntitySource, modules.taskModule.actions.ViewModuleSource, modules.userRightModule.actions.CreateAllRight, modules.userRightModule.actions.Login, modules.userRightModule.actions.Logout, and modules.userRightModule.actions.RightCheck.
Referenced by newtonERP.module.AbstractAction.perform().
String newtonERP.module.AbstractAction.getDetailedDescription ()
Returns:
description détaillée facultative
Definition at line 135 of file AbstractAction.java.
AbstractEntity newtonERP.module.AbstractAction.getEntityUsable ()
Returns:
the entityUsable
Definition at line 76 of file AbstractAction.java.
Referenced by modules.userRightModule.UserRightModule.isPermissionAllowed().
Module newtonERP.module.AbstractAction.getOwnedByModule ()
Returns:
the ownedByModul
Definition at line 92 of file AbstractAction.java.
Referenced by newtonERP.serveur.Servlet.makeLink().
String newtonERP.module.AbstractAction.getSystemName ()
Returns:
nom de l'action dans le système (normalement nom de la classe mais peut être overridé si c'est une action dynamique)
Reimplemented in newtonERP.module.BaseAction.
Definition at line 127 of file AbstractAction.java.
Referenced by modules.userRightModule.UserRightModule.isPermissionAllowed(), and newtonERP.serveur.Servlet.makeLink().
final AbstractEntity newtonERP.module.AbstractAction.perform (Hashtable< String, String > parameters)
Abstract method that will be used to perform the actions.
Parameters:
parameters list de parametre utilisable par l'action, une partie d'entre eux sera transforme en entite
Returns:
l,entite resultante de l'action
Definition at line 37 of file AbstractAction.java.
References newtonERP.module.AbstractAction.doAction(), newtonERP.module.AbstractEntity.getFields(), and newtonERP.orm.field.Fields.setFromHashTable().
Referenced by newtonERP.module.Module.doAction().
void newtonERP.module.AbstractAction.setDetailedDescription (String detailedDescription)
Parameters:
detailedDescription description détaillée facultative
Definition at line 143 of file AbstractAction.java.
Referenced by newtonERP.module.BaseAction.BaseAction(), modules.userRightModule.actions.Login.Login(), and modules.userRightModule.actions.Logout.Logout().
void newtonERP.module.AbstractAction.setOwnedByModul (Module ownedByModul)
Parameters:
ownedByModul the ownedByModul to set
Definition at line 84 of file AbstractAction.java.
The documentation for this class was generated from the following file:
src/newtonERP/module/AbstractAction.java