Bee ERP: modules.userRightModule.entityDefinitions.GroupsRight Class Reference
modules.userRightModule.entityDefinitions.GroupsRight Class Reference
Entity defenition representing a group right for the users.
Inherits newtonERP::module::AbstractOrmEntity.
Public Member Functions
GroupsRight (Groups groups, Right right)
Fields initFields ()
initialise les champ de l'entity, doit etre overider si l'entity contient des champs, sinon initialise une liste de champ vide
Groups getGroupsEntity ()
permet d'obtenir directement l'entity groups lie a cet user
Right getRightEntity ()
permet d'obtenir directement l'entity Right lier a cet user
Detailed Description
Entity defenition representing a group right for the users.
Author:
CloutierJo
Definition at line 15 of file GroupsRight.java.
Constructor & Destructor Documentation
modules.userRightModule.entityDefinitions.GroupsRight.GroupsRight (Groups groups, Right right)
Parameters:
groups ID du groupe
right ID du droit
Definition at line 31 of file GroupsRight.java.
References newtonERP.module.AbstractEntity.getFields(), newtonERP.module.AbstractOrmEntity.getPrimaryKeyValue(), and newtonERP.orm.field.Fields.setData().
Member Function Documentation
Groups modules.userRightModule.entityDefinitions.GroupsRight.getGroupsEntity ()
permet d'obtenir directement l'entity groups lie a cet user
Returns:
le group lier
Definition at line 53 of file GroupsRight.java.
References newtonERP.orm.field.Fields.getField(), newtonERP.module.AbstractEntity.getFields(), and newtonERP.module.AbstractOrmEntity.getPrimaryKeyName().
Right modules.userRightModule.entityDefinitions.GroupsRight.getRightEntity ()
permet d'obtenir directement l'entity Right lier a cet user
Returns:
le Right lier
Definition at line 70 of file GroupsRight.java.
References newtonERP.orm.field.Fields.getField(), newtonERP.module.AbstractEntity.getFields(), newtonERP.module.AbstractOrmEntity.getPrimaryKeyName(), and newtonERP.orm.field.Fields.setData().
Fields modules.userRightModule.entityDefinitions.GroupsRight.initFields () [virtual]
initialise les champ de l'entity, doit etre overider si l'entity contient des champs, sinon initialise une liste de champ vide
Returns:
le Fields initialiser
Implements newtonERP.module.AbstractOrmEntity.
Definition at line 40 of file GroupsRight.java.
The documentation for this class was generated from the following file:
src/modules/userRightModule/entityDefinitions/GroupsRight.java