Bee ERP: newtonERP.sourceCodeBuilder.ModuleSourceCodeBuilder Class Reference
newtonERP.sourceCodeBuilder.ModuleSourceCodeBuilder Class Reference
Cette classe sert à construire le code source de module.
Static Public Member Functions
static String build (ModuleEntity moduleEntity)
static String buildClassFileName (ModuleEntity moduleEntity)
static String getPackagePath (ModuleEntity moduleEntity)
static void createDirectories (ModuleEntity moduleEntity)
Static Protected Member Functions
static String getPackageName (ModuleEntity moduleEntity)
Detailed Description
Cette classe sert à construire le code source de module.
Author:
Guillaume Lacasse
Definition at line 12 of file ModuleSourceCodeBuilder.java.
Member Function Documentation
static String newtonERP.sourceCodeBuilder.ModuleSourceCodeBuilder.build (ModuleEntity moduleEntity) [static]
Parameters:
moduleEntity entité du module
Returns:
code source
Definition at line 18 of file ModuleSourceCodeBuilder.java.
static String newtonERP.sourceCodeBuilder.ModuleSourceCodeBuilder.buildClassFileName (ModuleEntity moduleEntity) [static]
Parameters:
moduleEntity module entity
Returns:
source class file name
Definition at line 75 of file ModuleSourceCodeBuilder.java.
References newtonERP.sourceCodeBuilder.ModuleSourceCodeBuilder.getPackagePath().
static void newtonERP.sourceCodeBuilder.ModuleSourceCodeBuilder.createDirectories (ModuleEntity moduleEntity) [static]
Parameters:
moduleEntity module entity
Definition at line 98 of file ModuleSourceCodeBuilder.java.
References newtonERP.sourceCodeBuilder.ModuleSourceCodeBuilder.getPackagePath().
static String newtonERP.sourceCodeBuilder.ModuleSourceCodeBuilder.getPackagePath (ModuleEntity moduleEntity) [static]
Parameters:
moduleEntity module entity
Returns:
package path
Definition at line 88 of file ModuleSourceCodeBuilder.java.
Referenced by newtonERP.sourceCodeBuilder.ModuleSourceCodeBuilder.buildClassFileName(), and newtonERP.sourceCodeBuilder.ModuleSourceCodeBuilder.createDirectories().
The documentation for this class was generated from the following file:
src/newtonERP/sourceCodeBuilder/ModuleSourceCodeBuilder.java