Bee ERP: newtonERP.orm.associations.GateWayManager Class Reference
newtonERP.orm.associations.GateWayManager Class Reference
Sert à gérer les accesseurs passant par des accesseurs.
Static Public Member Functions
static void addGateWay (AbstractOrmEntity sourceEntity, AbstractOrmEntity gateWayEntity, AbstractOrmEntity externalEntity)
static AbstractOrmEntity getExternalEntity (GateWay gateWay, AbstractOrmEntity sourceEntity)
Detailed Description
Sert à gérer les accesseurs passant par des accesseurs.
Author:
Guillaume Lacasse
Definition at line 10 of file GateWayManager.java.
Member Function Documentation
static void newtonERP.orm.associations.GateWayManager.addGateWay (AbstractOrmEntity sourceEntity, AbstractOrmEntity gateWayEntity, AbstractOrmEntity externalEntity) [static]
Parameters:
sourceEntity entité de source
gateWayEntity entité de passerelle
externalEntity entité externe
Definition at line 17 of file GateWayManager.java.
References newtonERP.module.AbstractOrmEntity.getGateWayList().
static AbstractOrmEntity newtonERP.orm.associations.GateWayManager.getExternalEntity (GateWay gateWay, AbstractOrmEntity sourceEntity) [static]
Parameters:
gateWay gateWay
sourceEntity source entity
Returns:
external entity
Definition at line 29 of file GateWayManager.java.
References newtonERP.module.AbstractEntity.getData(), newtonERP.orm.associations.GateWay.getExternalEntity(), newtonERP.module.AbstractOrmEntity.getForeignKeyName(), newtonERP.orm.associations.GateWay.getGateWayEntity(), newtonERP.module.AbstractOrmEntity.getPrimaryKeyName(), and newtonERP.module.AbstractEntity.setData().
The documentation for this class was generated from the following file:
src/newtonERP/orm/associations/GateWayManager.java