Bee ERP: newtonERP.viewers.viewerData.GridViewerData Class Reference
newtonERP.viewers.viewerData.GridViewerData Class Reference
Représente les données pouvant être visible par le grid viewer.
Inherits newtonERP::viewers::viewerData::BaseViewerData.
Inherited by newtonERP.viewers.viewerData.ListViewerData.
Public Member Functions
GridViewerData ()
s
GridCaseData[] getHeader ()
void setHeader (GridCaseData[] header)
GridCaseData[] getLeftHeader ()
void setLeftHeader (GridCaseData[] leftHeader)
GridCaseData[][] getCases ()
void setCases (GridCaseData[][] cases)
Vector< ActionLink > getSpecificActionButtonList ()
permet d'obtenir les action specifique
void setSpecificActionButtonList (Vector< ActionLink > specificActionButtonList)
void addSpecificActionButtonList (ActionLink actionLink)
void removeSpecificActions (String specificActionName)
void removeSpecificActions (ActionLink SpecificActionName)
boolean isColored ()
void setColored (boolean isColored)
boolean isSpanSimilar ()
void setSpanSimilar (boolean spanSimilar)
Detailed Description
Représente les données pouvant être visible par le grid viewer.
Author:
Guillaume
Definition at line 12 of file GridViewerData.java.
Member Function Documentation
void newtonERP.viewers.viewerData.GridViewerData.addSpecificActionButtonList (ActionLink actionLink)
Parameters:
actionLink action du bouton
Definition at line 98 of file GridViewerData.java.
Referenced by newtonERP.module.AbstractOrmEntity.getList(), modules.taskModule.entityDefinitions.ModuleEntity.getList(), modules.taskModule.entityDefinitions.FieldEntity.getList(), modules.taskModule.entityDefinitions.EntityEntity.getList(), and modules.taskModule.entityDefinitions.ActionEntity.getList().
GridCaseData [][] newtonERP.viewers.viewerData.GridViewerData.getCases ()
Returns:
the cases
Reimplemented in newtonERP.viewers.viewerData.ListViewerData.
Definition at line 64 of file GridViewerData.java.
GridCaseData [] newtonERP.viewers.viewerData.GridViewerData.getHeader ()
Returns:
the header
Reimplemented in newtonERP.viewers.viewerData.ListViewerData.
Definition at line 32 of file GridViewerData.java.
Referenced by newtonERP.viewers.firstStep.GridViewer.getHtmlCode().
GridCaseData [] newtonERP.viewers.viewerData.GridViewerData.getLeftHeader ()
Returns:
the leftHeader
Definition at line 48 of file GridViewerData.java.
Referenced by newtonERP.viewers.firstStep.GridViewer.getHtmlCode().
Vector<ActionLink> newtonERP.viewers.viewerData.GridViewerData.getSpecificActionButtonList ()
permet d'obtenir les action specifique
Returns:
liste de specificAction
Definition at line 81 of file GridViewerData.java.
boolean newtonERP.viewers.viewerData.GridViewerData.isColored ()
Returns:
the color
Definition at line 139 of file GridViewerData.java.
boolean newtonERP.viewers.viewerData.GridViewerData.isSpanSimilar ()
Returns:
the spanSimilar
Definition at line 155 of file GridViewerData.java.
void newtonERP.viewers.viewerData.GridViewerData.removeSpecificActions (String specificActionName)
Parameters:
specificActionName the globalActionName to remove
Definition at line 106 of file GridViewerData.java.
References newtonERP.common.ActionLink.getName().
void newtonERP.viewers.viewerData.GridViewerData.removeSpecificActions (ActionLink SpecificActionName)
Parameters:
SpecificActionName the globalActionName to remove
Definition at line 120 of file GridViewerData.java.
References newtonERP.common.ActionLink.getName().
void newtonERP.viewers.viewerData.GridViewerData.setCases (GridCaseData cases[][])
Parameters:
cases the cases to set
Definition at line 72 of file GridViewerData.java.
void newtonERP.viewers.viewerData.GridViewerData.setColored (boolean isColored)
Parameters:
isColored the color to set
Definition at line 147 of file GridViewerData.java.
void newtonERP.viewers.viewerData.GridViewerData.setHeader (GridCaseData[] header)
Parameters:
header the header to set
Definition at line 40 of file GridViewerData.java.
void newtonERP.viewers.viewerData.GridViewerData.setLeftHeader (GridCaseData[] leftHeader)
Parameters:
leftHeader the leftHeader to set
Definition at line 56 of file GridViewerData.java.
void newtonERP.viewers.viewerData.GridViewerData.setSpanSimilar (boolean spanSimilar)
Parameters:
spanSimilar the spanSimilar to set
Definition at line 163 of file GridViewerData.java.
void newtonERP.viewers.viewerData.GridViewerData.setSpecificActionButtonList (Vector< ActionLink > specificActionButtonList)
Parameters:
specificActionButtonList the specificActionButtonList to set
Definition at line 89 of file GridViewerData.java.
The documentation for this class was generated from the following file:
src/newtonERP/viewers/viewerData/GridViewerData.java