Bee ERP: newtonERP.common.FileModule Class Reference
newtonERP.common.FileModule Class Reference
représente les fichier de module et permet donc de ne pas faire la gestion du systeme de fichier a l'extérieur de cette class
Public Member Functions
FileModule (String name, String filePath)
constructor
String getPackagePathName ()
get a full file path to a package
Module getCache ()
get a cached module
void setCache (Module cache)
set a cached module
String getName ()
get the name of the module
String getFilePath ()
get the path to the modules root package of this module's package
String getPackagePath ()
get the package path to the module (whitout the module name)
Detailed Description
représente les fichier de module et permet donc de ne pas faire la gestion du systeme de fichier a l'extérieur de cette class
Author:
Cloutierjo
Definition at line 15 of file FileModule.java.
Constructor & Destructor Documentation
newtonERP.common.FileModule.FileModule (String name, String filePath)
constructor
Parameters:
name module name
filePath path to the module's root
Definition at line 28 of file FileModule.java.
Member Function Documentation
Module newtonERP.common.FileModule.getCache ()
get a cached module
Returns:
the cached module, return null if there is no cache
Definition at line 52 of file FileModule.java.
String newtonERP.common.FileModule.getFilePath ()
get the path to the modules root package of this module's package
Returns:
the filePath
Definition at line 82 of file FileModule.java.
String newtonERP.common.FileModule.getName ()
get the name of the module
Returns:
the name
Definition at line 72 of file FileModule.java.
Referenced by newtonERP.common.ListModule.addModule(), and newtonERP.common.FileModule.getPackagePathName().
String newtonERP.common.FileModule.getPackagePath ()
get the package path to the module (whitout the module name)
Returns:
the packagePath
Definition at line 91 of file FileModule.java.
Referenced by newtonERP.common.FileModule.getPackagePathName().
String newtonERP.common.FileModule.getPackagePathName ()
get a full file path to a package
Returns:
a full file path to a package
Definition at line 42 of file FileModule.java.
References newtonERP.common.FileModule.getName(), and newtonERP.common.FileModule.getPackagePath().
void newtonERP.common.FileModule.setCache (Module cache)
set a cached module
Parameters:
cache the cache to set
Definition at line 62 of file FileModule.java.
The documentation for this class was generated from the following file:
src/newtonERP/common/FileModule.java