Bee ERP: newtonERP.orm.associations.SingleAccessorManager Class Reference
newtonERP.orm.associations.SingleAccessorManager Class Reference
Cette classe s'occupe de la gestion des accessor 1 à 1 ou plusieurs à 1.
Static Public Member Functions
static final TreeMap< String,
AbstractOrmEntity > getSingleAccessorList (AbstractOrmEntity entity)
static AbstractOrmEntity getSingleAccessor (AbstractOrmEntity abstractOrmEntity, String listOfValueName)
Detailed Description
Cette classe s'occupe de la gestion des accessor 1 à 1 ou plusieurs à 1.
Author:
Guillaume
Definition at line 14 of file SingleAccessorManager.java.
Member Function Documentation
static AbstractOrmEntity newtonERP.orm.associations.SingleAccessorManager.getSingleAccessor (AbstractOrmEntity abstractOrmEntity, String listOfValueName) [static]
Parameters:
abstractOrmEntity entité
listOfValueName nom de l'accessor
Returns:
accessor singulier
Definition at line 69 of file SingleAccessorManager.java.
References newtonERP.module.generalEntity.ListOfValue.getForeignEntityDefinition(), newtonERP.module.AbstractEntity.getPositiveListOfValueList(), and newtonERP.module.AbstractEntity.tryMatchListOfValue().
static final TreeMap<String, AbstractOrmEntity> newtonERP.orm.associations.SingleAccessorManager.getSingleAccessorList (AbstractOrmEntity entity) [static]
Parameters:
entity entité source
Returns:
liste des accessors plusieurs à plusieurs pour l'entité source
Definition at line 20 of file SingleAccessorManager.java.
References newtonERP.module.generalEntity.ListOfValue.getForeignEntityDefinition(), and newtonERP.module.AbstractEntity.getPositiveListOfValueList().
The documentation for this class was generated from the following file:
src/newtonERP/orm/associations/SingleAccessorManager.java