Bee ERP: modules.userRightModule.actions.Login Class Reference
modules.userRightModule.actions.Login Class Reference
Action class that creates all the rights for every module.
Inherits newtonERP::module::AbstractAction.
Public Member Functions
Login ()
constructeur
AbstractEntity doAction (AbstractEntity entity, Hashtable< String, String > parameters)
Abstract method that will be reused by all the actions.
Detailed Description
Action class that creates all the rights for every module.
Author:
cloutierJo
Definition at line 22 of file Login.java.
Member Function Documentation
AbstractEntity modules.userRightModule.actions.Login.doAction (AbstractEntity entity, Hashtable< String, String > parameters) [virtual]
Abstract method that will be reused by all the actions.
Parameters:
entity entite a utiliser a l'intérieur du doAction
parameters list de parametre autre que l'entite
Returns:
l'entite resultante
Implements newtonERP.module.AbstractAction.
Definition at line 33 of file Login.java.
References newtonERP.viewers.viewerData.BaseViewerData.addAlertMessage(), newtonERP.module.generalEntity.Form.addField(), modules.userRightModule.actions.Login.Login(), newtonERP.viewers.viewerData.PromptViewerData.setButtonAction(), and newtonERP.viewers.viewerData.BaseViewerData.setTitle().
The documentation for this class was generated from the following file:
src/modules/userRightModule/actions/Login.java