Bee ERP: newtonERP.viewers.viewables.FloorViewable Interface Reference
newtonERP.viewers.viewables.FloorViewable Interface Reference
Ce qui peut être vu en tant que plan 2D comportant des salles et des corridors.
Inherited by newtonERP.viewers.viewerData.FloorViewerData.
Public Member Functions
int getRowCount ()
boolean isCorridorAt (int x, int y)
String tryGetZoneNameAt (int x, int y)
Vector< ActionLink > getActionLinkListAt (int x, int y)
boolean isWallAt (String string, int x, int y)
Package Functions
int getColumnCount ()
Detailed Description
Ce qui peut être vu en tant que plan 2D comportant des salles et des corridors.
Author:
Guillaume Lacasse
Definition at line 12 of file FloorViewable.java.
Member Function Documentation
Vector<ActionLink> newtonERP.viewers.viewables.FloorViewable.getActionLinkListAt (int x, int y)
Parameters:
x position x
y position y
Returns:
liste des actionLink pour la position spécifiée
Implemented in newtonERP.viewers.viewerData.FloorViewerData.
int newtonERP.viewers.viewables.FloorViewable.getColumnCount () [package]
Returns:
nombre de colonnes
Implemented in newtonERP.viewers.viewerData.FloorViewerData.
Referenced by newtonERP.viewers.firstStep.FloorViewer.getHtmlCode().
int newtonERP.viewers.viewables.FloorViewable.getRowCount ()
Returns:
nombre de rangées
Implemented in newtonERP.viewers.viewerData.FloorViewerData.
Referenced by newtonERP.viewers.firstStep.FloorViewer.getHtmlCode().
boolean newtonERP.viewers.viewables.FloorViewable.isCorridorAt (int x, int y)
Parameters:
x position x
y position y
Returns:
s'il y a un corridor à la position x
Implemented in newtonERP.viewers.viewerData.FloorViewerData.
Referenced by newtonERP.viewers.firstStep.FloorViewer.getHtmlCode().
boolean newtonERP.viewers.viewables.FloorViewable.isWallAt (String string, int x, int y)
Parameters:
string nom de type de mur
x position x de zone
y position y de zone
Returns:
vrai s'il y a un mur à la position indiquée
Implemented in newtonERP.viewers.viewerData.FloorViewerData.
String newtonERP.viewers.viewables.FloorViewable.tryGetZoneNameAt (int x, int y)
Parameters:
x position x
y position y
Returns:
nom de la zone à la position x, y
Implemented in newtonERP.viewers.viewerData.FloorViewerData.
Referenced by newtonERP.viewers.firstStep.FloorViewer.getHtmlCode().
The documentation for this interface was generated from the following file:
src/newtonERP/viewers/viewables/FloorViewable.java