package newtonERP.orm;

import java.sql.ResultSet;
import java.util.Collection;
import java.util.Hashtable;
import java.util.Vector;

import newtonERP.common.ListModule;
import newtonERP.module.AbstractOrmEntity;
import newtonERP.module.Module;
import newtonERP.module.exception.ModuleException;
import newtonERP.orm.exceptions.OrmException;
import newtonERP.orm.field.Field;
import newtonERP.orm.sgbd.AbstractSgbd;
import newtonERP.orm.sgbd.sqlite.SgbdSqlite;
import newtonERP.taskManager.TaskManager;

/**
 * Basic class for the orm. It is used to put the objects in the databse using
 * SqLite3 and its java binding. The orm will receive an entity from which the
 * orm will perform various tasks such as generating the query and executing it
 * obviously. Then it's gonna send the query to the SgbdSqlite class to execute
 * it.
 * 
 * http://www.sqlite.org/lang_keywords.html
 * 
 * TODO: Drop a module (maybe a an array of the entities to drop?)
 * 
 * @author r3hallejo, r3lacasgu
 */
public class Orm
{
    private static AbstractSgbd sgbd = new SgbdSqlite();// On cré la référence

    // vers le SGBD voulu

    /**
     * Alter table
     * 
     * @param entity the entity containing the new field
     * @param field the field to add
     * @return ?
     * @throws OrmException an exception that can occur in the orm
     */
    public static ResultSet addColumnToTable(AbstractOrmEntity entity,
	    Field<?> field) throws OrmException
    {
	return sgbd.addColumnToTable(entity, field);
    }

    /**
     * Use only for complex queries. Use the select that takes only a vector of
     * entities instead
     * 
     * Method used to do search queries done from the views to the databse. The
     * search criterias that has been passed in parameter are a list of string
     * that has been generated by the view modules
     * 
     * @param searchEntity the entity that has to be researched
     * @param searchCriteriasParam the search criterias formatted into strings
     * @return a vector of ormizable entities
     * @throws OrmException an exception that can occur in the orm
     */
    public static Vector<AbstractOrmEntity> select(
	    AbstractOrmEntity searchEntity, Vector<String> searchCriteriasParam)
	    throws OrmException
    {
	return EntityCreator.createEntitiesFromResultSet(sgbd.select(
		searchEntity, searchCriteriasParam), searchEntity);
    }

    /**
     * Uses the new where builder
     * 
     * Method used to do search queries done from the views to the databse. The
     * search criterias that has been passed in parameter are a list of string
     * that has been generated by the view modules
     * 
     * @param searchEntities the entities from which we will perform the search
     * @return the entities
     * @throws OrmException an exception that can occur in the orm
     */
    public static Vector<AbstractOrmEntity> select(
	    Vector<AbstractOrmEntity> searchEntities) throws OrmException
    {
	return EntityCreator.createEntitiesFromResultSet(sgbd
		.select(searchEntities), searchEntities.get(0));
    }

    /**
     * @param searchEntity the single search entity
     * @return the entities that have been selected in the db
     * @throws OrmException an exception that can occurin the orm
     */
    public static Vector<AbstractOrmEntity> select(
	    AbstractOrmEntity searchEntity) throws OrmException
    {
	Vector<AbstractOrmEntity> searchEntities = new Vector<AbstractOrmEntity>();
	searchEntities.add(searchEntity);
	return select(searchEntities);
    }

    /**
     * Select. Use only if you are sure that it will return only 1 entity (or
     * that you want the first entity)
     * 
     * @param searchEntity the entity from which we will perform our search
     * @return the first entity from the result set
     * @throws OrmException an exception that can occur in the orm
     */
    public static AbstractOrmEntity selectUnique(AbstractOrmEntity searchEntity)
	    throws OrmException
    {
	return select(searchEntity).get(0);
    }

    /**
     * Select. Use only if you are sure that it will return only 1 entity (or
     * that you want the first entity)
     * 
     * @param searchEntities the entity from which we will perform our search
     * @return the first entity from the result set
     * @throws OrmException an exception that can occur in the orm
     */
    public static AbstractOrmEntity selectUnique(
	    Vector<AbstractOrmEntity> searchEntities) throws OrmException
    {
	return select(searchEntities).get(0);
    }

    /**
     * Method used to insert an entity in the databse based into the entity
     * passed in parameter
     * 
     * @param newEntity the entity to add
     * @return le id de clé primaire ajoutée
     * @throws Exception si ça fail
     */
    public static int insert(AbstractOrmEntity newEntity) throws Exception
    {
	int primaryKeyValue = sgbd.insert(newEntity);

	if (primaryKeyValue != 0)
	    TaskManager.executeTasks(newEntity, primaryKeyValue);

	return primaryKeyValue;
    }

    /**
     * Insert an entity if no entity matches current field
     * 
     * @param newUniqueEntity New unique entity to insert
     * @throws Exception si insertion fail
     */
    public static void insertUnique(AbstractOrmEntity newUniqueEntity)
	    throws Exception
    {
	if (select(newUniqueEntity).size() < 1)
	    insert(newUniqueEntity);
    }

    /**
     * Method used to delete an entity from the database
     * 
     * @param searchEntity the entity to be researched
     * @param searchCriterias the search criterias for the where clause
     * @throws Exception si effacement fail
     */
    public static void delete(AbstractOrmEntity searchEntity,
	    Vector<String> searchCriterias) throws Exception
    {
	sgbd.delete(searchEntity, searchCriterias);
    }

    /**
     * Uses the new where builder
     * 
     * Method used to delete an entity from the database
     * 
     * @param searchEntities the entities from which we will build our where
     *            clause
     * @throws Exception si effacement fail
     */
    public static void delete(Vector<AbstractOrmEntity> searchEntities)
	    throws Exception
    {
	sgbd.delete(searchEntities);
    }

    /**
     * Using new where builder
     * 
     * Method used to delete an entity from the database
     * 
     * @param searchEntity the entity from which we will build our where
     * @throws Exception si effacement fail
     */
    public static void delete(AbstractOrmEntity searchEntity) throws Exception
    {
	Vector<AbstractOrmEntity> searchEntities = new Vector<AbstractOrmEntity>();
	searchEntities.add(searchEntity);
	delete(searchEntities);
    }

    /**
     * Method used to update / change an entity
     * 
     * @param entityContainingChanges the entity that has been changed and will
     *            be in the orm
     * @param searchCriterias the criterias used by the update
     * @throws Exception si update fail
     */
    public static void update(AbstractOrmEntity entityContainingChanges,
	    Vector<String> searchCriterias) throws Exception
    {
	sgbd.update(entityContainingChanges, searchCriterias);
    }

    /**
     * Uses the new where builder
     * 
     * Method used to update / change an entity
     * 
     * @param searchEntities the entities from which we will build our where
     *            clause
     * @param entityContainingChanges the changes to apply
     * @throws Exception si update fail
     */
    public static void update(Vector<AbstractOrmEntity> searchEntities,
	    AbstractOrmEntity entityContainingChanges) throws Exception
    {
	sgbd.update(searchEntities, entityContainingChanges);
    }

    /**
     * Uses the new where builder
     * 
     * Method used to update / change an entity
     * 
     * @param searchEntity the entities from which we will build our where
     *            clause
     * @param entityContainingChanges the changes to apply
     * @throws Exception si update fail
     */
    public static void updateUnique(AbstractOrmEntity searchEntity,
	    AbstractOrmEntity entityContainingChanges) throws Exception
    {
	sgbd.updateUnique(searchEntity, entityContainingChanges);
    }

    /**
     * Creates the non-existent table from the modules in the database
     * @throws Exception remonte
     */
    public static void createNonExistentTables() throws Exception
    {
	Hashtable<String, String> modules = ListModule.getAllModules();

	for (String key : modules.keySet())
	{
	    try
	    {
		Module module = ListModule.getModule(key);
		createNonExistentTables(module);
	    } catch (ModuleException e)
	    {
		// PrintStackTrace nécéssaire pour afficher l'information de
		// l'exception précédente. Il faudrait mettre l'ancien
		// stackTrace dans le nouveau
		e.printStackTrace();
		throw new ModuleException(
			"Erreur à la construction de la requête pour créer les tables : "
				+ e.getMessage());
	    }
	}
    }

    private static void createNonExistentTables(Module module) throws Exception
    {
	Collection<AbstractOrmEntity> moduleEntities = module
		.getEntityDefinitionList().values();

	// For each entity in the list of module entities
	for (AbstractOrmEntity entity : moduleEntities)
	{
	    createTableForEntity(entity);
	    addMissingColumnsForEntity(entity);
	    createIndexesForEntity(entity);
	}
    }

    private static void addMissingColumnsForEntity(AbstractOrmEntity entity)
    {
	for (Field<?> field : entity.getFields())
	{
	    try
	    {
		sgbd.addColumnToTable(entity, field);
	    } catch (OrmException e)
	    {
		System.out.println("Champ déjà dans entité");
	    }
	}
    }

    private static void createTableForEntity(AbstractOrmEntity entity)
	    throws Exception
    {
	sgbd.createTableForEntity(entity);
    }

    private static void createIndexesForEntity(AbstractOrmEntity entity)
	    throws Exception
    {
	// On cré des index pour chaque clef étrangère
	for (String fieldName : entity.getFields().getKeyList())
	    if ((fieldName.endsWith("ID") && !fieldName.startsWith("PK"))
		    || fieldName.startsWith("system"))
		createIndex(entity.getSystemName(), fieldName);
    }

    /**
     * Sert à ajouter un index dans la table SQL de l'entité pour un field en
     * particulier
     * @param entity entité
     * @param field champ
     * @throws Exception si ça fail
     */
    public static void createIndex(AbstractOrmEntity entity, Field<?> field)
	    throws Exception
    {
	createIndex(entity.getSystemName(), field.getSystemName());
    }

    /**
     * Sert à ajouter un index dans la table SQL de l'entité pour un field en
     * particulier
     * @param entityName nom de l'entité
     * @param fieldName nom du field
     * @throws Exception si ça fail
     */
    public static void createIndex(String entityName, String fieldName)
	    throws Exception
    {
	sgbd.createIndex(entityName, fieldName);
    }

    /**
     * Used to initialize the connection
     * 
     * @throws OrmException an exception that can occur in the orm
     */
    public static void connect() throws OrmException
    {
	sgbd.connect();
    }

    /**
     * Used to disconnect from the db
     * 
     * @throws OrmException an exception that can occur in the orm
     */
    public static void disconnect() throws OrmException
    {
	sgbd.disconnect();
    }

    /**
     * To execute a custom query
     * 
     * @param sqlQuery the executed
     * @throws Exception si exécution fail
     */
    public static void executeCustomQuery(String sqlQuery) throws Exception
    {
	sgbd.execute(sqlQuery, OrmActions.OTHER);
    }

    /**
     * @param entitySystemName nom système d'une entité
     * @return true si l'entité a une table dans la base de donnée, sinon false
     * @throws Exception si ça fail
     */
    public static boolean isEntityExists(String entitySystemName)
	    throws Exception
    {
	return sgbd.isEntityExists(entitySystemName);
    }

    /**
     * @param searchEntity entité de recherche
     * @param searchCriteriasParam critères de recherche
     * @param limit limite de résultats
     * @param offset offset de début de résultats
     * @return liste d'entités trouvées
     * @throws OrmException si ça fail
     */
    public static Vector<AbstractOrmEntity> select(
	    AbstractOrmEntity searchEntity,
	    Vector<String> searchCriteriasParam, int limit, int offset)
	    throws OrmException
    {
	return select(searchEntity, searchCriteriasParam, limit, offset, null);
    }

    /**
     * @param searchEntity entité de recherche
     * @return nombre d'occurence du type de l'entité de recherche
     * @throws Exception si ça fail
     */
    public static int count(AbstractOrmEntity searchEntity) throws Exception
    {
	return count(searchEntity, null);
    }

    /**
     * @param searchEntity entité de recherche
     * @param searchParameterList liste de paramètres de recherche
     * @return nombre d'occurence du type de l'entité de recherche
     * @throws Exception si ça fail
     */
    public static int count(AbstractOrmEntity searchEntity,
	    Vector<String> searchParameterList) throws Exception
    {
	return sgbd.count(searchEntity, searchParameterList);
    }

    /**
     * Fait un backup de la DB si l'intervale de temps est assez grande
     */
    public static void doBackupIfTimeIntervalAllows()
    {
	long currentTime = BackupManager.getCurrentTime();
	long latestBackupTime = sgbd.getLatestBackupTime();
	long desiredBackupTimeInterval = BackupManager
		.getDesiredBackupIntervalTime();

	if (currentTime - latestBackupTime > desiredBackupTimeInterval)
	    sgbd.doBackup();
    }

    /**
     * @param searchEntity entité
     * @param searchParameters critère de recherche
     * @param limit limite
     * @param offset offset
     * @param orderBy ordre
     * @return liste d'entité
     * @throws OrmException si ça fail
     */
    public static Vector<AbstractOrmEntity> select(
	    AbstractOrmEntity searchEntity, Vector<String> searchParameters,
	    int limit, int offset, String orderBy) throws OrmException
    {
	return EntityCreator.createEntitiesFromResultSet(sgbd.select(
		searchEntity, searchParameters, limit, offset, orderBy),
		searchEntity);
    }
}
